### ISSUE TITLE
Verschwommene Ansicht iphone 11 pro max 

### ISSUE THREAD

**Issue by papagei1996** [sbormann/ioBroker.iqontrol#100]
![F754326D-A59B-406A-B0A2-FD432FE1BC0E](https://user-images.githubusercontent.com/56414714/70281721-0990da80-17bc-11ea-8006-a7134d86ab99.png)
![85CA1E84-8EE6-4139-B152-1C0D69BF5C3D](https://user-images.githubusercontent.com/56414714/70281741-157c9c80-17bc-11ea-9755-cc87d30c15db.png)

Habe das Problem welches es damals mit force touch beim iPhone x gab nun mit dem neuen display beim iPhone 11 pro max welches nun nicht mehr über die Stärke des drucks sondern über die Länge des drucks geht. Somit ist bei mir oft das Bild verschwommen siehe Anhang und das pop up Fenster geht auf welches eigentlich nur bei langem drücken aufgehen sollte obwohl ich nur einmal kurz drücke. Eine Einstellung diese Funktion konplett zu deaktivieren wäre cool wenn das für euch einfach umzusetzen wäre.

**Comment by sbormann** [comment]
Hi, welche Version von iQontrol nutzt du? Ich dachte nämlich, das Problem sei bereits gelöst worden.

**Comment by papagei1996** [comment]
Hey benutze die Version 0.2.14
Ja das Problem gab es mal beim iPhone x und dem force touch jetzt beim iPhone 11 gibt es ja das 3d touch oder wie auch immer die das nennen und seitdem habe ich das Problem zwar selten aber ab und zu wieder 

Gruß Jannik 

Von meinem iPhone gesendet

**Comment by sbormann** [comment]
Ja, kommt bei mir auch ab und an vor. Habe den Fehler aber leider noch nicht finden können.
Ich denke, ich werde demnächst auf die Auswertung des Drucks (forced Touch) verzichten und alles über einen längere Berührung steuern, so wie es die neuen Apple-Geräte ohne forced Touch ja auch machen.

**Comment by allmyjoes** [comment]
> Ja, kommt bei mir auch ab und an vor. Habe den Fehler aber leider noch nicht finden können.
> Ich denke, ich werde demnächst auf die Auswertung des Drucks (forced Touch) verzichten und alles über einen längere Berührung steuern, so wie es die neuen Apple-Geräte ohne forced Touch ja auch machen.

Wäre es möglich, forced Touch ziemlich zeitnah herauszunehmen? Oder zumindest in den Einstellungen anzubieten, ob es genutzt werden soll oder nicht. Aktuell ist es so gut wie gar nicht nutzbar (in max. 1 von 5 Fällen wird die Aktion ausgeführt, die ich möchte).

Danke und Gruß

**Comment by sbormann** [comment]
Bitte mal die 0.4.1 probieren - klappt es jetzt? Bitte kurze Rückmeldung. VG!

**Comment by allmyjoes** [comment]
> Bitte mal die 0.4.1 probieren - klappt es jetzt? Bitte kurze Rückmeldung. VG!

Danke für das Update! Hab es installiert und läuft auf meinem Android Gerät einwandfrei. Das iPhone mit dem Problem bzgl. forced Touch steht jetzt gerade die nächsten 2 Wochen leider nicht zur Verfügung. Anschließend würde ich es aber direkt testen und ein Feedback geben.

**Comment by papagei1996** [comment]
Habe mal eben installiert und etwas drin Rum geklickt. Bisher keine Fehler mehr! 

Gruß Jannik

Von meinem iPhone gesendet

**Comment by allmyjoes** [comment]
Ich habe es nun ebenfalls auf meinem Iphone Xr probiert und nun funktioniert es einwandfrei mit der Einstellung unter Optionen -> Sonstiges -> Druck / ForcedTouch "Immer Zeit statt Druck nutzen". Vielen Dank!

**Comment by sbormann** [comment]
Wunderbar, freut mich, dass es jetzt endlich besser läuft. In der nächsten Version werden dann noch ein paar Fine-Tunings vorgenommen. VG!
