### ISSUE TITLE
Zustände werden plötzlich nicht mehr erkannt

### ISSUE THREAD

**Issue by MikeyRZW** [sbormann/ioBroker.iqontrol#102]
Hi,
plötzlich werden keine Zustaände mehr erkannt.
Ich habe schon die komplette Instanz neu installiert.
Import / Export und Adapter neu installieren hat auch nicht geholfen.
Habt ihr noch einen Tip für mich?

![grafik](https://user-images.githubusercontent.com/45110596/71493915-66bfff00-2843-11ea-8b28-56da1758fc79.png)

![grafik](https://user-images.githubusercontent.com/45110596/71493900-35dfca00-2843-11ea-9c26-ccc4578dca77.png)

**Comment by MikeyRZW** [comment]
Hmm,
die meisten Geräte lassen sich auch nicht mehr ändern...

Ideen / Tips ??

![grafik](https://user-images.githubusercontent.com/45110596/71561910-54310a00-2a7d-11ea-878e-86fd3db868c4.png)

**Comment by sbormann** [comment]
Duplicate of #104 

Entspricht glaube ich dem Issue #104 - wird gefixed mit der nächsten Version.

**Comment by sbormann** [comment]
0.2.15 ist online. Gehts damit?

**Comment by MikeyRZW** [comment]
Ja, es scheint alles wieder zu funktionieren.
Zustände werden wieder sofort gelesen, Geräte lassen sich wieder ändern und schalten.
Es sieht so aus als wenn es das war.
Danke.
