### ISSUE TITLE
Wettervorhersage

### ISSUE THREAD

**Issue by Masterg4941** [sbormann/ioBroker.iqontrol#103]
Hallo,

sehr gerne nutze ich seit neuestem den IQontrol Adapter zum Visualisieren meiner Datenpunkte. 
Nun musste ich leider feststellen, dass es nicht möglich ist eine "Wettervorhersage", wie z.B. soeine externe Bilddatei, vernünftig dar zu stellen.[https://www.daswetter.com/wimages/foto9b63eed9a30f50519e0ebbb363d15500.png](url)

Gibt es hier ggf. Zukunftspläne, wo dies integriert werden soll?
Da ich den Aufwand sehr schlecht einschätzen kann hier einmal plump gefragt:
Ist es möglich die Kacheln dynamisch zu gestalten? Also das man diese per drag&drop vergrößern oder verkleinern kann? Dann könnte man die Wettervorhersage auch einfach als "Hintergrundbild" einer Kachel hinterlegen. 

Auf jeden Fall vielen Dank für den Adapter! Er ist sehr einfach zu bedienen und schaut super aus!

LG

**Comment by liv-in-sky** [comment]
über ein popup und einem iframe - man könnte auch noch andere infos reinsetzen oder evtl einen anderen background - meinst du sowas? greift direkt auf die webseite zu

![Image 11](https://user-images.githubusercontent.com/18462890/71593690-5b1b5380-2b35-11ea-8a99-6cdbfd4df0c2.png)

**Comment by Masterg4941** [comment]
Ja die Frame-Funktion habe ich entdeckt. Dies funktioniert auch soweit sehr gut. 
Nur ist es halt immer ein Popup, dass geöffnet werden muss. 
Ich denke da eher an den "home" bzw. Startbildschirm wo die wichtigsten Daten auf den ersten Blick zu sehen sein sollen. Und demnach auch das Wetter direkt zu sehen ist, ohne es noch anklicken zu müssen. 

LG

**Comment by sbormann** [comment]
Hi,
eine Anpassung der Kachelgröße ist vorerst nicht geplant (viel Aufwand - wenig Zeit :))

Aber mit etwas Spielen habe ich folgendes hinbekommen:
![image](https://user-images.githubusercontent.com/49171332/71785483-51479380-3000-11ea-95ac-bbd1a53f2244.png)

daswetter.com/widget:
![image](https://user-images.githubusercontent.com/49171332/71785496-6cb29e80-3000-11ea-8595-3bea8d64ab32.png)

Als Device ein Popup mit dem oben generierten Hintergrundbild, Icon ausgeblendet, Device-Name ausgeblendet, Überzug ausgeblendet. Als Popup-URL kann man dann z.B. das große Widget mit allen Infos hinterlegen und auch noch die Popup-Breite und Höhe passend angeben:
![image](https://user-images.githubusercontent.com/49171332/71785516-c31fdd00-3000-11ea-8076-0fe1984fe210.png)


Reicht das? 

VG

**Comment by Masterg4941** [comment]
Sieht gut aus. Das sollte gehen. Danke dir!
