### ISSUE TITLE
Pictures missing / iqontrol.meta 

### ISSUE THREAD

**Issue by realwax** [sbormann/ioBroker.iqontrol#105]
JScontroller 2.2.7
nodejs/NPM 10.17 / 6.13
redis/redis
multihost

Default pictures and icons can't be found.  Files are existing in iqcontrol's node_module folder but will not be copied to iobroker-data/files/iqcontrol....

iobroker upload iqontrol - does not do the job.

When I create new folders and upload pictures into the adapter via its own feature a iqontrol.meta path shows up in the browser. But nothing can be found in the file system. I assume it makes use of redis and uploads files there?!?

How can I easily fix that - i'd lilke to make the basic installation picture and icons available with uploading one by one...

Thanks for your help

Wolfgang

**Comment by sbormann** [comment]
Sorry, im not completely shure, what you mean.
Do you speak german (Wolfgang sounds german)?
Maybe you could post that question on the iobroker forum?
https://forum.iobroker.net/topic/26684/test-adapter-iqontrol-v0-2-x/116

**Comment by realwax** [comment]
> Sorry, im not completely shure, what you mean.
> Do you speak german (Wolfgang sounds german)?
> Maybe you could post that question on the iobroker forum?
> https://forum.iobroker.net/topic/26684/test-adapter-iqontrol-v0-2-x/116
Hallo @sbormann 
Klar, spreche ich deutsch. Es gibt ein Problem mit den Bildern deines iqcontrol in Zusammenhang mit aktuellen JScontroller und redis/redis. 
Die Bilder und Icons kommen in den node_module Ordner, werden aber nicht kopiert, noch sind sie in deiner Bilderverwaltung verfügbar. Legt man in deiner Bilderverwaltung einen Ordner an und verwendet das Bild sieht man als Pfad mitunter iqcontrol.meta. Dies ist aber wiederum nicht im file System auffindbar. Ich nehme an es wird im redis angelegt. Der Endeffekt ist man muss händisch nachbessern. Ich wollte wissen ob du bescheid weißt bzw eine Lösung hast deine Bilder und Icons nachträglich upzuloaden abseits deiner Bildverwaltung. Speziell bei den Icons. Sind die Pfade noch irgendwo in der App coded? Oder es ist nur sample content. 

Danke und LG

Wolfgang

**Comment by sbormann** [comment]
Ich habe das jetzt noch mal nachgestellt, bei mir werden die Bilder ordnungsgemäß in den iobroker-data/files/iqcontrol-meta Ordner kopiert. Besteht das Problem immer noch?

**Comment by d1nd141** [comment]
Hallo,
hab so ein ähnliches (oder gleiches?) Problem.
Hab keine Icons zur Auswahl. (Alle Browser getestet, cache natürlich gelöscht.)
"Upload" auch schon durch. (RC=0)
![image](https://user-images.githubusercontent.com/13020602/80566214-bf222b80-89f2-11ea-8bfb-76958ad03c30.png)

root@master:/opt/iobroker/iobroker-data/files/iqontrol.meta/userimages# ls -latr
total 16
drwxr-xr-x+ 3 iobroker iobroker 4096 Mar  6 17:21 ..
drwxr-xr-x+ 2 iobroker iobroker 4096 Mar  6 17:21 .
root@master:/opt/iobroker/iobroker-data/files/iqontrol.meta/userimages#

Im node_modules folder sind die png's:
root@master:/opt/iobroker/node_modules/iobroker.iqontrol/www/userimages/usericons# find ./
./
./inbuilt
./inbuilt/button_pressed.png
./inbuilt/gas_off.png
./inbuilt/battery_10.png
./inbuilt/garagedoor_opening.png
./inbuilt/gas_on.png

usw.

**Comment by sbormann** [comment]
Hi, 
könnt ihr mal bitte schauen, was die Entwicklerkonsole ausgibt, wenn ihr die Einstellungen von iQontrol öffnet? Also ioBroker öffnen, F12 drücken und ins Console-Window wechseln und dann die iQontrol-Settings öffnen. Das müsste dann in etwa so aussehen:

![image](https://user-images.githubusercontent.com/49171332/82069768-18b57600-96d4-11ea-9ca6-39555f9cfe5e.png)

**Comment by realwax** [comment]
Jup - ich habe das Problem nicht mehr.
![image](https://user-images.githubusercontent.com/14924590/82081149-21af4300-96e6-11ea-8ccf-4673d228dc39.png)

**Comment by sbormann** [comment]
Perfekt, danke!

**Comment by d1nd141** [comment]
Leider nein :-(
![image](https://user-images.githubusercontent.com/13020602/82091400-9048cc80-96f7-11ea-883b-2ff38e8782ce.png)

**Comment by sbormann** [comment]
Kannst Du bitte noch mal auf das index_m.html in der Fehlermeldung klicken und mir das noch mal schicken?

--
Von meinem iPhone aus gesendet

Am 15.05.2020 um 22:01 schrieb d1nd141 <notifications@github.com>:

﻿

Leider nein :-(
[image]<https://user-images.githubusercontent.com/13020602/82091400-9048cc80-96f7-11ea-883b-2ff38e8782ce.png>

**Comment by d1nd141** [comment]
Klar:
![image](https://user-images.githubusercontent.com/13020602/82094390-41059a80-96fd-11ea-9b9d-cf91dc7b065d.png)

**Comment by sbormann** [comment]
Hi, diese Zeile ist schon seit einigen Versionen deaktiviert, d.h. irgendwie bist Du noch auf einer alten Version, vermutlich ist irgendwann mal bei einem Update was schief gegangen. Bitte mach mal folgendes:
https://github.com/sbormann/ioBroker.iqontrol#troubleshooting

**Comment by d1nd141** [comment]
Hab jetzt den Browser cache komplett gelöscht, iqontrol uninstalled und neu installiert.
Wieder gleich die gleichen Probleme:

`$ ./iobroker add iqontrol  --host master
NPM version: 6.14.4
npm install iobroker.iqontrol@0.2.16 --loglevel error --prefix "/opt/iobroker" (System call)
host.master install adapter iqontrol
upload [30] iqontrol.admin /opt/iobroker/node_modules/iobroker.iqontrol/admin/words.js words.js application/javascript
upload [20] iqontrol.admin /opt/iobroker/node_modules/iobroker.iqontrol/admin/materialize-colorpicker/img/materialize-colorpicker/alpha.png materialize-colorpicker/img/materialize-colorpicker/alpha.png image/png
upload [19] iqontrol.admin /opt/iobroker/node_modules/iobroker.iqontrol/admin/materialize-colorpicker/img/materialize-colorpicker/alpha-horizontal.png materialize-colorpicker/img/materialize-colorpicker/alpha-horizontal.png image/png
upload [18] iqontrol.admin /opt/iobroker/node_modules/iobroker.iqontrol/admin/materialize-colorpicker/css/materialize-colorpicker.min.css materialize-colorpicker/css/materialize-colorpicker.min.css text/css
upload [17] iqontrol.admin /opt/iobroker/node_modules/iobroker.iqontrol/admin/materialize-colorpicker/css/materialize-colorpicker.css materialize-colorpicker/css/materialize-colorpicker.css text/css
upload [16] iqontrol.admin /opt/iobroker/node_modules/iobroker.iqontrol/admin/jQueryIcons.jpg jQueryIcons.jpg image/jpeg
upload [15] iqontrol.admin /opt/iobroker/node_modules/iobroker.iqontrol/admin/iqontrol.png iqontrol.png image/png
upload [14] iqontrol.admin /opt/iobroker/node_modules/iobroker.iqontrol/admin/index_m.js index_m.js application/javascript
upload [13] iqontrol.admin /opt/iobroker/node_modules/iobroker.iqontrol/admin/index_m.html index_m.html text/html
upload [12] iqontrol.admin /opt/iobroker/node_modules/iobroker.iqontrol/admin/img/info-big.png img/info-big.png image/png
upload [11] iqontrol.admin /opt/iobroker/node_modules/iobroker.iqontrol/admin/fonts/font_verdana.png fonts/font_verdana.png image/png
upload [10] iqontrol.admin /opt/iobroker/node_modules/iobroker.iqontrol/admin/fonts/font_trebuchet.png fonts/font_trebuchet.png image/png
upload [9] iqontrol.admin /opt/iobroker/node_modules/iobroker.iqontrol/admin/fonts/font_times.png fonts/font_times.png image/png
upload [8] iqontrol.admin /opt/iobroker/node_modules/iobroker.iqontrol/admin/fonts/font_impact.png fonts/font_impact.png image/png
upload [7] iqontrol.admin /opt/iobroker/node_modules/iobroker.iqontrol/admin/fonts/font_georgia.png fonts/font_georgia.png image/png
upload [6] iqontrol.admin /opt/iobroker/node_modules/iobroker.iqontrol/admin/fonts/font_garamond.png fonts/font_garamond.png image/png
upload [5] iqontrol.admin /opt/iobroker/node_modules/iobroker.iqontrol/admin/fonts/font_courier.png fonts/font_courier.png image/png
upload [4] iqontrol.admin /opt/iobroker/node_modules/iobroker.iqontrol/admin/fonts/font_comic.png fonts/font_comic.png image/png
upload [3] iqontrol.admin /opt/iobroker/node_modules/iobroker.iqontrol/admin/fonts/font_arial.png fonts/font_arial.png image/png
upload [2] iqontrol.admin /opt/iobroker/node_modules/iobroker.iqontrol/admin/custom_m.html custom_m.html text/html
upload [1] iqontrol.admin /opt/iobroker/node_modules/iobroker.iqontrol/admin/conn.js conn.js application/javascript
upload [0] iqontrol.admin /opt/iobroker/node_modules/iobroker.iqontrol/admin/admin.d.ts admin.d.ts video/mp2t
upload [450] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/userimages/usericons/inbuilt/link_plain_internal.png userimages/usericons/inbuilt/link_plain_internal.png image/png
upload [400] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/userimages/usericons/inbuilt/blank.png userimages/usericons/inbuilt/blank.png image/png
upload [350] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/jquery/images/icons-svg/refresh-white.svg jquery/images/icons-svg/refresh-white.svg image/svg+xml
upload [300] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/jquery/images/icons-svg/carat-r-white.svg jquery/images/icons-svg/carat-r-white.svg image/svg+xml
upload [250] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/jquery/images/icons-png/refresh-white.png jquery/images/icons-png/refresh-white.png image/png
upload [200] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/jquery/images/icons-png/carat-r-white.png jquery/images/icons-png/carat-r-white.png image/png
upload [150] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/images/stop.png images/stop.png image/png
upload [100] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/images/icons/light_desklamp_on.png images/icons/light_desklamp_on.png image/png
upload [90] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/images/icons/indicator_yellow.png images/icons/indicator_yellow.png image/png
upload [80] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/images/icons/gas_off.png images/icons/gas_off.png image/png
upload [70] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/images/icons/fire_off.png images/icons/fire_off.png image/png
upload [60] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/images/icons/camera_ptz_on.png images/icons/camera_ptz_on.png image/png
upload [50] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/images/icons/blind_closed.png images/icons/blind_closed.png image/png
upload [40] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/images/icons/battery_50.png images/icons/battery_50.png image/png
upload [30] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/images/hue.png images/hue.png image/png
upload [20] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/images/config.png images/config.png image/png
upload [19] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/images/colortemperature.png images/colortemperature.png image/png
upload [18] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/images/color.png images/color.png image/png
upload [17] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/images/brightness.png images/brightness.png image/png
upload [16] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/images/battery.png images/battery.png image/png
upload [15] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/images/background.png images/background.png image/png
upload [14] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/i18n/zh-cn/translations.json i18n/zh-cn/translations.json application/json
upload [13] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/i18n/ru/translations.json i18n/ru/translations.json application/json
upload [12] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/i18n/pt/translations.json i18n/pt/translations.json application/json
upload [11] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/i18n/pl/translations.json i18n/pl/translations.json application/json
upload [10] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/i18n/nl/translations.json i18n/nl/translations.json application/json
upload [9] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/i18n/it/translations.json i18n/it/translations.json application/json
upload [8] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/i18n/fr/translations.json i18n/fr/translations.json application/json
upload [7] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/i18n/es/translations.json i18n/es/translations.json application/json
upload [6] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/i18n/en/translations.json i18n/en/translations.json application/json
upload [5] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/i18n/de/translations.json i18n/de/translations.json application/json
upload [4] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/favicon_big.png favicon_big.png image/png
upload [3] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/favicon.png favicon.png image/png
upload [2] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/favicon.ico favicon.ico image/vnd.microsoft.icon
upload [1] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/conn.js conn.js application/javascript
upload [0] iqontrol /opt/iobroker/node_modules/iobroker.iqontrol/www/cache.manifest cache.manifest text/cache-manifest
host.master object system.adapter.iqontrol created/updated
host.master object iqontrol.meta created/updated
host.master create instance iqontrol
host.master object system.adapter.iqontrol.upload created
host.master object system.adapter.iqontrol.0.sigKill created
host.master object system.adapter.iqontrol.0.eventLoopLag created
host.master object system.adapter.iqontrol.0.outputCount created
host.master object system.adapter.iqontrol.0.inputCount created
host.master object system.adapter.iqontrol.0.uptime created
host.master object system.adapter.iqontrol.0.memRss created
host.master object system.adapter.iqontrol.0.memHeapTotal created
host.master object system.adapter.iqontrol.0.memHeapUsed created
host.master object system.adapter.iqontrol.0.cputime created
host.master object system.adapter.iqontrol.0.cpu created
host.master object system.adapter.iqontrol.0.compactMode created
host.master object system.adapter.iqontrol.0.connected created
host.master object system.adapter.iqontrol.0.alive created
host.master object system.adapter.iqontrol.0 created
process exited with code 0`


![image](https://user-images.githubusercontent.com/13020602/82112102-2279c080-974a-11ea-9fa0-a34c9f7c86eb.png)

**Comment by sbormann** [comment]
Du versuchst iQontrol 0.2.16 zu installieren, also die letzte stable. Bitte stelle mal den Verwahrort in den ioBroker Hautpeinstellungen auf latest und aktualisier mal auf die aktuelle Version (0.4.1). Ggf. müssten auch admin und js-controller mal auf die neuesten Versionen aktualisiert werden. Und ggf. mal den ioBroker neu starten nach dem deinstallieren. Mehr fällt mir jetzt auf die Schnelle nicht ein.

**Comment by d1nd141** [comment]
Fehler bleibt, hab alles auf latest updated, natürlich neu gestartet.
Werde noch einmal versuchen iobroker komplett neu zu installieren. Sollte dies weiterhin nicht funktionieren, bleib ich wohl bei fhem. Schade :-( Sieht echt nett aus. Dank Dir für Deine Mühe!

**Comment by d1nd141** [comment]
Nur als Info, hab im Proxmox nen Container mir Debian10 erstellt (alles updated).
Hier nur iobroker latest (repo) updates, Module: FHEM, VIS, Web, Conbee und iqontrol.
Gleiches Problem, keine (Background) Images werden zur Auswahl angezeigt.
Werde später noch Ubuntu versuchen.

**Comment by sbormann** [comment]
Hmm, das ist ja wirklich komisch. Kannst Du denn eigene Bilder hochladen?

--
Von meinem iPhone aus gesendet

Am 17.05.2020 um 18:53 schrieb d1nd141 <notifications@github.com>:

﻿

Nur als Info, hab im Proxmox nen Container mir Debian10 erstellt (alles updated).
Hier nur iobroker latest (repo) updates, Module: FHEM, VIS, Web, Conbee und iqontrol.
Gleiches Problem, keine (Background) Images werden zur Auswahl angezeigt.
Werde später noch Ubuntu versuchen.

**Comment by d1nd141** [comment]
Jup, das geht, kann diese dann auch auswählen:
![image](https://user-images.githubusercontent.com/13020602/82158826-81deea00-988a-11ea-80a8-3184a438881a.png)

Die mitgelieferten Bilder werden auch gefunden:
root@CT102:/# find / -name bottle.jpg |xargs ls -latr
-rwxr-xr-x+ 1 iobroker iobroker 396131 Oct 26  1985 /opt/iobroker/node_modules/iobroker.iqontrol/www/userimages/demo/bottle.jpg
-rw-rw-r--+ 1 iobroker iobroker 396131 May 17 16:42 /opt/iobroker/iobroker-data/files/iqontrol/userimages/demo/bottle.jpg

Jedoch ist mein uploaded Bild in nem anderen Folder:

**Comment by d1nd141** [comment]
Keine Ahnung ob's Normal ist:
Die Folder werden Linux/Win angezeigt:
![image](https://user-images.githubusercontent.com/13020602/82180318-91891d80-98e0-11ea-87e4-5dd8cf301afc.png)

Anderes "Problem" Clicke ich auf save, erhalte ich das übliche Popup "Please confirm

Some data are not stored. Discard?" als würde ich das Fenster schliessen wollen. Gespeichert wird trotzdem.

**Comment by sbormann** [comment]
Also ich fasse noch mal zusammen, ob ich es richtig verstanden habe:
Was fehlt sind aktuell nur die demo-Bilder (die sind im falschen Ordner), richtig? Ansosten geht alles? Icons sind da und eigene Bilder und Icons lassen sich hochladen und benutzen?

Zum "Some data are not stored Problem" - ist vermutlich ein Fehler im Admin, dafür existiert bereits ein Issue.

**Comment by d1nd141** [comment]
Bei Devices oder Views hab ich keine Bilder (also die welche mitgeliefert werden) zur Auswahl.
Wenn ich Bilder hochlade, werden diese zur Auswahl angegeben, und nur die.
![image](https://user-images.githubusercontent.com/13020602/82320969-6da70400-99d4-11ea-945f-fac2e212328c.png)

![image](https://user-images.githubusercontent.com/13020602/82321013-7f88a700-99d4-11ea-84e3-a7eb008b48a6.png)


root@master:~# find / -name orangedrops.jpg |xargs ls -latr
-rwxr-xr-x+ 1 iobroker iobroker 576097 Oct 26  1985 /opt/iobroker/node_modules/iobroker.iqontrol/www/userimages/demo/orangedrops.jpg
-rw-rw-r--+ 1 iobroker iobroker 576097 May 16 10:50 /opt/iobroker/iobroker-data/files/iqontrol/userimages/demo/orangedrops.jpg
root@master:~# find / -name fp_Keller.png |xargs ls -latr
-rw-rw-r--+ 1 iobroker iobroker 24257 May 19 13:24 /opt/iobroker/iobroker-data/files/iqontrol.meta/userimages/fp_Keller.png


Ich hatte Iqontrol vor langer Zeit schon am laufen, hab dann jedoch eine neue VM aufgesetzt, und bei 0 wieder angefangen. Damals ging alles.

Momentan geht Iqontrol überhaupt nicht mehr auf (seitdem ändern vom Repo auf latest)

![image](https://user-images.githubusercontent.com/13020602/82321315-ed34d300-99d4-11ea-875f-4670c66ff032.png)

**Comment by d1nd141** [comment]
Allerdings muss ich auch sagen:
Diese Tests sind in Debian10 (alles updated) getätigt worden.

In Ubuntu 20 (server edition) & Centos8 im LX container auf Proxmox hab ich genau die gleichen Probleme.

**Comment by AxelRHD** [comment]
Ich habe exakt das gleiche Problem (keine Anzeige der Bilder im Demo-Ordner und keine Auswahl möglich).

Node.js: v12.18.4
NPM: 6.14.6
Installationsart: Docker Container

Gibt es hier seit Mai weitere Entwicklungen?

**Comment by d1nd141** [comment]
Bei mir leider nicht. Hab iqontrol LEIDER nicht mehr im gebrauch.
