### ISSUE TITLE
Add admin/img/big-info.png icon

### ISSUE THREAD

**Issue by GermanBluefox** [sbormann/ioBroker.iqontrol#106]
because this icon will be loaded if no image found, elsewise we have endless loop in selectID Dialog

https://github.com/ioBroker/ioBroker.admin/blob/master/src/img/info-big.png

**Comment by sbormann** [comment]
should the filename be big-info.png or info-big.png?
(In the headline it differs to the linked filename)
Greetings!

**Comment by sbormann** [comment]
@GermanBluefox : should the filename be big-info.png or info-big.png?
