### ISSUE TITLE
Iqontrol 0.2.15 ins Stable

### ISSUE THREAD

**Issue by Starcon79** [sbormann/ioBroker.iqontrol#107]
Hallo wäre es möglich die Iqontrol 0.2.15 ins Stable zu ziehen da dies Vorraussetzung ist für Admin 3.7.8 und js-controller 2.2.
Siehe:
https://forum.iobroker.net/topic/29435/js-controller-2-2-jetzt-f%C3%BCr-alle-im-stable/5

und:
https://github.com/sbormann/ioBroker.iqontrol/issues/104

Danke.

**Comment by sbormann** [comment]
Ja, alles klar, mach ich. VG
