### ISSUE TITLE
IOBroker startet komplett neu, bei öffen der Konfig Seite auf Instanz

### ISSUE THREAD

**Issue by Flashy-GER** [sbormann/ioBroker.iqontrol#109]
Der ioBroker startet neu, wenn  ich die Konfigurationsseite über die Instanz anwähle und öffne.
Alle Instanzen fahren runter und wieder hoch.
Es kann auch keine Änderung an der Konfiguration durchgeführt werden.

---

**System data:**

Platform: linux
Distribution: Raspbian GNU/Linux
Architecture: arm
Model: ARMv7 Processor rev 3 (v7l)
RAM: 3.81 GB
Node.js: v10.18.1
NPM: 6.13.6
JS-Controller (1): 2.2.8
Admin: 3.7.9
iQontrol: 0.2.16

> *created by ioBroker.info*

**Comment by Flashy-GER** [comment]
Zusatzinfo: dieser Fehler tritt auf und ist reproduzierbar, wenn man den ioBroker im Modus File / Redis betreibt, also Objekte in Files und States in die Redis DB schreibt.
er kann hier keine Objekte anlegen und als Folgefehler wird dem Java Controller die DB weggezogen

**Comment by unicast92** [comment]
Ich habe das selbe Problem seit dem Update auf den JS-Controller 2.2.x.

Bitte um einen Fix oder Workaround.

Gruß
Unicast

**Comment by aDabbelju** [comment]
Hier ebenfalls das Problem. Bei mir startet leider nichts neu. Die Admin-Konsole ist leider nicht mehr aufrufbar danach.

**Comment by siggi85** [comment]
Durch ein Update von JS Controller 2.2.8 auf 2.2.9 konnte ich das Problem bei mir beheben.
