### ISSUE TITLE
SVG file upload error

### ISSUE THREAD

**Issue by tonic12** [sbormann/ioBroker.iqontrol#111]
Hi, now i'm trying iQontrol and have problem with upload svg files to iqontrol. I look code admin page and find line: 

`<input type="file" multiple accept="image/png, image/jpeg, image/jpg, image/gif, image/svg" id="imagesUploadFile" name="imagesUploadFile" />`.

If we add type `image/svg+xml` all is work: 

`<input type="file" multiple accept="image/png, image/jpeg, image/jpg, image/gif, image/svg, image/svg+xml" id="imagesUploadFile" name="imagesUploadFile" />` 

I think it's a bug.

**Comment by sbormann** [comment]
Will be fixed in next version.
