### ISSUE TITLE
Speichern führt zu Meldung "Nicht alle Änderungen wurden gespeichert"

### ISSUE THREAD

**Issue by martinschm** [sbormann/ioBroker.iqontrol#113]
**Describe the bug**  
Wenn ich aktuell eine Änderung Speicher bzw einfach nur auf den Speichern Button klicke, kommt immer die Meldung, das einige Änderungen nicht gespeichert wurden.

Siehe Screenshot.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/39886158/76228265-ca41b200-6220-11ea-895d-03133e2c7c2c.png)

Ein Dump der Entwickler Console hab ich jetzt mal nicht angehängt. Da wurden 615 KB produziert, wo sämtliche Geräte IDs etc drin stehen.

**Versions:**  
 - Adapter version: 2.16
 - JS-Controller version: 2.2.8 
 - Node version: v10.16.3
 - Operating system: debian

**Comment by Sacred-Shadow** [comment]
Hab ich leider auch öfter aber auch nicht immer. 

Klickanblauf:
Adapter öffnen => Geräte => beliebige Ansicht öffnen => Rechts unten auf Abbrechen

**Comment by sbormann** [comment]
Ich habe das bei mehreren Adaptern, nicht nur bei iQontrol, seit Update auf js-controller 2.0

Ich konnte keine Lösung finden und habe das ganze selbst als Frage ins Forum gepostet:
https://forum.iobroker.net/topic/32243/fehler-einige-daten-wurden-nicht-gespeichert-verwerfen

Da es, glaube ich, kein iQontrol-Problem ist, sondern eher ein admin-Problem, schließe ich den Thread hier, bitte im Forum weiter diskutieren. Danke und VG!
