### ISSUE TITLE
Groß/Kleinschreibung bei ALTERNATIVE_COLORSPACE_VALUE

### ISSUE THREAD

**Issue by siggi85** [sbormann/ioBroker.iqontrol#114]
**Describe the bug**  
Ich nutze iQontrol in Kombination mit Shelly RGBW2's. Hier wird der RGBW Wert anscheinend in Großbuchstaben gespeichert. Wenn ich nun eine Ansicht in iQontrol öffne (ich öffne nur die Ansicht und versuche gerade nichts zu schalten), indem ein RGBW2 als Gerät existiert, setzt er den aktuellen RGBW-Wert auf den gleichen Wert aber mit kleingeschriebenen Buchstaben und der Shelly bzw. Shelly Adapter korrigiert das wieder auf den großgeschriebenen RGBW-Wert.
Im Prinzip bleibt der Wert also gleich, ABER durch das erneute Setzen wird der eingestellte Wert neu gesetzt mit all seinen Folgen (das Licht geht bspw. an). So haut er mir irgendwie gerade gesetzt Lichtszenen kaputt, nur wenn ich die Ansicht für die Lichter öffne.

**To Reproduce**  
siehe oben

**Expected behavior**  
Wäre es möglich bei Light und ALTERNATIVE_COLORSPACE_VALUE auswählen zu können, dass der RGBW-Wert in Großbuchstaben gesetzt wird? (also statt "#ff00ff00" soll "#FF00FF00" gesetzt werden)
Von mir aus als Alternative Colorspace einfach "#rgbw" und "#RGBW" auswählbar machen.

**Screenshots & Logfiles**  
![grafik](https://user-images.githubusercontent.com/45281493/76491717-ac499c80-642e-11ea-8bc2-20816a232ecb.png)

**Versions:**  
 - Adapter version: 0.2.16
 - JS-Controller version: 2.2.9
 - Node version: v10.19.0
 - Operating system: debian

**Additional context**  
EDIT: Die Hoffnung ist natürlich, dass wenn iQontrol den Wert den er einliest "OK" findet, diesen gar nicht mehr aktualisiert. Ein reines Einlesen eines bezüglich Groß/Kleinschreibung falschen Wertes (also ohne Korrektur) könnte das Problem wahrscheinlich ebenfalls bereits beheben.

**Comment by sbormann** [comment]
Hi,
in der nächsten Version (kommt nachher) habe ich eine Abfrage eingebaut, ob der Wert in groß oder kleinbuchstaben vorliegt. Hat einen Nachteil: Wenn der Wert nur aus Zahlen besteht, kann er das natürlich nicht ermitteln. Aber vielleicht ist das Problem ja so trotzdem gelöst. Kannst Du es mal probieren und mir hier Rückmeldung geben?
Danke und VG!

**Comment by siggi85** [comment]
Habe das Update durchgeführt, leider stürzt der Web Adapter bei Aufruf ab. Fehlerbeschreibung habe ich im ioBroker Forum hinterlegt:
https://forum.iobroker.net/topic/26684/test-adapter-iqontrol-v0-2-x/302
