### ISSUE TITLE
Verhalten von ALTERNATIVE_COLORSPACE_VALUE in Kombination mit Farb-/Weißhelligkeit

### ISSUE THREAD

**Issue by siggi85** [sbormann/ioBroker.iqontrol#115]
**Describe the bug**  
Kann man das Zusammenspiel zwischen "WHITE BRIGHTNESS oder COLOR BRIGHTNESS" und "ALTERNATIVE_COLORSPACE_VALUE" ändern, sodass "ALTERNATIVE_COLORSPACE_VALUE" nur für das Setzen der Farbe genutzt wird?

**To Reproduce**  
siehe unten

**Expected behavior**  
Falls nur ALTERNATIVE_COLORSPACE_VALUE gesetzt ist --> Verhalten wie jetzt
Falls alle 3 Werte (ALTERNATIVE_COLORSPACE_VALUE, WHITE BRIGHTNESS und COLOR BRIGHTNESS) gefüllt sind --> beim Nutzen der bspw. Farbhelligkeit, nur den COLOR BRIGHTNESS Wert ändern und NICHT den RGBW-Wert hierfür nutzen
Ich habe bspw. mehrere RGBW Lampen gruppiert (Shelly RGBW2). Ich habe also einen virtuellen Datenpunkt für die Helligkeit und einen für die Farbe all dieser Lampen. Diese werden bei Änderungen auf die physichen Datenpunkte übertragen.
Falls ich nun jeder dieser Lampen eine eigene Farbe zugeordnet habe und dann über das Gruppenobjekt nur die Helligkeit ändern möchte, ändert iQontrol nun den RGBW Datenpunkt und überschreibt somit nicht nur die Helligkeit, sondern auch die Farbe, sodass alle Lampen danach die gleiche Farbe habe (die zuletzte eingestellte des Gruppendatenpunktes, halt nur mit angepasster Helligkeit). Das ist so natürlich nicht gewollt.

**Screenshots & Logfiles**  
siehe oben

**Versions:**  
 - Adapter version: 0.2.16
 - JS-Controller version: 2.2.9
 - Node version: v10.19.0
 - Operating system: debian

**Additional context**  
Ich hoffe ich konnte das Problem klar darstellen. Bei Bedarf kann ich gerne ein kurzes Video erstellen um das Problem etwas greifbarer zu machen.

**Comment by Sacred-Shadow** [comment]
Also mir wurde hier mal geschrieben, dass man zum Dimmen nicht die BRIGHTNESS nutzen soll sondern den LEVEL. Löst das evtl. schon dein Problem?

**Comment by siggi85** [comment]
Shelly RGBW2 in Kombination mit dem Shelly Adapter haben kein LEVEL, daher kann ich das leider nicht testen.
Ich glaube auch nicht, dass dies das Problem lösen würde. Der Unterschied ist ja nur, dass der eine Wert von 1-255 und der andere von 1-100 geht. Bei mir wird ja die Farbe überschrieben, wenn ich den Helligkeitswert ändere.
Die Empfehlung rührt sicher daher, dass die Helligkeit sonst halt nur bis 100 von 255 gehen, also bis knapp über 39% (LEVEL) gehen würde, falls man den BRIGHTNESS Wert nutzt, die Oberfläche aber den LEVEL Wert erwartet.

**Comment by Sacred-Shadow** [comment]
Nein .. nicht Level beim Objekt sondern Level als Datenpunkt im iQontrol.
![grafik](https://user-images.githubusercontent.com/61997661/79044992-e0b8a000-7c08-11ea-8dc0-af4f0c01e011.png)

**Comment by siggi85** [comment]
Achso! Habe ich gerade getestet, indem ich den gain Wert (also die Helligkeit für Farbe) in LEVEL genutzt habt. Leider gleiches Verhalten.
Wenn ich den Regler Farbe, Sättigung oder "Helligkeit Farbe" nutze, sehe ich in den Objekten, dass iQontrol anscheinend nur den RGBW Datenpunkt nutzt, die anderen Datenpunkte werden gar nicht geändert (ich ändere diese DP aktuell nur in eine Richtung, also wenn der GruppenDP sich ändert, werden die einzelnen Systeme geändert, wenn die einzelnen Systeme sich ändern, bleibt der Gruppendatenpunkt unverändert auf dem zuletzt konfigurierten Stand.

In der iQontrol README steht dazu:
> To avoid conversation-loops it is recommendet to either use the original colorspace-datapoints (HUE, SATURATION, COLOR_BRIGHTNESS, CT, WHITE_BRIGHTNESS) or the alternative colorspace-datapoint to replace these datapoints.

Ich denke hier hat man einfach den anderen DP ignoriert um dieses Loop-Problem zu beheben. Gruppenobjekte, bei denen nur ein Wert geändert werden soll (bspw. die Helligkeit einer ganzen Gruppe ändern, aber deren individuelle Farben behalten) ist dadurch leider nicht mehr möglich. :/

**Comment by sbormann** [comment]
Duplicate of #98 
Ich denke, das ist das Gleiche, wie bei Issue #98 - und damit hoffentlich gelöst, falls nicht, bitte noch mal Rückmeldung!
VG!

**Comment by siggi85** [comment]
Habe das Update durchgeführt, leider stürzt der Web Adapter bei Aufruf ab. Fehlerbeschreibung habe ich im ioBroker Forum hinterlegt:
https://forum.iobroker.net/topic/26684/test-adapter-iqontrol-v0-2-x/302
