### ISSUE TITLE
Rolladen nicht zu steuern

### ISSUE THREAD

**Issue by GuybrushThreepwood75** [sbormann/ioBroker.iqontrol#118]
Wenn ich 1 Rolladen einbinde funktioniert dieser klasse. 
Aber wenn ich den funktionierenden Rolladen kopiere und die Konfiguration abändere (0 und 100 ab zu invertiert) , kann ich keinen Rolladen mehr steuern und der Status der Rolladen wird nicht mehr angezeigt.
Hoffe ich finde hier Hilfe, weil iQontrol finde ich klasse!

**Comment by sbormann** [comment]
Hi, bitte poste mal etwas genauer, was passiert, einschließlich Logs aus der Entwicklerkonsole des Browsers während der Fehler auftritt:
iQontrol öffnen, F12 drücken, das "Console" Fenster öffnen und dann das posten, was da kommt, wenn der Fehler auftritt.
Danke

**Comment by sbormann** [comment]
Keine Rückmeldung mehr erhalten, deshalb geschlossen. Falls weiter Probleme bestehen, bitte wiedereröffnen.
