### ISSUE TITLE
Übersicht schaltet ausgeschaltete Lampen ein.

### ISSUE THREAD

**Issue by Sacred-Shadow** [sbormann/ioBroker.iqontrol#119]
**Describe the bug**  
Ich binde Lampen über Zigbee ein und verwende dann Alexa um die zu steuern.
Wenn Alexa eine Lampe mit Dimmer ausschaltet, wird der "state" auf "false" und die "brightness" auf "0" gesetzt.

Die Lampe ist so eingebunden:
![grafik](https://user-images.githubusercontent.com/61997661/78234841-05f63180-74d8-11ea-8434-80a5f0a7a24b.png)

Rufe ich eine Übersicht mit der Lampe auf, wird die Lampe eingeschaltet, ausgeschaltet, wieder eingeschaltet und bleibt dann an. Ist "brightness" nicht "0" und die Lampe nur über den "state" ausgeschaltet, tritt das Problem nicht auf. 

**Versions:**  
 - Adapter version: 0.2.16
 - JS-Controller version: 2.2.9
 - Node version: v10.19.0
 - Operating system: Raspbian

**Comment by sbormann** [comment]
Bitte brightness bei LEVEL und nicht bei COLOR_BRIGHTNESS eintragen. VG
