### ISSUE TITLE
Einfaches Anführungszeichen im Gerätenamen verhindert laden der Ansicht

### ISSUE THREAD

**Issue by gswdn** [sbormann/ioBroker.iqontrol#120]
Repro:

1. Ansicht für Geräte anlegen 
2. Gerätenamen mit einfachem Anführungszeichen vergeben, z.B. "Don't forget lunch". Siehe Screenshot
![2020-04-18 07_06_28-instances - ioBroker](https://user-images.githubusercontent.com/52855342/79628752-25ca5e00-8144-11ea-8132-0f5393e63f5a.png)
3. iQontrol Ansicht öffnen
-> Ansicht wird nicht geladen
-> Meldungen in der Debug-Console siehe Screenshot
![2020-04-18 07_01_48-iQontrol](https://user-images.githubusercontent.com/52855342/79628754-29f67b80-8144-11ea-8389-09e5c9e62d99.png)

Vermutung: Hochkomma im Gerätenamen verursacht das Problem.
Wird dieses aus dem Gerätenamen entfernt, wird die Ansicht geladen.

iQontrol-Version 0.3.1
Fehler trat mit der Version 0.2.20 nicht auf.

**Comment by sbormann** [comment]
Stimmt, wird in der nächsten Version (hoffentlich - weil komplex) behoben sein.
