### ISSUE TITLE
nach Update keinerlei Anzeige mehr

### ISSUE THREAD

**Issue by roadsterdriver** [sbormann/ioBroker.iqontrol#121]
nach dem Update auf die neue Version ist leider nichts mehr in der Webansicht zu sehen....

**Comment by sbormann** [comment]
Geht es mit 0.3.2? Falls nicht, benötige ich weitere Infos, z.B. Log aus der F12-Enwickler-Konsole etc., um die Probleme zu lösen. Danke und VG!
