### ISSUE TITLE
Web Adapter wird ab Version 0.3.2 gekillt, mit 0.3.1 läuft alles

### ISSUE THREAD

**Issue by ihavenonick** [sbormann/ioBroker.iqontrol#122]
host.Beelink | 2020-04-22 10:08:58.386 | error | instance system.adapter.web.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.Beelink | 2020-04-22 10:08:58.386 | error | Caught by controller[0]:     at processTicksAndRejections (internal/process/task_queues.js:79:11)
host.Beelink | 2020-04-22 10:08:58.386 | error | Caught by controller[0]:     at /opt/iobroker/node_modules/socket.io/lib/socket.js:528:12
host.Beelink | 2020-04-22 10:08:58.386 | error | Caught by controller[0]:     at Socket.EventEmitter.emit (domain.js:482:12)
host.Beelink | 2020-04-22 10:08:58.385 | error | Caught by controller[0]:     at Socket.emit (events.js:310:20)
host.Beelink | 2020-04-22 10:08:58.385 | error | Caught by controller[0]:     at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.socketio/lib/socket.js:921:30)
host.Beelink | 2020-04-22 10:08:58.385 | error | Caught by controller[0]:     at Adapter.getForeignStates  (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:6786:26)
host.Beelink | 2020-04-22 10:08:58.385 | error | Caught by controller[0]:     at Adapter._processStates  (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:6693:31)
host.Beelink | 2020-04-22 10:08:58.385 | error | Caught by controller[0]:     at Array.map (<anonymous>)
host.Beelink | 2020-04-22 10:08:58.385 | error | Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:6694:24
host.Beelink | 2020-04-22 10:08:58.384 | error | Caught by controller[0]: TypeError: Cannot read property 'startsWith' of null
web.0 | 2020-04-22 10:08:57.898 | info | (10297) Terminated (NO_ERROR): Without reason
web.0 | 2020-04-22 10:08:57.896 | info | (10297) terminating
web.0 | 2020-04-22 10:08:57.879 | info | (10297) terminated http server on port 8082
web.0 | 2020-04-22 10:08:57.877 | error | at processTicksAndRejections (internal/process/task_queues.js:79:11)
web.0 | 2020-04-22 10:08:57.877 | error | at /opt/iobroker/node_modules/socket.io/lib/socket.js:528:12
web.0 | 2020-04-22 10:08:57.877 | error | at Socket.EventEmitter.emit (domain.js:482:12)
web.0 | 2020-04-22 10:08:57.877 | error | at Socket.emit (events.js:310:20)
web.0 | 2020-04-22 10:08:57.877 | error | at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.socketio/lib/socket.js:921:30)
web.0 | 2020-04-22 10:08:57.877 | error | at Adapter.getForeignStates (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:6786:26)
web.0 | 2020-04-22 10:08:57.877 | error | at Adapter._processStates (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:6693:31)
web.0 | 2020-04-22 10:08:57.877 | error | at Array.map (<anonymous>)
web.0 | 2020-04-22 10:08:57.877 | error | at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:6694:24
web.0 | 2020-04-22 10:08:57.877 | error | (10297) TypeError: Cannot read property 'startsWith' of null
web.0 | 2020-04-22 10:08:57.876 | error | (10297) uncaught exception: Cannot read property 'startsWith' of null

Node12
JS 3.0.14
Browser: Firefox 75.0

**Comment by sbormann** [comment]
Geht das mit der aktuellen Version wieder?

**Comment by ihavenonick** [comment]
Ja läuft
