### ISSUE TITLE
Add Pressure display in Temperature-Sensor

### ISSUE THREAD

**Issue by vgeannin** [sbormann/ioBroker.iqontrol#123]
Hi Sebastian,

Can you add an option to display the Pressure value on the Temperature-Sensor ?
or Can you create a Pressure Sensor ?
I have several Xiaomi Temprature Sensor that can report Pressure 
![Capture d’écran 2020-04-22 à 15 52 12](https://user-images.githubusercontent.com/14293635/79990476-65c97200-84b1-11ea-8617-666f83bfd505.png)

Thanks,
Vincent

**Comment by sbormann** [comment]
Leider sind schon beide Info-Felder belegt. Du könntest Dir aber z.B. mit dem Additional Info-Feld weiterhelfen. Reicht das? VG!
