### ISSUE TITLE
Homematic HmIP-eTRV-B breaks views

### ISSUE THREAD

**Issue by stephan1827** [sbormann/ioBroker.iqontrol#126]
**Describe the bug**  
When you add thermostat HmIP-eTRV-B via auto detect the view that contains this device no longer loads. When you now go the view and try to open the view that contains the thermostat it no longer opens the view. The button just flashes but nothing happens. 

When I go back into the device and change any of the parameters and save it again it starts working again.

<img width="1106" alt="Bildschirmfoto 2020-04-29 um 21 25 18" src="https://user-images.githubusercontent.com/2972703/80639034-b9176380-8a61-11ea-93e2-5e8ae0b3e268.png">

**To Reproduce**  
1. Go to a view
2. Click on Create Device Automatically
3. Select device
4. Click on Create Preview
5. Save

**Expected behavior**  
When you now go the view and try to open the view that contains the thermostat it should load the new view.

**Screenshots & Logfiles**  
<img width="887" alt="Bildschirmfoto 2020-04-29 um 21 23 49" src="https://user-images.githubusercontent.com/2972703/80639040-bb79bd80-8a61-11ea-9b9b-9ff7e229703e.png">

**Versions:**  
 - Adapter version: 0.35
 - JS-Controller version: 3.0.19
 - Node version: HmIP-eTRV-B
 - Operating system: docker

**Comment by sbormann** [comment]
Hi, bitte mal den Fehler reproduzieren bei geöffneter Entwicklerkonsole (im Browser F12 drücken) und dann das posten, was unter "Console" angezeigt wird.

**Comment by stephan1827** [comment]
[Deprecation] Application Cache was previously restricted to secure origins only from M70 on but now secure origin use is deprecated and will be removed in M82.  Please shift your use case over to Service Workers.
DevTools failed to load SourceMap: Could not load content for http://192.168.86.90:8082/iqontrol/jquery/jquery.mobile-1.4.5.min.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://192.168.86.90:8082/lib/js/socket.io.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
jquery-migrate-3.0.0.min.js:2 JQMIGRATE: Migrate is installed, version 3.0.0
conn.js:264 2020-05-08T17:58:35.341Z Connected => authenticate
conn.js:273 2020-05-08T17:58:35.482Z Authenticated: true
index.js:662 Socket connected - getStarted
index.js:708 * Get started...
index.js:721 * Fetch system config...
index.js:723 * System config received.
index.js:727 * Fetch config...
index.js:776 * Creating options-object
index.js:729 * Config received.
index.js:730 * Handle options...
index.js:732 * Options handeled.
index.js:733 * Render toolbar...
index.js:735 * Toolbar rendered.
index.js:736 * Render actual|home view...
index.js:2743 renderView iqontrol.0.Views.Start
index.js:828 Fetch object: hm-rega.0.22568
index.js:828 Fetch object: hm-rega.0.3039
index.js:828 Fetch object: hm-rega.0.2688
index.js:828 Fetch object: hm-rega.0.950
index.js:828 Fetch object: hm-rega.0.1981
index.js:6105 resizeDevicesToFitScreen with zoom-factor 0.9877049180327869
index.js:741 * Home rendered.
index.js:835 Fetched Object: hm-rega.0.22568
index.js:835 Fetched Object: hm-rega.0.3039
translate.js:24 "Aus": {"en": "Aus", "de": "Aus", "ru": "Aus", "pt": "Aus", "nl": "Aus", "fr": "Aus"},
index.js:835 Fetched Object: hm-rega.0.2688
translate.js:24 "Auto": {"en": "Auto", "de": "Auto", "ru": "Auto", "pt": "Auto", "nl": "Auto", "fr": "Auto"},
index.js:835 Fetched Object: hm-rega.0.950
translate.js:24 "offen": {"en": "offen", "de": "offen", "ru": "offen", "pt": "offen", "nl": "offen", "fr": "offen"},
index.js:835 Fetched Object: hm-rega.0.1981
translate.js:24 "offen": {"en": "offen", "de": "offen", "ru": "offen", "pt": "offen", "nl": "offen", "fr": "offen"},
translate.js:24 "Aus": {"en": "Aus", "de": "Aus", "ru": "Aus", "pt": "Aus", "nl": "Aus", "fr": "Aus"},
translate.js:24 "Auto": {"en": "Auto", "de": "Auto", "ru": "Auto", "pt": "Auto", "nl": "Auto", "fr": "Auto"},
2translate.js:24 "offen": {"en": "offen", "de": "offen", "ru": "offen", "pt": "offen", "nl": "offen", "fr": "offen"},
index.js:4196 Starting marquee observer
index.js:2602 PRESSURE start
index.js:2623 	PRESSURE change 0.02|0
index.js:2623 	PRESSURE change 0.04|0.02
index.js:2623 	PRESSURE change 0.06|0.04
index.js:2623 	PRESSURE change 0.08|0.06
index.js:2623 	PRESSURE change 0.1|0.08
index.js:2623 	PRESSURE change 0.12000000000000001|0.1
index.js:2623 	PRESSURE change 0.14|0.12000000000000001
index.js:2623 	PRESSURE change 0.16|0.14
index.js:2623 	PRESSURE change 0.18|0.16
index.js:2623 	PRESSURE change 0.19999999999999998|0.18
index.js:2623 	PRESSURE change 0.21999999999999997|0.19999999999999998
index.js:2623 	PRESSURE change 0.23999999999999996|0.21999999999999997
index.js:2623 	PRESSURE change 0.25999999999999995|0.23999999999999996
index.js:2623 	PRESSURE change 0.27999999999999997|0.25999999999999995
index.js:2623 	PRESSURE change 0.3|0.27999999999999997
index.js:2673 PRESSURE end via TOUCHEND/MOUSEUP
index.js:2743 renderView iqontrol.0.Views.Räume
index.js:6105 resizeDevicesToFitScreen with zoom-factor 0.9877049180327869
index.js:2682 Find active Toolbar Index
index.js:2623 	PRESSURE change 0.09999999999999998|0.3
index.js:2625 	PRESSURE change ignore
index.js:4196 Starting marquee observer
index.js:4254 PRESSURE start
index.js:4275 	PRESSURE change 0.02|0
index.js:4275 	PRESSURE change 0.04|0.02
index.js:4275 	PRESSURE change 0.06|0.04
index.js:4275 	PRESSURE change 0.08|0.06
index.js:4275 	PRESSURE change 0.1|0.08
index.js:4275 	PRESSURE change 0.12000000000000001|0.1
index.js:4275 	PRESSURE change 0.14|0.12000000000000001
index.js:4275 	PRESSURE change 0.16|0.14
index.js:4275 	PRESSURE change 0.18|0.16
index.js:4275 	PRESSURE change 0.19999999999999998|0.18
index.js:4275 	PRESSURE change 0.21999999999999997|0.19999999999999998
index.js:4275 	PRESSURE change 0.23999999999999996|0.21999999999999997
index.js:4275 	PRESSURE change 0.25999999999999995|0.23999999999999996
index.js:4275 	PRESSURE change 0.27999999999999997|0.25999999999999995
index.js:4325 PRESSURE end via TOUCHEND/MOUSEUP
index.js:4237 CLICK
index.js:2743 renderView Schlafzimmer
index.js:828 Fetch object: hm-rpc.1.00201A49A02B30.1.SET_POINT_TEMPERATURE
index.js:828 Fetch object: hm-rpc.1.00201A49A02B30.1.ACTUAL_TEMPERATURE
index.js:828 Fetch object: hm-rpc.1.00201A49A02B30.1.CONTROL_MODE
index.js:828 Fetch object: hm-rpc.1.00201A49A02B30.1.BOOST_MODE
index.js:828 Fetch object: hm-rpc.1.00201A49A02B30.1.PARTY_MODE
index.js:828 Fetch object: hm-rpc.1.00201A49A02B30.0.LOW_BAT
index.js:828 Fetch object: hm-rpc.1.00201A49A02B30.0.UNREACH
index.js:828 Fetch object: hm-rpc.1.00201A49A02B30.0.UPDATE_PENDING_ALARM
index.js:828 Fetch object: hm-rpc.0.NEQ0943267.1.STATE
index.js:828 Fetch object: hm-rpc.0.NEQ0943267.1.LOWBAT
index.js:828 Fetch object: hm-rpc.0.NEQ0943267.0.UNREACH
index.js:828 Fetch object: hm-rpc.0.NEQ0943267.1.ERROR
index.js:828 Fetch object: hm-rpc.1.001158A991387B.4.LEVEL
index.js:828 Fetch object: hm-rpc.1.001158A991387B.4.STOP
index.js:828 Fetch object: hm-rpc.1.001158A991387B.0.UNREACH
index.js:824 Already waiting for object: hm-rpc.1.00201A49A02B30.1.ACTUAL_TEMPERATURE
index.js:824 Already waiting for object: hm-rpc.1.00201A49A02B30.1.CONTROL_MODE
index.js:824 Already waiting for object: hm-rpc.1.00201A49A02B30.0.UNREACH
index.js:3547 Uncaught TypeError: Cannot read property 'push' of undefined
    at index.js:3547
    at index.js:3551
    at fetchView (index.js:794)
    at renderView (index.js:2758)
    at eval (eval at <anonymous> (index.js:4242), <anonymous>:3:63)
    at HTMLDivElement.<anonymous> (index.js:4242)
    at HTMLDivElement.dispatch (jquery-1.11.3.min.js:4)
    at HTMLDivElement.r.handle (jquery-1.11.3.min.js:4)
(anonymous) @ index.js:3547
(anonymous) @ index.js:3551
fetchView @ index.js:794
renderView @ index.js:2758
eval @ VM178:3
(anonymous) @ index.js:4242
dispatch @ jquery-1.11.3.min.js:4
r.handle @ jquery-1.11.3.min.js:4
index.js:835 Fetched Object: hm-rpc.1.00201A49A02B30.1.SET_POINT_TEMPERATURE
index.js:4275 	PRESSURE change 0.07999999999999996|0.27999999999999997
index.js:4277 	PRESSURE change ignore
index.js:835 Fetched Object: hm-rpc.1.00201A49A02B30.1.ACTUAL_TEMPERATURE
index.js:835 Fetched Object: hm-rpc.1.00201A49A02B30.1.CONTROL_MODE
index.js:835 Fetched Object: hm-rpc.1.00201A49A02B30.1.BOOST_MODE
index.js:835 Fetched Object: hm-rpc.1.00201A49A02B30.1.PARTY_MODE
index.js:835 Fetched Object: hm-rpc.1.00201A49A02B30.0.LOW_BAT
index.js:835 Fetched Object: hm-rpc.1.00201A49A02B30.0.UNREACH
index.js:835 Fetched Object: hm-rpc.1.00201A49A02B30.0.UPDATE_PENDING_ALARM
translate.js:24 "NO ALARM": {"en": "NO ALARM", "de": "NO ALARM", "ru": "NO ALARM", "pt": "NO ALARM", "nl": "NO ALARM", "fr": "NO ALARM"},
index.js:835 Fetched Object: hm-rpc.0.NEQ0943267.1.STATE
index.js:835 Fetched Object: hm-rpc.0.NEQ0943267.1.LOWBAT
index.js:835 Fetched Object: hm-rpc.0.NEQ0943267.0.UNREACH
index.js:835 Fetched Object: hm-rpc.0.NEQ0943267.1.ERROR
index.js:835 Fetched Object: hm-rpc.1.001158A991387B.4.LEVEL
index.js:835 Fetched Object: hm-rpc.1.001158A991387B.4.STOP
index.js:835 Fetched Object: hm-rpc.1.001158A991387B.0.UNREACH

**Comment by sbormann** [comment]
Hi,
kannst Du mal bitte auf die index.js:3547 klicken aus dieser Fehlermeldung und mit im Screenshot zeigen, wo genau der Fehler ist? In der Regel bekommt man eine Erklärung, wenn man mit der Maus über den rot unterstrichenen Fehler zeigt.

index.js:3547 Uncaught TypeError: Cannot read property 'push' of undefined
at index.js:3547

Danke!

**Comment by stephan1827** [comment]
<img width="555" alt="Bildschirmfoto 2020-05-14 um 07 10 54" src="https://user-images.githubusercontent.com/2972703/81895257-1f4bcc80-95b2-11ea-8fff-01500164fe78.png">
Hier ist der Screenshot

**Comment by sbormann** [comment]
Sorry, bitte klick mal auf das blau unterstrichene, ich muss die Zeile sehen.

--
Von meinem iPhone aus gesendet

Am 14.05.2020 um 07:12 schrieb Stephan Stricker <notifications@github.com>:

﻿

[Bildschirmfoto 2020-05-14 um 07 10 54]<https://user-images.githubusercontent.com/2972703/81895257-1f4bcc80-95b2-11ea-8fff-01500164fe78.png>

Hier ist der Screenshot

**Comment by stephan1827** [comment]
<img width="1104" alt="Bildschirmfoto 2020-05-14 um 18 38 00" src="https://user-images.githubusercontent.com/2972703/81961023-15f24c80-9612-11ea-92f6-91a6a8e5fdde.png">
So?

**Comment by sbormann** [comment]
Ja perfekt, wird in der nächsten Version gefixed.

Von: Stephan Stricker <notifications@github.com>
Gesendet: Donnerstag, 14. Mai 2020 18:39
An: sbormann/ioBroker.iqontrol <ioBroker.iqontrol@noreply.github.com>
Cc: Sebastian Bormann <sebastian@bormann.net>; Comment <comment@noreply.github.com>
Betreff: Re: [sbormann/ioBroker.iqontrol] Homematic HmIP-eTRV-B breaks views (#126)


[Bildschirmfoto 2020-05-14 um 18 38 00]<https://user-images.githubusercontent.com/2972703/81961023-15f24c80-9612-11ea-92f6-91a6a8e5fdde.png>
So?
