### ISSUE TITLE
Mal die Stable Version nachziehen

### ISSUE THREAD

**Issue by Sacred-Shadow** [sbormann/ioBroker.iqontrol#128]
Hey,

aktuell ist die 0.2.16 als stable gekennzeichnet. 
Die hängt nun 12 Versionen (o. 4 Monate) Entwicklungszeit hinterher.

Wird Zeit die langsam mal nachzuziehen oder? :)

**Comment by sbormann** [comment]
Ja, ist in Planung. Warte noch auf ein paar Rückmeldungen zu Bugfixes, wenn alles mir bekannte gefixed ist wird dann zügig umgestellt.
