### ISSUE TITLE
Does not work thru iobroker.pro

### ISSUE THREAD

**Issue by algar42** [sbormann/ioBroker.iqontrol#129]
**Describe the bug**  
Starting version 0.4.0 of adapter it does not connect anymore via iobroker.pro cloud. In Chrome console I get "SocketURL not defined" error message. 

**Versions:**  
 - Adapter version: 0.4.1
 - JS-Controller version: 3.0.14
 - Node version: 10

**Comment by sbormann** [comment]
Hi, gehts hier um das Frontend oder die Konfigurations-Seite?

**Comment by algar42** [comment]
it is about frontend

**Comment by sbormann** [comment]
Please provide log entrys from console (f12 in the browser).

**Comment by algar42** [comment]
it now works with latest version after I cleared browser cache. :)
thanks!
