### ISSUE TITLE
Wrong month in timestamp

### ISSUE THREAD

**Issue by MarvinMH** [sbormann/ioBroker.iqontrol#131]
**Describe the bug**  
Timestamp of last change shows the wrong month.

**To Reproduce**  
In IQontrol config section, create a device "Schalter", set timestamp to "Status + Zeitstempel + Abgelaufene Zeit (seit). Change the underlying object and see the timestemp gets updated. Wait a few days without changing the object's value. Wait until the widget shows the date and not the time.

**Expected behavior**  
Last change of the object was 1590969600036, which is "01.06.2020". Timestamp on the widget should represent that time. However, the widget shows "01.05.2020 - seit 2 Tagen" (today: 03.06.2020). The month is wrong.

**Versions:**  
 - Adapter version: 0.4.1
 - JS-Controller version: 3.1.4
 - Node version: v10.20.1
 - Operating system: Raspberry Pi OS

**Comment by sbormann** [comment]
You are right. Will be fixed in next version.
