### ISSUE TITLE
The load circle never is replaced with content

### ISSUE THREAD

**Issue by kaefert** [sbormann/ioBroker.iqontrol#133]
**Describe the bug**  
The load circle never is replaced with content

**To Reproduce**  
1. Install iqontrol adapter and add instance (tried both the version 1.0.0 that you get by default and the version 1.1.2 by installing from github)
2. Click on the link .../iqontrol/index.html
3. See error

**Expected behavior**  
Show the sample views & devices I can see in the adapter configuration after creating the instance

**Screenshots & Logfiles**  
![IO-Broker_iqontrol_doesnt_open](https://user-images.githubusercontent.com/1448723/85376424-fa932f00-b537-11ea-8af7-0c62386edb88.png)

**Versions:**  
 - Adapter version: Tested both 1.0.0 and 1.1.2, both show the same issue for me
 - JS-Controller version: 3.1.4
 - Node version: v10.19.0
 - Operating system: Debian 10 (buster)

**Additional context**  
I am unexperienced with the visualisation of data out of IO-Broker. I first tried "Material UI" but ran into a dead-end here: https://forum.iobroker.net/topic/34625/material-ui-click-aktion-url
Now I wanted to try iqontrol, but failed even sooner than with "Material UI". :(

**JS-Stack-Trace**
```
TypeError: config[namespace] is undefined
index.js:2498:6
    renderToolbar http://io-broker-ip:8082/iqontrol/index.js:2498
    getStarted http://io-broker-ip:8082/iqontrol/index.js:683
    fetchConfig http://io-broker-ip:8082/iqontrol/index.js:734
    onack http://io-broker-ip:8082/lib/js/socket.io.js:8
    onpacket http://io-broker-ip:8082/lib/js/socket.io.js:8
    exports http://io-broker-ip:8082/lib/js/socket.io.js:8
    emit http://io-broker-ip:8082/lib/js/socket.io.js:6
    ondecoded http://io-broker-ip:8082/lib/js/socket.io.js:6
    exports http://io-broker-ip:8082/lib/js/socket.io.js:8
    emit http://io-broker-ip:8082/lib/js/socket.io.js:6
    add http://io-broker-ip:8082/lib/js/socket.io.js:6
    ondata http://io-broker-ip:8082/lib/js/socket.io.js:6
    exports http://io-broker-ip:8082/lib/js/socket.io.js:8
    emit http://io-broker-ip:8082/lib/js/socket.io.js:6
    onPacket http://io-broker-ip:8082/lib/js/socket.io.js:7
    setTransport http://io-broker-ip:8082/lib/js/socket.io.js:7
    emit http://io-broker-ip:8082/lib/js/socket.io.js:6
    onPacket http://io-broker-ip:8082/lib/js/socket.io.js:7
    onData http://io-broker-ip:8082/lib/js/socket.io.js:7
    onmessage http://io-broker-ip:8082/lib/js/socket.io.js:8
```

**Comment by sbormann** [comment]
Hi, please try the actual version from github, i tried to fix the faulty line.
But i think there is a problem in your configuration - have you defined a toolbar and a home view?

**Comment by Revengendary** [comment]
I just installed the new version from Github. But now I can't open the tiles anymore. :( 
![image](https://user-images.githubusercontent.com/66947847/85562580-e715c000-b62c-11ea-879e-b56f4910f95d.png)

**Comment by kaefert** [comment]
> have you defined a toolbar and a home view?
I haven't done any config myself yet, but it looked like it auto created a sample config. is this one not functional?

**Comment by sbormann** [comment]
> I just installed the new version from Github. But now I can't open the tiles anymore. :(
> ![image](https://user-images.githubusercontent.com/66947847/85562580-e715c000-b62c-11ea-879e-b56f4910f95d.png)
> 
> Downgrade to version 1.1.1 brought the tiles back...

Whoops, bad and silly from me: i added this "demo"-error to make screenshots of how to provide a proper error-log - and uploaded this to github :)

Fixed version without "demo-error" is online :)

**Comment by sbormann** [comment]
> > have you defined a toolbar and a home view?
> 
> I haven't done any config myself yet, but it looked like it auto created a sample config. is this one not functional?
> 
> > please try the actual version from github
> 
> Isn't the verison 1.1.2 that I get by clicking the "install from custom URL" button and then select iqontrol on the drop-down on the first tab titled "install from github" the "actual version from github"?
> If not, how do I get that?

Hi, you are right in both points. 

The github-version doesn't get a new version-number, so you cannot differentiate between version 1.1.2 from npm (latest) and the even newer developing-version from github by the version number. But if you have installed via the cat-icon, this is the actual development-version from github.

And you are also right, that a demo-config is provided - but maybe here went something wrong. So please try to configure just a view, and a valid toolbar-entry and try again.

Good luck!
