### ISSUE TITLE
blurred page after minimize homescreen app on iphone/ipad

### ISSUE THREAD

**Issue by gravidigit** [sbormann/ioBroker.iqontrol#134]
Have you seen this before?

![IMG_0001](https://user-images.githubusercontent.com/8973517/86241009-79284600-bba2-11ea-953e-ec51b3e17e40.PNG)

Thanks!

**Comment by sbormann** [comment]
Please activate this option: Always use time instead of pressure.
https://forum.iobroker.net/assets/uploads/files/1592851834951-2594a2f8-3f84-4560-8ebd-2daecd33dbd3-image.png
