### ISSUE TITLE
Navigation is almost impossible when accessing from phone

### ISSUE THREAD

**Issue by algar42** [sbormann/ioBroker.iqontrol#136]
**Describe the bug**  
Navigation is almost impossible when accessing from phone. Buttons\tiles in GUI are not responsive. 
See the video with the problem here: [iqontrol.mp4](https://photos.app.goo.gl/kSXp6sjNxwhA6xWZ7)
it looks like it recognizes all clicks as long-press or something like that.. 

**To Reproduce**  
1. Access to the created web-interface from Android phone
2. Try to navigate between pages.

**Versions:**  
 - Adapter version: 1.1.5
 - JS-Controller version: 3.16
 - Node version: 10.16.3

**Comment by sbormann** [comment]
Please use option "Always use time instead of pressure" under options.
In next version this option will be set as standard.
