### ISSUE TITLE
IPv6 only is not working

### ISSUE THREAD

**Issue by MartinDEU** [sbormann/ioBroker.iqontrol#138]
Running in an IPv6 only environment, only the basic environment is loading. But the buttons and status is not shown. 

**To Reproduce**  
1. Setup ioBroker incl. iQontrol on a IPv6 enabled Raspi
2. Start Browser (firefox, chromium) on IPv6 enabled client
3. Load iQontrol page on browser, i.e. http://[_IPv6-Address_]:8082/iqontrol/index.html. Browser starts loading, but only shows empty page with headline "iQontrol", "(reload)" button and circle in the middle of the page.

**Expected behavior**  
same behaviour as on a IPv4 connection (test on same server and client with http://_IPv4-Address_:8082/iqontrol/index.html works without any issue). The ioBroker admin page on port 8081 works without any issue on v6 and v4.

**Screenshots & Logfiles**  
Browser console shows error 
`[Socket] connect error: Error: xhr poll` 
`<anonym> http://[<ipv6 addr>]:8082/iqontrol/index.js:7994`
`emit http://[<ipv6 addr>]:8082/lib/js/socket.io.js:6`
`emit http://[<ipv6 addr>]:8082/lib/js/socket.io.js:8`
`emitAll http://[<ipv6 addr>]:8082/lib/js/socket.io.js:6`
`s http://[<ipv6 addr>]:8082/lib/js/socket.io.js:6`
`emit http://[<ipv6 addr>]:8082/lib/js/socket.io.js:6`
`onError http://[<ipv6 addr>]:8082/lib/js/socket.io.js:7`
`setTransport http://[<ipv6 addr>]:8082/lib/js/socket.io.js:7`
`emit http://[<ipv6 addr>]:8082/lib/js/socket.io.js:6`
`onError http://[<ipv6 addr>]:8082/lib/js/socket.io.js:7`
`doPoll http://[<ipv6 addr>]:8082/lib/js/socket.io.js:7`
`emit http://[<ipv6 addr>]:8082/lib/js/socket.io.js:6`
`onError http://[<ipv6 addr>]:8082/lib/js/socket.io.js:7`
`create http://[<ipv6 addr>]:8082/lib/js/socket.io.js:7`
as well as 
`[Socket] getIsConnected index.js`
`Page visible-event - socket is disconnected`

**Versions:**  
 - Adapter version: 1.1.5
 - JS-Controller version: 3.1.4
 - Node version: 12.18.0
 - Operating system: raspbian
uname -a: Linux ioBroker 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux

**Comment by sbormann** [comment]
Hi,
DEU im Namen - sprichst Du deutsch?
Habe mit ip v6 praktisch noch keine Erfahrungen. Gehen denn andere Adapter, die socket.io brauchen? Probier mal bitte FLOT und VIS aus, falls möglich.
VG!

**Comment by MartinDEU** [comment]
Hi, 
ja, spreche Deutsch :-) 
Von VIS funktioniert sowohl der Editor, als auch die damit erzeugte Oberfläche. FLOT scheint auch zu funktionieren, zumindest läd es. 
VG.

**Comment by sbormann** [comment]
@GermanBluefox  oder @Apollon77 : Kann einer von Euch mit dem Fehler was anfangen? 
Mit ipv6 scheint der socket nicht zu connecten:
````
[Socket] connect error: Error: xhr poll
<anonym> http://[<ipv6 addr>]:8082/iqontrol/index.js:7994
emit http://[<ipv6 addr>]:8082/lib/js/socket.io.js:6
emit http://[<ipv6 addr>]:8082/lib/js/socket.io.js:8
emitAll http://[<ipv6 addr>]:8082/lib/js/socket.io.js:6
s http://[<ipv6 addr>]:8082/lib/js/socket.io.js:6
emit http://[<ipv6 addr>]:8082/lib/js/socket.io.js:6
onError http://[<ipv6 addr>]:8082/lib/js/socket.io.js:7
setTransport http://[<ipv6 addr>]:8082/lib/js/socket.io.js:7
emit http://[<ipv6 addr>]:8082/lib/js/socket.io.js:6
onError http://[<ipv6 addr>]:8082/lib/js/socket.io.js:7
doPoll http://[<ipv6 addr>]:8082/lib/js/socket.io.js:7
emit http://[<ipv6 addr>]:8082/lib/js/socket.io.js:6
onError http://[<ipv6 addr>]:8082/lib/js/socket.io.js:7
create http://[<ipv6 addr>]:8082/lib/js/socket.io.js:7
as well as
[Socket] getIsConnected index.js
Page visible-event - socket is disconnected
````

**Comment by GermanBluefox** [comment]
Ich nicht...

**Comment by Apollon77** [comment]
I expect that it an not work because we listen to an IPv4 by default or ?!

see also https://stackoverflow.com/questions/14185370/socket-io-ipv6-january-2013-edition

This would mean to really think about that in many places

**Comment by Apollon77** [comment]
PS: A try could be in the web adapter (or the config from socketio) to define the "bind" param with "::1" instead of 0.0.0.0

**Comment by MartinDEU** [comment]
Not quiet sure if this helps:
- connection to [ipv6 addr]:8082 is working well
- connection to [ipv6 addr]:8081 (admin interface) is also working well

**Comment by Apollon77** [comment]
Did you tried to configure as proposed?

**Comment by MartinDEU** [comment]
I changed the web adapter config to "::1" (which would be the loopback adress!?!) which does not change the behavior. I also tried "::" (which is the equivalent to 0.0.0.0) but also no positive effect. 

I have no idea how to modify settings of socket.io - any hints?

**Comment by sbormann** [comment]
It seems, this issue ist not directly related to iQontrol, isn't it? Therefore i would like to close it here. Is that ok?
