### ISSUE TITLE
Erweiterung Alarm Template um Hüllenschutz

### ISSUE THREAD

**Issue by Melwindp** [sbormann/ioBroker.iqontrol#141]
Idee: Viele Alarmanlagen nutzen insgesamt 3 Status:
- Vollschutz 
- Hüllenschutz
- Aus

Derzeit kann man im Template nur An und Aus konfigurieren. Toll wäre eine Erweiterung um einen zweiten aktiven Zustand "Hüllenschutz"

Viele Grüsse 

Melwin

**Comment by sbormann** [comment]
Hi, 
man kann beliebig viele Zustände definieren mit einer ValueList.
Bei mir gibt es z.B. 
Alarmanlage unscharf, Intern scharf, Extern scharf:
![image](https://user-images.githubusercontent.com/49171332/93498528-33ae2600-f912-11ea-9d62-15ddf945a5c0.png)

**Comment by sbormann** [comment]
Lies mal das Kapitel über value list und target value list. Bei Fragen kannst Du Dich gerne ans Forum wenden. VG
