### ISSUE TITLE
Keine Hintergrundbilder

### ISSUE THREAD

**Issue by nob0dy80** [sbormann/ioBroker.iqontrol#143]
Hallo,

erst dachte ich meine iobroker installation wäre kaputt gefummelt, aber nachdem ich extra für diesen adapter einen zweiten iobroker frisch aufgesetzt habe (linux), ist das Problem das gleiche.

Egal was ich versuche, es wird kein Hintergrundbild eingebunden. Nach einer komplett frischen Installation werden auf den Seiten nicht mal die Demo-Bilder dargestellt die standardmässig hinterlegt sind.

Wenn ich es richtig verstehe, sollte per Standard das Bild .\userimages\demo\bakestone.jpg auf der "Startseite" angezeigt werden.
![image](https://user-images.githubusercontent.com/28686079/94290082-025cd800-ff5a-11ea-9751-8d52fde3308a.png)

Diese sind auch da
![image](https://user-images.githubusercontent.com/28686079/94290435-75664e80-ff5a-11ea-941d-86c3a9ebf553.png)

Beim Aufruf der Seite, sieht es aber so aus:
![image](https://user-images.githubusercontent.com/28686079/94290239-3637fd80-ff5a-11ea-8c1f-5d0a82324cf5.png)

Da frisch installiert, brauch ich vermutlich keine Versionen benennen außer NodeJs 12 in der letzten Version.

**Comment by sbormann** [comment]
Eigentlich sollten die Bilder beim ersten Start automatisch nach iqontrol.meta verschoben werden. Gibt es dieses Verzeichnis bei Dir? Kannst Du eigene Bilder hochladen und nutzen?

**Comment by sbormann** [comment]
Bitte schick mal ein komplettes Log aus der F12 Konsole, während Du die Admin-Seite von iQontrol öffnest.

**Comment by nob0dy80** [comment]
@sbormann
Ich kann Bilder hochladen, aber diese ebenfalls nicht benutzen.
Der Meta Ordner ist vorhanden, beinhaltet aber nur das Bild was ich selber hochgeladen habe.
![image](https://user-images.githubusercontent.com/28686079/94361910-f850eb80-00b7-11eb-80ea-1e524daf4039.png)


Anbei noch das Console log:
![image](https://user-images.githubusercontent.com/28686079/94361928-0bfc5200-00b8-11eb-99ef-dc31234baca2.png)

**Comment by nob0dy80** [comment]
Hier noch der Versuch mit einem eigenen Bild:

![image](https://user-images.githubusercontent.com/28686079/94362171-b9bc3080-00b9-11eb-99e4-e8ca9259c986.png)

![image](https://user-images.githubusercontent.com/28686079/94362184-d6f0ff00-00b9-11eb-8ebd-3779ee14b671.png)


![image](https://user-images.githubusercontent.com/28686079/94362197-ea9c6580-00b9-11eb-8abe-0859bbdde490.png)

**Comment by nob0dy80** [comment]
Hab jetzt noch mal einen frischen Iobroker aufgesetzt um der Gefahr zu entgehen, dass ich was falsch gemacht habe.

Ich habe die Bilder gefunden, allerdings nicht im Meta Ordner.

![image](https://user-images.githubusercontent.com/28686079/94363097-289c8800-00c0-11eb-88b1-149ab38136c1.png)

Soll das so sein? Habe die Ordner iqontrol.admin, iqontrol  und  iqontrol.meta.
Meta wird beim ersten Start angelegt, bleibt aber bis auf die json Datei leer. 
Bin ein wenig irritiert darüber wie er die einen Bilder im Meta Ordner suchen soll aber die Demo Bilder im iqontrol Ordner?

**Comment by sbormann** [comment]
Hi, das ist seltsam. Eigentlich sollten beim ersten Start, wenn der meta-Ordner angelegt wird, auch die demo-Bilder rüber kopiert werden. Da scheint es zu haken - warum auch immer.
Das Log, das Du geschickt hast, ist vom Frontend, richtig? Ich bräuchte genau so eins, während Du die Admin-Seite von iQontrol öffnest. Vielleicht findet sich da eine Fehlermeldung?

**Comment by nob0dy80** [comment]
@sbormann 
Mein Standard-Iobroker hat im Moment: iqontrol 1.2.5, admin 4.0.10, und js-controller 3.1.4 (Debian Linux)
Mein Test-Iobroker den ich nur für iqontrol zum testen installiert habe hat: iqontrol 1.2.4, admin 4.0.10 und js-controller 3.1.6 (alles latest stable) (RaspiOS basierend auf Debian)
Beide Systeme verhalten sich gleich.


Console-Ausgabe beim öffnen der Admin-Seite:

![image](https://user-images.githubusercontent.com/28686079/94368536-c4d88600-00e4-11eb-81e9-4588c81b658e.png)

Verdächtiges kann ich da nicht sehen.

**Comment by nob0dy80** [comment]
Nehme an, du bist deinem Latein auch am Ende? :-) Hab das Spiel jetzt noch 2 mal erneut gemacht. Einmal mit Ubuntu, einmal mit Arch Linux. Immer das gleiche Ergebnis. Das Problem scheint, in meinen Augen zumindest, erstmal am Adapter zu liegen oder an einem er späteren Versionupdates.

Kann es sein, dass du das ganze Ding unter Windows entwickelt hast? Alleine die Pfadangaben mit "/" und "\" verwirren mich.

**Comment by jonnycastaway** [comment]
Ich hänge mich dran, slebiges Problem hier.
Raspbian Buster mit frischem ioBroker und iQontrol.
Es sind keine Hintergrundbilder vorhanden.
Allerdings funktionieren bei mir die selbst Hochgeladenen problemlos.

**Comment by nob0dy80** [comment]
Hab auch noch mal gespielt. Es lässt sich tatsächlich ein eigenes Hintergrundbild einbinden wenn man den Pfad wie folgt gestaltet:
.\..\iqontrol.meta\userimages\black.jpg

Lustigerweise (oder auch nicht) nimmt er ein zweites Bild (.\..\iqontrol.meta\userimages\blau.jpg) welches ich auch hochgeladen habe und für die "Rooms" seite hinterlegt habe, nicht an.
Auch hier bleibt das Hintergrundbild black.jpg.

Fehler bleibt in 1.3.1 weiterhin.

**Comment by sbormann** [comment]
Hi, genau, der Link mit ``.\..\iqontrol.meta\userimages....`` ist richtig. 
Also funktioniert zumindest der upload von Bildern in den iqontrol.meta-Ordner schon mal. 
Wenn Du jetzt aber ein Bild, z.B. black.jpg, via Drop-Down-Menü auswählst, nimmt er den falschen Pfad? Bitte schick mal ein Screenshot, welchen Pfad er nimmt, wenn Du black.jpg im Drop-Down auswählst.

**Comment by nob0dy80** [comment]
@sbormann 
Via Dropdown dreht er nur die slashes um:
![image](https://user-images.githubusercontent.com/28686079/96574565-e980e180-12cf-11eb-98c4-7cf6b582692b.png)
Funktioniert aber dann genauso.
Es geht hier also nur noch um die Demo Bilder die nicht funktionieren. Diese sind auch nicht via Dropdown auswählbar.

Naja kopier ich sie halt runter und lade sie als userimages wieder hoch :-)

**Comment by sbormann** [comment]
Hi,
das mit den umgedrehten Slashes ist richtig (es war notwendig, dies so zu implementieren, da die intern die Backslashes beim Befüllen des Drop-Down-Menüs die einzelnen Einträge trennt und deshalb nicht verwendet werden dürfen).

Bzgl. des ursprünglichen Problems vermute ich mal, dass es bei der ersten Installation irgendwie das Verschieben der Demo-Bilder verhauen hat. 

Würde das Issue dann damit schließen.
VG!

**Comment by nob0dy80** [comment]
Wenn du wirklich der Meinung bist, dass man Probleme schließen sollte die weiterhin vorhanden sind, dann bitte...
Ich vermute mal jeder Softwareentwickler würde jetzt die Hände über den Kopf zusammenschlagen, aber man kann dich nicht zwingen das Problem zu behandeln.

**Comment by sbormann** [comment]
Also
a) gefällt mit der Tonfall nicht. Ich denke, über mangelndes Engagement für ein nicht kommerzielles Produkt kann hier keiner ernsthaft klagen. Auch Deine Logfiles habe ich meiner Freizeit angeschaut, ausgewertet und kommentiert.
b) Habe ich es so aufgefasst, dass das Problem gelöst ist. Zitat von Dir: "Es geht hier also nur noch um die Demo Bilder die nicht funktionieren. ... Naja kopier ich sie halt runter und lade sie als userimages wieder hoch" - Ergo läuft alles, bis auf die 5 Demo-Bilder, die bei der Erstinstallation wohl irgendwie verschüttet gingen. Den Workaround hast Du selbst gefunden und gepostet. Warum die Demo-Bilder fehlen, ließ sich aus den Logfiles nicht ersehen. Ich sehe somit auch keine Chance, das zu klären, es sei denn, ich hätte hier ein System, auf dem ich den Fehler reproduzieren könnte - was mir leider nicht zur Verfügung steht. 
c) würde ich dann gerne wieder zum gewohnt freundlichen Umgang zurückkehren. Hast Du also noch etwas zur Klärung des Fehlers beizusteuern, gerne her damit. Geschlossen heißt ja auch nicht, dass man nichts mehr posten oder den Thread wiedereröffnen kann, wenn es neue Infos gibt.
