### ISSUE TITLE
Loading rooms and assigned devices from HM automatically

### ISSUE THREAD

**Issue by gidhap** [sbormann/ioBroker.iqontrol#144]
Hi, I have all my devices assigned to rooms in homematic already, currently managed by the mediaola App.
Is there any chance or plan to automatically load all rooms and assigned devices from HM into iQontrol ?
I though asking before starting to creating rooms and importing devices one after the other is worthwhile to do :)
And thanks for your work with iQontrol, very much apprecciated

**Comment by sbormann** [comment]
It is planed - since a long time :)
May be i will find some time in the upcoming cold season to do that - but the wishlist is long :)
Best wishes

**Comment by gidhap** [comment]
Txs, sounds promising to me. As I push lots of stuff to "winter evenings" too, I'll vote for it going to the Christmas list :)
So in any case I'll wait before I start to transfer all my stuff manually. 
Unfortunately my knowledge in coding is close to zero, but in case you need a guinea pig for testing, let me know so I can at least support at this end.
All the best

**Comment by sbormann** [comment]
Should work with the newest version :)
