### ISSUE TITLE
RGB to HEX - Slider missing

### ISSUE THREAD

**Issue by kueppert** [sbormann/ioBroker.iqontrol#145]
![iqontrol_zigbee](https://user-images.githubusercontent.com/35038463/94534170-5c062080-0240-11eb-9618-a83ae6c494c8.PNG)
Hi @sbormann , 
i`m not able to get the ALTERNATIVE_COLORSPACE_VALUE working. I have already selected the correct datapoint and "RGB" (found an old issue from DutchmanNL, Issue #77 ).
But when i open this device, the slider for color is missing.

I`m using v1.2.6 of iQontrol. I have already deleted the Cache from Chrome on my mobile device (and tried it on my PC, too, without success). Any idea what i can do?

Thank you, kueppert

**Comment by sbormann** [comment]
Hi, could you please show me the value and the RAW of the datapoint that you used on ALTERNATIVE_COLORSPACE_VALUE? Many thanks!

**Comment by kueppert** [comment]
> 
> 
> Hi, could you please show me the value and the RAW of the datapoint that you used on ALTERNATIVE_COLORSPACE_VALUE? Many thanks!

Hi Sebastian, klar, mach ich gern ;)

{
  "from": "system.adapter.zigbee.0",
  "user": "system.user.admin",
  "ts": 1599476936789,
  "result": {},
  "common": {
    "name": "Color",
    "type": "string",
    "role": "level.color.rgb",
    "read": true,
    "write": true
  },
  "native": {
    "iQontrolTempValues": {
      "iqontrol.0.Views.Lichter.devices.14.HUE": 115,
      "iqontrol.0.Views.Lichter.devices.14.COLOR_BRIGHTNESS": 67,
      "iqontrol.0.Views.Lichter.devices.14.SATURATION": 81
    }
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "zigbee.0.7cb03eaa0a008dc9.color",
  "type": "state"
}

Ich sehe gerade die Values von iQontrol dort. Ich habe nichts via Schraubenschlüssel aktiv aktuell dort. Habe nur in iQontrol diesen Datenpunkt ausgewählt und #RGB im Dropdown selektiert.

**Comment by kueppert** [comment]
Habe mich jetzt am RAW des DPs meines Zigbee-LED-Stripes herangemacht und die EInträge von iQontrol manuell gelöscht (hab mich an meinem 2. Stripe orientiert, damit ich nicht zu viel lösche).
Habe nun im iQontrol den Stripe automatisch hinzufügen lassen, Ergebnis:
![grafik](https://user-images.githubusercontent.com/35038463/94919181-5d3f8380-04b4-11eb-88a2-00a32b21c2b5.png)
der Slider für die Farbe fehlt.
Nun in iQontrol - den Stripe rein und manuell bei "Farbraum für ALTERNATIVE_COLORSPACE_VALUE" #RGB ausgewählt, den Datenpunkt unter "CT" gelöscht.
Unerwartetes Ergebnis :-1: 
![grafik](https://user-images.githubusercontent.com/35038463/94919416-bad3d000-04b4-11eb-85a0-095444db8889.png)

**Comment by sbormann** [comment]
Hi,
zwei Fragen noch:
1) Welche Werte hat der Datenpunkt? (also wie sieht ein valider Wert aus, z.B. "#FF1234"?
2) Bitte mal ein Log aus der F12-Console schicken, wenn Du den Dialog mit dem fehlenden Slider öffnest.
Danke

**Comment by kueppert** [comment]
Hi,
danke für deine Hilfe :+1: zu 1.: korrekt, Objekt wird mit #FF0000 zB angesteuert:
![grafik](https://user-images.githubusercontent.com/35038463/94986159-b6fb8880-055c-11eb-85fc-19637d741fd0.png)

und 2.: Konsole in Chrome, Daten aus dem Reiter "Console":
Add timestamp to Osram Lightstrip 1 with value 0
index.js:3605 Converting #RGB from FF0000 to H|S|B/CT|B...
index.js:3707 ...result is 0|100|100/null|null
index.js:6971 Starting marquee observer
index.js:2182 Object not found
index.js:4485 PRESSURE end function - delete everything
index.js:10928 Shuffle!
index.js:2182 Object not found
index.js:10929 Shuffle!
index.js:4415 PRESSURE end via SCROLL
index.js:4461 PRESSURE end function
index.js:4471 PRESSURE end function - find active Toolbar Index
index.js:4485 PRESSURE end function - delete everything
index.js:4415 PRESSURE end via SCROLL
index.js:4461 PRESSURE end function
index.js:4471 PRESSURE end function - find active Toolbar Index
index.js:4485 PRESSURE end function - delete everything
index.js:6842 Add timestamp to Nachtlicht with value Aus
index.js:4410 PRESSURE end via TOUCHEND/MOUSEUP
index.js:4461 PRESSURE end function
index.js:7019 CLICK
index.js:7236 []
2index.js:6842 Add timestamp to Osram Lightstrip 1 with value 0
index.js:3605 Converting #RGB from FF0000 to H|S|B/CT|B...
index.js:3707 ...result is 0|100|100/null|null
index.js:4471 PRESSURE end function - find active Toolbar Index
index.js:4485 PRESSURE end function - delete everything
3index.js:6842 Add timestamp to Nachtlicht with value Aus

**Comment by kueppert** [comment]
wollte gerade in der Console noch was rumspielen, und auf einmal taucht alle sauf??? O.o
![grafik](https://user-images.githubusercontent.com/35038463/94986225-4143ec80-055d-11eb-8223-f4b5dc559f7c.png)
`Add timestamp to Nachtlicht with value Aus
index.js:4410 PRESSURE end via TOUCHEND/MOUSEUP
index.js:4461 PRESSURE end function
index.js:4471 PRESSURE end function - find active Toolbar Index
index.js:4485 PRESSURE end function - delete everything
index.js:6842 Add timestamp to Wohnzimmer Regal Stripe with value Aus
index.js:4410 PRESSURE end via TOUCHEND/MOUSEUP
index.js:4461 PRESSURE end function
index.js:7019 CLICK
index.js:7236 []
2index.js:6842 Add timestamp to Osram Lightstrip 1 with value 0
index.js:3605 Converting #RGB from FF0000 to H|S|B/CT|B...
index.js:3707 ...result is 0|100|100/null|null
index.js:4471 PRESSURE end function - find active Toolbar Index
index.js:4485 PRESSURE end function - delete everything
2index.js:6842 Add timestamp to Nachtlicht with value Aus
index.js:4410 PRESSURE end via TOUCHEND/MOUSEUP
index.js:4461 PRESSURE end function
index.js:4471 PRESSURE end function - find active Toolbar Index
index.js:4485 PRESSURE end function - delete everything
index.js:4415 PRESSURE end via SCROLL
index.js:4461 PRESSURE end function
index.js:4471 PRESSURE end function - find active Toolbar Index
index.js:4485 PRESSURE end function - delete everything
index.js:4415 PRESSURE end via SCROLL
index.js:4461 PRESSURE end function
index.js:4471 PRESSURE end function - find active Toolbar Index
index.js:6842 Add timestamp to Nachtlicht with value Aus
index.js:4485 PRESSURE end function - delete everything
index.js:4363 PRESSURE change start
index.js:4406 PRESSURE start via TOUCHSTART/MOUSEDOWN
index.js:4422 PRESSURE start function
index.js:4363 PRESSURE change start
index.js:4366 PRESSURE change start FALLBACK
index.js:4449 PRESSURE changeFunction else
index.js:4410 PRESSURE end via TOUCHEND/MOUSEUP
index.js:4461 PRESSURE end function
index.js:4461 PRESSURE end function
index.js:4514 renderView iqontrol.0.Views.Start
index.js:10943 resizeFullWidthDevicesToFitScreen with zoom-factor 1.0491803278688525
index.js:10915 resizeDevicesToFitScreen with zoom-factor 1.0491803278688525
index.js:6713 Starting shuffle resize observer
index.js:4351 PRESSURE end native
2index.js:4471 PRESSURE end function - find active Toolbar Index
index.js:6842 Add timestamp to Alexa Anruf Sprachausgabe with value Aus
translate.js:24 "disable": {"en": "disable", "de": "disable", "ru": "disable", "pt": "disable", "nl": "disable", "fr": "disable"},
index.js:6842 Add timestamp to Alarm with value disable
index.js:6842 Add timestamp to Fernbedienung with value Aus
translate.js:24 "Lichter": {"en": "Lichter", "de": "Lichter", "ru": "Lichter", "pt": "Lichter", "nl": "Lichter", "fr": "Lichter"},
index.js:6842 Add timestamp to Lichter with value 3&nbsp;Lichter
index.js:6842 Add timestamp to Fenster with value 4&nbsp;Fenster
translate.js:24 "Türen": {"en": "Türen", "de": "Türen", "ru": "Türen", "pt": "Türen", "nl": "Türen", "fr": "Türen"},
index.js:6842 Add timestamp to Türen with value 0&nbsp;Türen
translate.js:24 "Steckdosen": {"en": "Steckdosen", "de": "Steckdosen", "ru": "Steckdosen", "pt": "Steckdosen", "nl": "Steckdosen", "fr": "Steckdosen"},
index.js:6842 Add timestamp to Steckdosen with value 9&nbsp;Steckdosen
index.js:6971 Starting marquee observer
2index.js:4485 PRESSURE end function - delete everything
index.js:10928 Shuffle!
index.js:10929 Shuffle!
index.js:4410 PRESSURE end via TOUCHEND/MOUSEUP
index.js:4461 PRESSURE end function
index.js:7019 CLICK
index.js:4514 renderView Lichter
index.js:2164 Object was already Received: zigbee.0.group_1.color
index.js:2164 Object was already Received: zigbee.0.7cb03eaa0a008dc9.color
index.js:10943 resizeFullWidthDevicesToFitScreen with zoom-factor 1.0491803278688525
index.js:10915 resizeDevicesToFitScreen with zoom-factor 1.0491803278688525
index.js:6713 Starting shuffle resize observer
index.js:4471 PRESSURE end function - find active Toolbar Index
translate.js:24 "K": {"en": "K", "de": "K", "ru": "K", "pt": "K", "nl": "K", "fr": "K"},
2index.js:2167 Already waiting for object: 
2translate.js:24 "°": {"en": "°", "de": "°", "ru": "°", "pt": "°", "nl": "°", "fr": "°"},
translate.js:24 "°K": {"en": "°K", "de": "°K", "ru": "°K", "pt": "°K", "nl": "°K", "fr": "°K"},
index.js:2167 Already waiting for object: 
2translate.js:24 "°": {"en": "°", "de": "°", "ru": "°", "pt": "°", "nl": "°", "fr": "°"},
translate.js:24 "°K": {"en": "°K", "de": "°K", "ru": "°K", "pt": "°K", "nl": "°K", "fr": "°K"},
3index.js:2167 Already waiting for object: null
translate.js:24 "°K": {"en": "°K", "de": "°K", "ru": "°K", "pt": "°K", "nl": "°K", "fr": "°K"},
2index.js:2167 Already waiting for object: null
index.js:2167 Already waiting for object: 
translate.js:24 "°": {"en": "°", "de": "°", "ru": "°", "pt": "°", "nl": "°", "fr": "°"},
index.js:3605 Converting #RGB from FF0000 to H|S|B/CT|B...
index.js:3707 ...result is 0|100|100/null|null
index.js:2791 >>>>>> setState TEMP:iqontrol.0.Views.Lichter.devices.14.SATURATION: 0 --> 100
index.js:2894        setState only local, because state ist CONST, ARRAY or TEMP
index.js:2791 >>>>>> setState TEMP:iqontrol.0.Views.Lichter.devices.14.COLOR_BRIGHTNESS: 0 --> 100
index.js:2894        setState only local, because state ist CONST, ARRAY or TEMP
index.js:2167 Already waiting for object: 
index.js:3009 >> ack: false val: 100 newVal: 100
index.js:3605 Converting #RGB from FF0000 to H|S|B/CT|B...
index.js:3707 ...result is 0|100|100/null|null
index.js:3554 Converting H|S|B/CT|B from 0|100|100/null|null to #RGB...
index.js:3596 ...result is #ff0000
index.js:2791 >>>>>> setState zigbee.0.7cb03eaa0a008dc9.color: FF0000 --> #FF0000
index.js:3009 >> ack: false val: 100 newVal: 100
index.js:3605 Converting #RGB from FF0000 to H|S|B/CT|B...
index.js:3707 ...result is 0|100|100/null|null
index.js:3554 Converting H|S|B/CT|B from 0|100|100/null|null to #RGB...
index.js:3596 ...result is #ff0000
index.js:2791 >>>>>> setState zigbee.0.7cb03eaa0a008dc9.color: FF0000 --> #FF0000
index.js:3605 Converting #RGB from FF0000 to H|S|B/CT|B...
index.js:3707 ...result is 0|100|100/null|null
index.js:3554 Converting H|S|B/CT|B from 0|100|100/null|null to #RGB...
index.js:3596 ...result is #ff0000
index.js:2791 >>>>>> setState zigbee.0.7cb03eaa0a008dc9.color: FF0000 --> #FF0000
2index.js:6842 Add timestamp to Wohnzimmer Regal Stripe with value Aus
translate.js:24 "K": {"en": "K", "de": "K", "ru": "K", "pt": "K", "nl": "K", "fr": "K"},
index.js:6842 Add timestamp to Wohnzimmer Schranklicht with value Ein
index.js:6842 Add timestamp to Wohnzimmer Aura with value 0
2translate.js:24 "°": {"en": "°", "de": "°", "ru": "°", "pt": "°", "nl": "°", "fr": "°"},
2index.js:6842 Add timestamp to Esszimmerlicht ALL with value 80
2translate.js:24 "°": {"en": "°", "de": "°", "ru": "°", "pt": "°", "nl": "°", "fr": "°"},
translate.js:24 "°K": {"en": "°K", "de": "°K", "ru": "°K", "pt": "°K", "nl": "°K", "fr": "°K"},
index.js:6842 Add timestamp to Hochzeitsburg with value Ein
2index.js:6842 Add timestamp to Melina Deckenlampe with value Aus
2index.js:6842 Add timestamp to Deckenlicht with value 68
translate.js:24 "°K": {"en": "°K", "de": "°K", "ru": "°K", "pt": "°K", "nl": "°K", "fr": "°K"},
2index.js:6842 Add timestamp to Wandlicht with value 50
2index.js:6842 Add timestamp to Deckenlampe with value 0
index.js:6842 Add timestamp to Nachtlicht with value Aus
2index.js:6842 Add timestamp to Treppe Wand with value 0
2index.js:6842 Add timestamp to Keller with value 0
translate.js:24 "°K": {"en": "°K", "de": "°K", "ru": "°K", "pt": "°K", "nl": "°K", "fr": "°K"},
2index.js:6842 Add timestamp to Abstellkammer with value 0
2index.js:6842 Add timestamp to Gardenpoles with value 0
translate.js:24 "°": {"en": "°", "de": "°", "ru": "°", "pt": "°", "nl": "°", "fr": "°"},
2index.js:6842 Add timestamp to Osram Lightstrip 1 with value 0
index.js:3009 >> ack: true val: FF0000 newVal: #FF0000
index.js:3605 Converting #RGB from FF0000 to H|S|B/CT|B...
index.js:3707 ...result is 0|100|100/null|null
index.js:6971 Starting marquee observer
index.js:4485 PRESSURE end function - delete everything
index.js:2887 << preventUpdate dexpired.
index.js:3605 Converting #RGB from FF0000 to H|S|B/CT|B...
index.js:3707 ...result is 0|100|100/null|null
index.js:3554 Converting H|S|B/CT|B from 0|100|100/null|null to #RGB...
index.js:3596 ...result is #ff0000
index.js:2791 >>>>>> setState zigbee.0.7cb03eaa0a008dc9.color: FF0000 --> #FF0000
index.js:2887 << preventUpdate dexpired.
index.js:3605 Converting #RGB from FF0000 to H|S|B/CT|B...
index.js:3707 ...result is 0|100|100/null|null
index.js:3554 Converting H|S|B/CT|B from 0|100|100/null|null to #RGB...
index.js:3596 ...result is #ff0000
index.js:2791 >>>>>> setState zigbee.0.7cb03eaa0a008dc9.color: FF0000 --> #FF0000
index.js:10928 Shuffle!
4index.js:2213 deliverState done
2index.js:2221 deliverObject done
index.js:2213 deliverState done
4index.js:3009 >> ack: false val: #FF0000 newVal: #FF0000
index.js:3009 >> ack: true val: #FF0000 newVal: #FF0000
index.js:3012 << ack-val reached new val: preventUpdate regular ended.
index.js:3605 Converting #RGB from #FF0000 to H|S|B/CT|B...
index.js:3707 ...result is 0|100|100/null|null
index.js:3605 Converting #RGB from #FF0000 to H|S|B/CT|B...
index.js:3707 ...result is 0|100|100/null|null
index.js:3605 Converting #RGB from #FF0000 to H|S|B/CT|B...
index.js:3707 ...result is 0|100|100/null|null
index.js:3605 Converting #RGB from #FF0000 to H|S|B/CT|B...
index.js:3707 ...result is 0|100|100/null|null
index.js:3605 Converting #RGB from #FF0000 to H|S|B/CT|B...
index.js:3707 ...result is 0|100|100/null|null
index.js:3605 Converting #RGB from #FF0000 to H|S|B/CT|B...
index.js:3707 ...result is 0|100|100/null|null
index.js:3605 Converting #RGB from #FF0000 to H|S|B/CT|B...
index.js:3707 ...result is 0|100|100/null|null
index.js:3605 Converting #RGB from #FF0000 to H|S|B/CT|B...
index.js:3707 ...result is 0|100|100/null|null
index.js:3605 Converting #RGB from #FF0000 to H|S|B/CT|B...
index.js:3707 ...result is 0|100|100/null|null
index.js:3605 Converting #RGB from #FF0000 to H|S|B/CT|B...
index.js:3707 ...result is 0|100|100/null|null
index.js:3605 Converting #RGB from #FF0000 to H|S|B/CT|B...
index.js:3707 ...result is 0|100|100/null|null
index.js:10929 Shuffle!
index.js:6842 Add timestamp to Nachtlicht with value Aus
index.js:4415 PRESSURE end via SCROLL
index.js:4461 PRESSURE end function
index.js:4471 PRESSURE end function - find active Toolbar Index
index.js:4485 PRESSURE end function - delete everything
index.js:4415 PRESSURE end via SCROLL
index.js:4461 PRESSURE end function
index.js:4471 PRESSURE end function - find active Toolbar Index
index.js:4485 PRESSURE end function - delete everything
index.js:4415 PRESSURE end via SCROLL
index.js:4461 PRESSURE end function
index.js:4471 PRESSURE end function - find active Toolbar Index
index.js:4485 PRESSURE end function - delete everything
index.js:4415 PRESSURE end via SCROLL
index.js:4461 PRESSURE end function
index.js:4471 PRESSURE end function - find active Toolbar Index
index.js:4485 PRESSURE end function - delete everything
index.js:4410 PRESSURE end via TOUCHEND/MOUSEUP
index.js:4461 PRESSURE end function
index.js:7019 CLICK
index.js:7236 []
2index.js:6842 Add timestamp to Osram Lightstrip 1 with value 0
index.js:3605 Converting #RGB from #FF0000 to H|S|B/CT|B...
index.js:3707 ...result is 0|100|100/null|null
index.js:3554 Converting H|S|B/CT|B from 0|100|100/null|null to #RGB...
index.js:3596 ...result is #ff0000
index.js:2791 >>>>>> setState zigbee.0.7cb03eaa0a008dc9.color: #FF0000 --> #FF0000
index.js:3605 Converting #RGB from #FF0000 to H|S|B/CT|B...
index.js:3707 ...result is 0|100|100/null|null
index.js:3554 Converting H|S|B/CT|B from 0|100|100/null|null to #RGB...
index.js:3596 ...result is #ff0000
index.js:3605 Converting #RGB from #FF0000 to H|S|B/CT|B...
index.js:3707 ...result is 0|100|100/null|null
index.js:3554 Converting H|S|B/CT|B from 0|100|100/null|null to #RGB...
index.js:3596 ...result is #ff0000
index.js:3009 >> ack: true val: #FF0000 newVal: #FF0000
index.js:3012 << ack-val reached new val: preventUpdate regular ended.
index.js:3605 Converting #RGB from #FF0000 to H|S|B/CT|B...
index.js:3707 ...result is 0|100|100/null|null
index.js:4471 PRESSURE end function - find active Toolbar Index
index.js:2213 deliverState done
index.js:3605 Converting #RGB from #FF0000 to H|S|B/CT|B...
index.js:3707 ...result is 0|100|100/null|null
index.js:3605 Converting #RGB from #FF0000 to H|S|B/CT|B...
index.js:3707 ...result is 0|100|100/null|null
index.js:4485 PRESSURE end function - delete everything
index.js:3605 Converting #RGB from #FF0000 to H|S|B/CT|B...
index.js:3707 ...result is 0|100|100/null|null
5index.js:6842 Add timestamp to Nachtlicht with value Aus
index.js:6658 viewTimestampElapsedTimer for 0 states
index.js:6842 Add timestamp to Nachtlicht with value Aus`

**Comment by kueppert** [comment]
Einmal iQontrol im Firefox geöffnet (Kommentar vorher war Chrome). Jetzt hab ich eine leere Seite:

Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: http://192.168.178.69:8082/iqontrol/jquery/jquery.mobile-1.4.5.min.js
Source-Map-Adresse: jquery.mobile-1.4.5.min.map

Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: http://192.168.178.69:8082/lib/js/socket.io.js
Source-Map-Adresse: socket.io.js.map

Einige Cookies verwenden das empfohlene "SameSite"-Attribut inkorrekt. 2
Das Cookie "io" wird in Zukunft bald abgelehnt werden, da es für das Attribut "SameSite" entweder "None" oder einen ungültigen Wert angibt, ohne das "secure"-Attribut zu verwenden. Weitere Informationen zum "SameSite"-Attribut finden Sie unter https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite. socket.io
Das Cookie "io" wird in Zukunft bald abgelehnt werden, da es für das Attribut "SameSite" entweder "None" oder einen ungültigen Wert angibt, ohne das "secure"-Attribut zu verwenden. Weitere Informationen zum "SameSite"-Attribut finden Sie unter https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite. socket.io
Layout-Darstellung wurde erzwungen, bevor die Seite vollständig geladen war. Falls Stylesheet noch nicht geladen sind, kann dies zu einem kurzzeitigen Darstellung des Inhalts ohne Formatierung führen. jquery-3.2.1.min.js:4
window.controllers/Controllers sollte nicht mehr verwendet werden. Verwenden Sie es nicht für die Browser-Erkennung. ace.js:1
Passwort-Felder sind auf einer unsicheren (http://) Seite vorhanden. Dies ist ein Sicherheitsrisiko, durch das Zugangsdaten gestohlen werden können.
192.168.178.69:8081
Einige Cookies verwenden das empfohlene "SameSite"-Attribut inkorrekt. 8
Das Cookie "io" wird in Zukunft bald abgelehnt werden, da es für das Attribut "SameSite" entweder "None" oder einen ungültigen Wert angibt, ohne das "secure"-Attribut zu verwenden. Weitere Informationen zum "SameSite"-Attribut finden Sie unter https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite. socket.io
Das Cookie "io" wird in Zukunft bald abgelehnt werden, da es für das Attribut "SameSite" entweder "None" oder einen ungültigen Wert angibt, ohne das "secure"-Attribut zu verwenden. Weitere Informationen zum "SameSite"-Attribut finden Sie unter https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite. socket.io
Das Cookie "io" wird in Zukunft bald abgelehnt werden, da es für das Attribut "SameSite" entweder "None" oder einen ungültigen Wert angibt, ohne das "secure"-Attribut zu verwenden. Weitere Informationen zum "SameSite"-Attribut finden Sie unter https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite. socket.io
Das Cookie "io" wird in Zukunft bald abgelehnt werden, da es für das Attribut "SameSite" entweder "None" oder einen ungültigen Wert angibt, ohne das "secure"-Attribut zu verwenden. Weitere Informationen zum "SameSite"-Attribut finden Sie unter https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite. socket.io
Das Cookie "io" wird in Zukunft bald abgelehnt werden, da es für das Attribut "SameSite" entweder "None" oder einen ungültigen Wert angibt, ohne das "secure"-Attribut zu verwenden. Weitere Informationen zum "SameSite"-Attribut finden Sie unter https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite. socket.io
Das Cookie "io" wird in Zukunft bald abgelehnt werden, da es für das Attribut "SameSite" entweder "None" oder einen ungültigen Wert angibt, ohne das "secure"-Attribut zu verwenden. Weitere Informationen zum "SameSite"-Attribut finden Sie unter https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite. socket.io
Das Cookie "io" wird in Zukunft bald abgelehnt werden, da es für das Attribut "SameSite" entweder "None" oder einen ungültigen Wert angibt, ohne das "secure"-Attribut zu verwenden. Weitere Informationen zum "SameSite"-Attribut finden Sie unter https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite. 2 socket.io
Das Cookie "io" wird in Zukunft bald abgelehnt werden, da es für das Attribut "SameSite" entweder "None" oder einen ungültigen Wert angibt, ohne das "secure"-Attribut zu verwenden. Weitere Informationen zum "SameSite"-Attribut finden Sie unter https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite. 2 socket.io
Fancytree@1 Fancytree.filterNodes() leavesOnly option is deprecated since 2.9.0 / 2015-04-19. Use opts.leavesOnly instead. jquery.fancytree-all.js:113

​

**Comment by kueppert** [comment]
Und nochmal Chrome, vorher BrowserDaten geleert, iQontrol geöffnet und OsramStripe geklickt. Ggf helfen die Fehlermeldungen am Anfang weiter?

**DevTools failed to load SourceMap: Could not load content for http://192.168.178.69:8082/iqontrol/jquery/jquery.mobile-1.4.5.min.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://192.168.178.69:8082/iqontrol/jquery/plugins/shuffle.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://192.168.178.69:8082/lib/js/socket.io.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
index.js:10928 Shuffle!**
2index.js:6842 Add timestamp to Wohnzimmer Regal Stripe with value 100%
translate.js:24 "K": {"en": "K", "de": "K", "ru": "K", "pt": "K", "nl": "K", "fr": "K"},
index.js:10929 Shuffle!
index.js:6842 Add timestamp to Nachtlicht with value Aus
index.js:6842 Add timestamp to Wohnzimmer Schranklicht with value Ein
index.js:4410 PRESSURE end via TOUCHEND/MOUSEUP
index.js:4461 PRESSURE end function
index.js:7019 CLICK
index.js:7236 []
2index.js:6842 Add timestamp to Osram Lightstrip 1 with value 0
index.js:3605 Converting #RGB from #FF0000 to H|S|B/CT|B...
index.js:3707 ...result is 0|100|100/null|null
index.js:4471 PRESSURE end function - find active Toolbar Index
index.js:4485 PRESSURE end function - delete everything
index.js:6842 Add timestamp to Nachtlicht with value Aus
index.js:6842 Add timestamp to Wohnzimmer Schranklicht with value Ein
index.js:6842 Add timestamp to Nachtlicht with value Aus
index.js:6842 Add timestamp to Wohnzimmer Schranklicht with value Ein

**Comment by sbormann** [comment]
Hi, sorry, dass das so lange gedauert hat! Habe mir jetzt mal die Logs von Dir angeschaut. Dabei bin ich, im vorletzten Post von Dir, über eine Sache gestolpert:

````
ndex.js:2791 >>>>>> setState zigbee.0.7cb03eaa0a008dc9.color: FF0000 --> #FF0000
index.js:2887 << preventUpdate dexpired.
index.js:3605 Converting #RGB from FF0000 to H|S|B/CT|B...
index.js:3707 ...result is 0|100|100/null|null
index.js:3554 Converting H|S|B/CT|B from 0|100|100/null|null to #RGB...
index.js:3596 ...result is #ff0000
index.js:2791 >>>>>> setState zigbee.0.7cb03eaa0a008dc9.color: FF0000 --> #FF0000
````

Da stehen die RGB-Farbwerte einmal in der Form ``FF0000`` und einmal als ``#FF0000``. Vielleicht liegt da der Fehler? Versuche doch mal als ALTERNATIVE_COLORSPACE ``RGB`` statt ``#RGB``. Vielleicht klappt es damit?

**Comment by kueppert** [comment]
Hi @sbormann 
kein Problem, du hast ja auch noch ein Privatleben - und im Forum sind auch alle ganz fleißig, dir neue Ideen mitzuteilen ;)

ich habe jetzt auf RGB umgestellt. Als erstes fällt mir folgendes auf, wenn ich den Tab von iQontrol öffne:
```
DevTools failed to load SourceMap: Could not load content for http://192.168.178.69:8082/iqontrol/jquery/jquery.mobile-1.4.5.min.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

DevTools failed to load SourceMap: Could not load content for http://192.168.178.69:8082/iqontrol/jquery/plugins/shuffle.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

DevTools failed to load SourceMap: Could not load content for http://192.168.178.69:8082/lib/js/socket.io.js.map: HTTP error:
status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

jetzt gehe ich in meine Lichter und öffne meinen RGB-Stripe:

```
index.js:7073 viewDeviceContextMenu start via TOUCHSTART/MOUSEDOWN
index.js:7090 viewDeviceContextMenu start function
index.js:4500 toolbarContextMenu end function
index.js:4505 toolbarContextMenu end function - find active Toolbar Index
index.js:7108 viewDeviceContextMenu level: -0.18750000000000003
index.js:7108 viewDeviceContextMenu level: -0.125
index.js:4452 toolbarContextMenu end via TOUCHEND/MOUSEUP
index.js:4500 toolbarContextMenu end function
index.js:7078 viewDeviceContextMenu end via TOUCHEND/MOUSEUP
index.js:7126 viewDeviceContextMenu end function
index.js:7078 viewDeviceContextMenu end via TOUCHEND/MOUSEUP
index.js:7126 viewDeviceContextMenu end function
index.js:7057 viewDeviceContextMenu device CLICK
index.js:7126 viewDeviceContextMenu end function
index.js:7176 renderDialog iqontrol.0.Views.Lichter.devices.14
index.js:7208 []
2index.js:6879 Add timestamp to Osram Lightstrip 1 with value 0
index.js:3715 Converting RGB from #3fe0d0 to H|S|B/CT|B...
index.js:3817 ...result is 174|72|88/null|null
index.js:4505 toolbarContextMenu end function - find active Toolbar Index
index.js:7099 viewDeviceContextMenu ignore click ended after 100ms
2index.js:4519 toolbarContextMenu end function - end ignoreStart
3index.js:7131 viewDeviceContextMenu end function - end ignoreStart
2index.js:6879 Add timestamp to Nachtlicht with value Ein
```

Leider fehlt der Slider weiterhin :/

**Comment by sbormann** [comment]
Hey, habe hier jetzt noch mal versucht nachzubessern. Könntest Du es bitte noch mal mit der aktuellen Github-Version checken?
VG!

**Comment by kueppert** [comment]
Hi @sbormann 
die Slider werden jetzt dargestellt, top. Morgen probiere ich noch aus, ob die Farben auch richtig bei meinen Stipes ankommen. Sieht auf jeden Fall schon sehr gut aus. Danke dir :)
Ich melde mich noch wegen meines abschließenden Tests.
VG Thorsten

**Comment by kueppert** [comment]
@sbormann 
YES, you made my day ;) Slider funktionieren wunderbar. Danke dir.
VG Thorsten

**Comment by o0shojo0o** [comment]
Bei mir tritt der Fehler leider auch wieder auf.
Adapter Version: 1.9.16

![image](https://user-images.githubusercontent.com/19333515/143143877-644b6f91-98f9-4c7f-9431-59b5d2c07f89.png)
![image](https://user-images.githubusercontent.com/19333515/143143888-869fc025-1de0-40f6-b20b-ccb77462bf50.png)
![image](https://user-images.githubusercontent.com/19333515/143143892-5ee33652-8a3f-4ecc-baf0-7a767fd7a07f.png)
![image](https://user-images.githubusercontent.com/19333515/143143897-accfa22c-4c8f-4814-b393-585acb569024.png)
```
renderDialog iqontrol.0.Views.Terrasse.devices.1
index.js:7958 []
index.js:7566 Add timestamp to Garden Poles with value 0
index.js:7764 !stateFillsDevice or badge is invisible - remove padding-top
index.js:7566 Add timestamp to Garden Poles with value 0
index.js:7764 !stateFillsDevice or badge is invisible - remove padding-top
index.js:3078 Converting #RGB from #FF0044 to H|S|B/CT|B...
index.js:3187 ...result is 344|100|100/null|null
index.js:3022 Converting H|S|B/CT|B from 344|100|100/8.9|null to #RGB...
index.js:3069 ...result is #ff0044
index.js:5603 Not sending state, because a white value was changed, but AlternativeColorspace is without white
index.js:3078 Converting #RGB from #FF0044 to H|S|B/CT|B...
index.js:3187 ...result is 344|100|100/null|null
index.js:4477 toolbarContextMenu end function - find active Toolbar Index
```
