### ISSUE TITLE
IQontrol background HTML contains \n elements.

### ISSUE THREAD

**Issue by louisvangeldrop** [sbormann/ioBroker.iqontrol#146]
I use VSCode as my development environment. I generate a html-file with the following content:

<!doctype html>
<html>

<body>
    <span id="batt"></span>
    <script type="text/javascript">
        let batterij = document.getElementById("batt")
        async function run() {
            let battAsync = await navigator.getBattery()
            batterij.innerHTML = `${battAsync.level * 100}%`
        }
        run()
    </script>
</body>

</html>

Then from VSCode I copy and paste this code into the background HTML of a Battery-widget.

In the Devtools of the running page the code for the <script> section looks like this:

<script type="text/javascript">\n        let batterij = document.getElementById("batt")\n        async function run() {\n            let battAsync = await navigator.getBattery()\n            batterij.innerHTML = `${battAsync.level * 100}%`\n        }\n        run()\n    </script>

It will not run because the "\n"'s

What mistake I am making?

**Comment by louisvangeldrop** [comment]
In VSCode the HTML file looks like this:

![image](https://user-images.githubusercontent.com/10716245/95205185-50d56680-07e5-11eb-9cd9-f916062db3b3.png)

**Comment by sbormann** [comment]
I think you might fix this problem by adding a semicolon (;) after each javascript command:
Could you please try this?

(On the other hand i'm not shure why all line-breaks are replaced by \n (which is the escaped form of a line-break) - i need to look deeper into this. Maybe there is a bug as well.)

**Comment by sbormann** [comment]
Correct code:
````
let batterij = document.getElementById("batt");
async function run() {
    let battAsync = await navigator.getBattery();
    batterij.innerHTML = `${battAsync.level * 100}%`;
 }
run();
````

**Comment by louisvangeldrop** [comment]
I tried your suggestion. Helas the same problem

**Comment by sbormann** [comment]
Ok, thanks for trying this. I will look into this.

--
Von meinem iPhone aus gesendet

Am 06.10.2020 um 19:16 schrieb Louis van Geldrop <notifications@github.com>:

﻿

I tried your suggestion. Helas the same problem

**Comment by louisvangeldrop** [comment]
The \n not only in the javascript-sction, but also in the other parts. I get a lot \n's shown in the widget

**Comment by sbormann** [comment]
Please try acutal github version, if it works now.
How do you add the html-code to iqontrol? If you paste it to an iobroker-datapoint, it is important to paste it into the edit-box of the datapoint: 
![image](https://user-images.githubusercontent.com/49171332/95254291-f73e5d80-081f-11eb-9b66-df4edfebbb6e.png)

![image](https://user-images.githubusercontent.com/49171332/95254319-01605c00-0820-11eb-83fd-0619f41d1b5b.png)

**Comment by louisvangeldrop** [comment]
I use IQontrol editor:

![image](https://user-images.githubusercontent.com/10716245/95258007-6e2a2500-0825-11eb-9c9e-b43744c9cba0.png)

**Comment by sbormann** [comment]
And is it working now?

**Comment by louisvangeldrop** [comment]
The \n's are gone in the background_html. However the javascript is still not executed.

As another issue: the \n's do still exist in e.g. the "state" field

**Comment by sbormann** [comment]
I suggest working with the new ability to create, upload and edit html, css and js files in the IMAGES/WIDGETS tab. You can then assign these files to the BACKGROUND_URL-Field by drop-down menu, instead of using BACKGROUND_HTML-Field. This works flawless and keeps your config-file free from large html-settings, because they are kept in external files.

**Comment by louisvangeldrop** [comment]
Thanks a lot. for your support I will try it as soon as possible.
