### ISSUE TITLE
CO2 Datenpunkt für Temperatursensoren

### ISSUE THREAD

**Issue by nob0dy80** [sbormann/ioBroker.iqontrol#147]
Bitte den Datenpunkt CO2 für Temperatursensoren einfügen.
Aktuelle Sensoren erfassen mehr als Temperatur und Luftfeuchtigkeit.

Dankeeeee

**Comment by sbormann** [comment]
Hi, hierfür bitte die Arrays INFO_A oder INFO_B nutzen, damit kannst Du Dir beliebig viele Datenpunkte anzeigen lassen (optional mit eigenen Symbolen).
