### ISSUE TITLE
Falsche Anzeige von Batteriestatus

### ISSUE THREAD

**Issue by nob0dy80** [sbormann/ioBroker.iqontrol#148]
Egal wie der Prozentsatz aussieht, das Icon ist immer gleich:

![image](https://user-images.githubusercontent.com/28686079/97110216-3ef62d80-16d8-11eb-96e9-52154afdd043.png)
![image](https://user-images.githubusercontent.com/28686079/97110247-6220dd00-16d8-11eb-935d-f0bb73127217.png)
![image](https://user-images.githubusercontent.com/28686079/97110262-8086d880-16d8-11eb-8961-6fe4c21608b8.png)

Die Batterieanzeige taucht bei mir auch NUR auf wenn ich "alway on" wähle. Bei Standard wird nichts angezeigt.

Achja: Adapter 1.3.3, iobroker komplett aktuell.

**Comment by sbormann** [comment]
Das ist "by design". Die Anzeige ist keine Prozentanzeige, sondern nur ein Logo für "Batterie leer":
https://github.com/sbormann/ioBroker.iqontrol#further-general-states

Für solche Fragen kannst Du auch gerne das Forum nutzen, da sind viele aktiv und beteiligen sich an der Beantwortung der Fragen.
