### ISSUE TITLE
Gekippt Icon wird bei Gerätetyp Fenster nicht angezeigt

### ISSUE THREAD

**Issue by hetti72** [sbormann/ioBroker.iqontrol#149]
**Describe the bug**  
Ich benutze mehrere HmIP Fenstergriff Sensoren. Die Sensoren geben 0 (closed), 1 (tilted) und 2 (open) als Werte zurück. Ein entsprechendes Gerät zeigt im Status dazu "Geschlossen" , "Gekippt" oder "geöffnet" an. Es werden dazu aber nur die Icons für ein geschlossenes oder geöffnetes Fenster angezeigt. Das ist das Fenster gekippt, wird ebenfalls ein geöffnetes Fenster angezeigt. 

Trägt man nun in der Geräte (Kachel) konfiguration in IQontrol unter Gerätespezifische Optionen in das Feld "Wert von STATE für gekippt" den Wert "Gekippt" ein, wird auch das gekippt Icon auf der Kachel angezeigt. 

![image](https://user-images.githubusercontent.com/54002469/97268627-74139480-182c-11eb-8771-97ce944e6cae.png)

Da der HmIP Sensor aber die Werte 0,1,2 und die States closed,tilted,open zurückgibt muss die Übersetzung in Geschlossen,Gekippt,Geöffnet in IQontrol erfolgen. Ich vermute das es hier einen Bug im mapping der Icons gibt.

**Comment by sbormann** [comment]
Hi,
ich denke, dass das an der Groß/Kleinschreibung liegt (iQontrol prüft auf 'gekippt' - HmIP scheint aber 'Gekippt', also großgeschrieben zurückzumelden). Ich werde in der nächsten Version eine Prüfung auf groß/kleinschreibung einbauen, bitte gib mir mal Rückmeldung, ob das Problem dann behoben ist. Die nächste Version werde ich heute noch online stellen.
VG!

**Comment by hetti72** [comment]
> HmIP scheint aber 'Gekippt', also großgeschrieben zurückzumelden

Also "Gekippt" steht nirgendwo in meinem DP: 

```
{
  "type": "state",
  "common": {
    "name": "Balkontür Büro:1.STATE",
    "def": "CLOSED",
    "type": "number",
    "read": true,
    "write": false,
    "min": 0,
    "max": 2,
    "states": {
      "0": "CLOSED",
      "1": "TILTED",
      "2": "OPEN"
    },
    "role": "state"
  },
  "native": {
    "MIN": "CLOSED",
    "OPERATIONS": 5,
    "MAX": "OPEN",
    "FLAGS": 1,
    "ID": "STATE",
    "TYPE": "ENUM",
    "DEFAULT": "CLOSED",
    "VALUE_LIST": [
      "CLOSED",
      "TILTED",
      "OPEN"
    ],
    "CONTROL": "RHS.STATE"
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1600861131540,
  "_id": "hm-rpc.2.0007D8A98BAE64.1.STATE",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

**Comment by hetti72** [comment]
Das Problem besteht mit der 1.3.5 Version immer noch. Ich muss für den State "gekippt"  Gekippt als Value angeben, dann funktioniert es

**Comment by hetti72** [comment]
Update: Wenn man alle werte unter "Gerätspezifische Optionen" löscht, funktioniert alles :-) 

Also Problem gelöst....

...Close
