### ISSUE TITLE
 neue Demo auf 2. Instanz 

### ISSUE THREAD

**Issue by oke24** [sbormann/ioBroker.iqontrol#151]
Ich habe ein Problem mit der neuen erweiterten Demo.
Als 2. Instanz der iqontrol-Version 1.4.1 Github-Version installiert wird bei mir unter dem Link http://192.168.1.119:8082/iqontrol/index.html?namespace=iqontrol.1 eine fast leere Seite angezeigt

![image](https://user-images.githubusercontent.com/46261409/98419332-21847480-2085-11eb-8cfe-484c015f33df.png)

Das ist auch der Fall wenn ich eine Seite explizit via URL anspringe, z.B. 
http://192.168.1.119:8082/iqontrol/index.html?namespace=iqontrol.1&home=iqontrol.1.Views.Home

Der Consolen-Output ist:

```
DevTools failed to load SourceMap: Could not load content for http://192.168.1.119:8082/lib/js/socket.io.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
--
  | DevTools failed to load SourceMap: Could not load content for http://192.168.1.119:8082/iqontrol/jquery/jquery.mobile-1.4.5.min.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
  | DevTools failed to load SourceMap: Could not load content for http://192.168.1.119:8082/iqontrol/jquery/plugins/shuffle.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
  | index.js:11668 Socket connected - getStarted
  | index.js:2497 * Get started...
  | index.js:2509 * Fetch system config...
  | index.js:2511 * System config received.
  | index.js:2515 * Fetch config...
  | index.js:2567 * Creating options-object
  | index.js:2517 * Config received.
  | index.js:2518 * Handle options...
  | index.js:2520 * Options handeled.
  | index.js:2521 * Render toolbar...
  | index.js:2523 * Toolbar rendered.
  | index.js:2524 * Render actual\|home view...
  | index.js:4902 renderView , triggeredByReconnection: true
  | index.js:4903 Set viewId to homeId:
  | index.js:4904 No viewId to render!
  | index.js:2531 * Actual view rendered.
  | 3index.js:11496 Page visible-event - socket is connected
```

**Comment by sbormann** [comment]
Mir kommt da eine Idee: hast Du vielleicht, nachdem die Demo-View erstellt wurde, nicht gespeichert?

**Comment by oke24** [comment]
Ja, das war die richtige Idee - vielen Dank !
Das reine Speichern, ohne das ich eine Änderung an der IQontrol Configuration vorgenommen habe, hat schon geholfen ! 

Jetzt sehe ich die Startseite, allerdings browserunabhängig noch in einer seltsam dunklen Darstellung

![image](https://user-images.githubusercontent.com/46261409/98462706-1711ca00-21ae-11eb-940a-da060cc7ff9a.png)

Beim Blick in die Adapterkonfiguration unter "Optionen" sieht man, dass sämtliche Colors, Background-Colors usw. per default auf Schwarz (#000000).  Ist das so beabsichtigt oder liegt hier noch ein Fehler bei mir vor ?

**Comment by sbormann** [comment]
Hmm, nein, die Optionen sollten nicht schwarz sein. Da ist wohl irgendwas schief gelaufen und es hilft wohl nur, alle Optionen auf Standard zurückzusetzen (also auf alle "X"-Icons klicken), sorry.

**Comment by sbormann** [comment]
#156 Sieht aber so aus, als gäbe es das Problem öfters...
