### ISSUE TITLE
Listen-Generation

### ISSUE THREAD

**Issue by ToTXR4Y** [sbormann/ioBroker.iqontrol#152]
Hi,
ich vermisse eine sehr nützliche Funktion in der IQontrol und zwar das nutzen von "Listen".

Ich stelle mir das so vor:
Liste:
-> Variable Unterpunkte aus den von mir gewählten Geräten (z.B. Luftdruck, Temperatur)

Das ganze könnte quasi so aufgebaut werden wie die INFO_A/B Sektionen wo ich einzelne Felder mit entsprechenden Werten und einem eigenen Text füllen kann zur reinen Anzeige.

Hintergrund:
Ich möchte z.B. eine Liste füllen mit den aktuellen Batterieständen aller Geräte. Dazu kann ich jedem Gerät einen Namen geben und den jeweiligen State der Batterie. Zusätzlich sollte noch die Möglichkeit bestehen diesen Geräten farbige Icons hinzufügen zu können (z.B. Batterie Grün -> Voll, Rot wenn leer). 
Alternativbeispiel offene Fenster: Alle geschlossenen sind Grün, alle offenen Fenster sind Rot markiert (z.B. Slider Symbol wie bei Lampenswitches).

So bekommt man sehr schnell sehr viele Informationen über ein Tile/Liste.

**Comment by sbormann** [comment]
Hi,
also so, wie ADDITIONAL_INFO, nur mit Icon?

**Comment by ToTXR4Y** [comment]
Ja quasi. Bisschen in Hübsch vielleicht :-P

Weitere Beispiele: Fenster offen/zu Status, Licht an/aus Status, aber eben als Liste in einem Tile.

Also ähnlich wie in HabPanel. Damit lassen sich dann in einem 1x3 Tile viele Informationen unterbringen und geben einen schnellen Überblick über wichtige States.

![grafik](https://user-images.githubusercontent.com/45144344/102461697-0d9b3d80-4049-11eb-9bc3-3b05b4f0d101.png)

**Comment by sbormann** [comment]
Gute Idee. Ich notiere es mir. Aktuell bin ich aber zeitlich sehr eingeschränkt und die Liste ist schon ziemlich lang geworden, ich kann also nicht versprechen, dass das zeitnah klappt. Aber, schau mal im Forum, dslraser hat da ein paar gute Scripts veröffentlicht, die diese Funktion als Widget implementieren. Vielleicht hilft das schon mal weiter!? 
VG

**Comment by ToTXR4Y** [comment]
Keinen Stress, ich brauche das ganze nicht sofort und es war auch nur eine Idee. Wäre halt schön alles zentral im Adapter zu haben und nicht auf etwaige Scripts ausweichen zu müssen (wobei dslraser da wirklich tolle Sachen gemacht hat).

**Comment by siedi** [comment]
Gibt ja einige HTML-Tabellen-Beispiele im Forum. Allerdings suche ich da auch was, genau für die oben genannten Beispiel, was eher generisch ist.
Aktuell ich ich mal ein einfach Tabellen-Widget gebaut, das sich die Daten aus einem zu definierbaren Datenpunkt zieht. In diesem Datenpunkt müssen die Daten in einem Array vorliegen. Für Boolean-Werte kann man dann zwei Icons hinterlegen.

Sieht im Frontend in etwa so aus:

<img width="354" alt="Bildschirmfoto 2021-01-24 um 20 02 37" src="https://user-images.githubusercontent.com/4923159/105640586-26d0ae80-5e7f-11eb-8d01-11b3b77b2ab2.png">

Über die Widgetkonfiguration kann man die Darstellung etwas formatieren:
<img width="321" alt="Bildschirmfoto 2021-01-24 um 20 04 37" src="https://user-images.githubusercontent.com/4923159/105640648-6d260d80-5e7f-11eb-8212-f5902d7e2c81.png">

Leider muss man den Datenpunkt halt noch per Blockly generieren. Der Datenpunkt sieht so aus, wobei die Anzahl der Spalten variabel ist, d.h. man kann beliebig viele anhängen und ist nicht nur auf. 2 begrenzt. Als Datentyp wird aktuell nur Text und Boolean erkannt (Boolean für die Icons). Könnte man natürlich noch ausbauen....

```
[[true,"Lampe Wohnzimmer"],[true,"Lampe Tim"],[true,"Lampe Schrank"],[false,"Lampe Mila"],[false,"Lampe Leni"],[true,"Lampe Klavier 5"],[true,"Lampe Klavier 4"],[true,"Lampe Klavier 3"],[true,"Lampe Klavier 2"],[true,"Lampe Klavier 1"],[true,"Lampe Flur"]]
```

Würde auch gerne weg von diesen Blockly-Sachen. Bin mir aber grad noch nicht sicher, wie ich das Thema Widget und Auswahl von einzelnen Datenpunkten unter einem Hut bringe. Bin auch echt am überlegen, mal einen eigenen Adapter zu schreiben für sowas, denn auch der Device-Counter nutzt ja die gleiche Logik (bzw. umgekehrt).

**Comment by sbormann** [comment]
Wow, schon mal sehr cooler Ansatz, das als Widget zu machen! Stellst Du Deinen Quellcode zur Verfügung?

**Comment by siedi** [comment]
Ja, klar. Ist aber noch im sehr frühen Stadium, deshalb will ich es noch nicht im Forum posten.

Braucht noch eine externe JS-Lib (ist MIT Lizenz), um den DOM beim Change nicht komplett neu zu zeichnen (flackert sonst).
Hänge mal beide Dateien an. Vielleicht kommst Du damit zurecht.

Hätte da auch noch eine Frage / Bitte: Bei den Widget-Optionen in getWidgetSettings gibts den Typ "icon" noch nicht, wie bei dialogDeviceEditOptionsBuildOptionsContent. Das wäre cool für die Auswahl des Icons. Ist aktuell hardcoded.

Hab leider grad auch nicht so viel Zeit. Daher etwas on hold für die Woche.


[Archiv.zip](https://github.com/sbormann/ioBroker.iqontrol/files/5863008/Archiv.zip)

**Comment by sbormann** [comment]
Hi,

alles klar, ich kümmer mich um die Icon-Geschichte.

VG!

**Comment by sbormann** [comment]
@siedi Habe ``icon`` und bei der Gelegenheit auch gleich ``datapoint`` als types für widget-urlparameter implementiert.
Die neue Zeile für Dein Widget sieht dann so aus:
````
<meta name="widget-urlparameters" content="tableColumns/1/Split table in columns/number;iconOn/switch_on.png/Icon on/icon;iconOff/switch_off.png/Icon off/icon;datapoint//Datapoint/datapoint;font-family/verdana,tahoma,arial,helvetica,sans-serif/Font-Family/text;font-size/9/Font size in pt/number;text-color/rgb(0,0,0)/Text-Color/color;background-color/rgba(104,164,255,0)/Background-Color/color">
````

Damit der Pfad zum Icon richtig formatiert wird, nutze z.B. folgenden code:
````
var iconOn = getUrlParameter('iconOn') || './images/icons/switch_on.png';
if(iconOn.indexOf('http') != 0) iconOn = '/iqontrol/' + iconOn;
````

PS: Bei mir lief Dein Widget nicht - hat einfach nichts angezeigt. Ggf. liegt es an der dom-change js?
Wenn Du die einzelnen Felder in der Tabelle mit id`s ausstattest, kannst Du die auch mit purem js aktualisieren.

Also z.B. alle Tabellen-Felder (td) mit bekommen die ``id='tableRow_' + tableRow + '_tableCol_' + tableCol`` (tableRow / tableCol sind halt die entsprechende Zeile / Spalte der Tabelle.

Die Images bekommen zusätzlich die ``id='tableRow_' + tableRow + '_icon'``

Mit 
````
document.getElementById('tableRow_' + tableRow + '_tableCol_' + tableCol).innerHTML = "Mein neuer Text";
````
kannst Du dann entsprechend den Inhalt einzelner Tabellenfelder tauschen.

Mit 
````
document.getElementById('tableRow_' + tableRow + '_icon').src = iconOn;
````
hast Du Zugriff auf das Icon.

Viel Erfolg und danke fürs Entwickeln!!

**Comment by siedi** [comment]
Hey @sbormann 

danke für die Fixes und sorry für die späte Antwort. Hoffe, ich komme am WE wieder dazu weiter zu machen.

Ja, anscheinend hat die zusätzliche lib gefehlt. Ich wollte das über ein virtual dom regeln. Denn das Problem ist ja, dass sich das Tabelle-Array (also der Inhalt des Datenpunkts) beliebig ändert (einzelne Werte, neue "Zeilen" aber auch neue "Spalten". Und einfach nur die einzelnen Spalten / Felder zu überschreiben könnte nicht reichen, wenn sich die Tabelle eben grundlegend ändert. 

Und das nächste Problem ist, dass beim einfachen und ständigen Überschreiben ein Flickern entsteht. Müsste also prüfen, ob sich der Inhalt jeder einzelner Zelle bzw. auch die Spaltenanzahl geändert hat und nur dann das DOM updaten.

Werd noch ma verschiedene Varianten ausprobieren.

**Comment by siedi** [comment]
Hier mal eine neue Version des table-widgets. Es verwendet jetzt keine externe Lib mehr, sondern parsed tatsächlich jede Zelle und zeichnet die Spalten/Zeilen/Tabelle neu, wenn strukturelle Änderungen vorkommen. Letzteres ist noch nicht perfekt, d.h. wenn sich die Rows ändern, fehlen da noch die checks.


[status-table.html.zip](https://github.com/sbormann/ioBroker.iqontrol/files/6175972/status-table.html.zip)

**Comment by sbormann** [comment]
Hi @siedi ,
heute kam ich mal dazu, das Script zu testen. Schon mal sehr cool, wie das ganze jetzt läuft!
Zwei Dinge sind mir noch aufgefallen:
Im Part receive postMessages hat er bei mir das JSON.parse nicht gemacht, weil der Datenpunkt bereits als JSON geliefert wurde (vermutlich macht ioBroker das so, wenn die common.role des Datenpunkts "json" ist?). Habe es deshalb so abgewandelt:
````javascript
        //receive postMessages
        const receivePostMessage = (event) => { //event = {data: message data, origin: url of origin, source: id of sending element}
            if (event.data && event.data.command) {
                if (event.data.stateId && event.data.value && event.data.stateId === getUrlParameter('datapoint')) {
                    try {
						  var val = event.data.value.val;
						  if(typeof val == "string") val = JSON.parse(event.data.value.val);
                        if (Array.isArray(val)) {
                            buildTable(val)
                        }
                    } catch (e) {
                        console.log(e)
                    }
                }
            }
        }
````

Dann muss das JSON bei Dir zwangsweise ein zweidimensionaler Array sein. Aber an sich könnten es ja auch Objekte sein.
Für die Auswertung der Spalten habe ich das mal so umgeschrieben:
````javascript
                // iterate through columns
				var line = val[i];
				if(!Array.isArray(line) && typeof line == "object"){
					var lineArray = [];
					for(col in line){lineArray.push(line[col]);}
					line = lineArray;
				}
                for (let j = 0; j < line.length; ++j) {
                    let col = document.getElementById(`table_${tableCount}_row_${i}_col_${j}`)
                    if (!col) {
                        if (typeof line[j] === 'boolean') {
                            row.insertAdjacentHTML('beforeend', `<td id="table_${tableCount}_row_${i}_col_${j}" style="height:16px;"><img style="height:100%;" src="${line[j] ? iconOn : iconOff}"></td>`)
                        } else {
                            row.insertAdjacentHTML('beforeend', `<td id="table_${tableCount}_row_${i}_col_${j}" style="height:16px;">${line[j]}</td>`)
                        }
                    } else {
                        // need to check the content and type of the col and if changed, redraw col
                        let newContent = `${line[j]}`
                        if (typeof line[j] === 'boolean') {
                             newContent = `<img style="height:100%;" src="${line[j] ? iconOn : iconOff}">`
                        }
                        if (col.innerHTML !== newContent) col.innerHTML = newContent
                    }
                }
            }
            // todo: if we have more old rows, we need to delete them
        }
````


Ggf. kann man das ganze noch etwas verfeinern und auch auf die Zeilen übertragen.

Schön wären noch optionale Tabellenüberschriften.

Das ganze ist sicher eine großartige Entwicklung, vielen Dank dafür!

Wenn das alles fertig ist, könnten wir das doch fest in iQontrol als Widget einbauen, was meinst Du?

LG und schönen Sonntag noch!

**Comment by sbormann** [comment]
Listen und passende Widgets sind nun in der aktuellen Github-Version zum Testen online und werden mit der nächsten Version zur Verfügung stehen.
Danke für den Start-Schuss zu diesem Thema, der hier begonnen hat!
VG!
