### ISSUE TITLE
Hintergrundfarbe wählen

### ISSUE THREAD

**Issue by Melwindp** [sbormann/ioBroker.iqontrol#155]
Hallo,

wie kann ich den gesamten Hintergrund auf weiß einstellen? Nach einem der letzten Updates habe ich plötzlich den blau-lila Farbverlauf (ähnlich den iqontrol logo) bekommen. Bis jetzt habe ich die Einstellung aber nicht finden können.

VG

Mel

**Comment by sbormann** [comment]
Hallo,
dafür gibt es leider keine Option, das müsste direkt im CSS-File geändert werden.
Sorry!
