### ISSUE TITLE
All Colors dark

### ISSUE THREAD

**Issue by d1nd141** [sbormann/ioBroker.iqontrol#156]
Hello,

the initial problem with the old iqontrol version, already notified here
https://github.com/sbormann/ioBroker.iqontrol/issues/105
seems fixed.

But i have a new issue.
The Colors in the overview are  all dark. (please check attachments)
Cache & cookies cleared in browser.
Added a  second web adapter.
No error messages in Console, only warnings.
![image](https://user-images.githubusercontent.com/13020602/101464942-9d513580-393f-11eb-8d2f-402355a789eb.png)
![image](https://user-images.githubusercontent.com/13020602/101464953-a04c2600-393f-11eb-8929-70568da425f3.png)
![image](https://user-images.githubusercontent.com/13020602/101465488-4bf57600-3940-11eb-884c-46a32a0ad803.png)

![image](https://user-images.githubusercontent.com/13020602/101465205-f02aed00-393f-11eb-81c9-6ea9a3eea0d4.png)

**Comment by Qlink84** [comment]
same problem here. i've tried to completely remove/delete/reinstall iqontrol (1.5.2). Clear browser cache, delete cookies, use different browser... all color settings in adapter options are set to #000000 ...
Any idea how this can be fixed ? 
Maybe you can add a restore default settings button in adapter options which sets colors correctly if this bug/problem occurs?

**Comment by d1nd141** [comment]
I did not even change any colors.
This was a fresh install (actually, the old version was uninstalled before, restarted several times (due to other tasks)., But no color was changed in old version at all)

**Comment by kopierschnitte** [comment]
Same here but I've never used any previous version. So, absolutely fresh install!

**Comment by d1nd141** [comment]
I confirm, clicking the "X" on every color solved the problem.
Thanks sbormann!

**Comment by sbormann** [comment]
Should be - hopefully - fixed in 1.5.3
