### ISSUE TITLE
Symbolic link doesn't behave as link when device role is changed

### ISSUE THREAD

**Issue by s0m3body** [sbormann/ioBroker.iqontrol#158]
I have changed device role from Light to Switch in its 'native' view. This device is also linked from another view, as symbolic link.

In this other view, the device remained as 'Light' -> I had to delete it and re-link it again in order to get the role change 'propagated'.

**Comment by sbormann** [comment]
Oh, danach muss ich schauen. Danke für die Rückmeldung.

**Comment by s0m3body** [comment]
Wenn du irgendwelche Unterstützung brauchst /(ich bin selbst 
Entwickler)/, sag bitte bescheid.

Gruß,

Martin

**Comment by sbormann** [comment]
Hi, 

teste mal die aktuelle Github-Version, da sollte es jetzt funktionieren!

Hilfe nehme ich immer gerne an - je mehr das Projekt wächst, um so mehr wachsen auch die Ansprüche :) 

Ich muss mich lediglich noch einarbeiten in die Zusammenarbeit auf Github. Bin ja Laie und habe bislang nur als Einzelentwickler gearbeitet. Von Merges, Branches etc. habe ich noch keine Ahnung, aber das kann ja noch kommen.

VG und Danke!
