### ISSUE TITLE
Tuya LED-Stripe

### ISSUE THREAD

**Issue by sir0drake** [sbormann/ioBroker.iqontrol#161]
Hello,
i am bit lost of what to set at wich point,  to get the full advantage of my new color led-stripe.
right now i am only able to set power On/Off.
Also the different Scenes i am able to Change ( withe/colored/sczene/...)
but when i want to bring the color change / the brighness etc into the config,
nothing is working any more. because the squence the tuya app want to send
is not a valid squence.

As you can see in Screenshot there is only 1 DataPoint where all is to be set.
Color, Brightness etc...

my question is what do i have to set where in a Light-Device in iQontrol to bring 
the missing properties alive.

Thanks all

[Device RAW]
[led_stripe_raw.txt](https://github.com/sbormann/ioBroker.iqontrol/files/5791467/led_stripe_raw.txt)

[Device Screenshot]
![2021-01-09 18_13_59-objects - ioBroker](https://user-images.githubusercontent.com/77205165/104104156-a28b0280-52a6-11eb-81be-668963ee2ff7.png)

**Versions:**  
 - Adapter version: 1.5.5
 - JS-Controller version: 3.1.6
 - Node version: 12.20.1
 - Operating system: "Raspbian GNU/Linux 10 (buster)"

**Comment by sbormann** [comment]
Notiz für mich:
Tuya color_data format:
HHSSBB in Hex, 
HH: 0000-016d (0-365)
SS: 0000-03e8 (0-1000)
BB: 0000-03e8 (0-1000)

**Comment by sbormann** [comment]
Please try the actual github-version - HHSSBB for Tuya was added to ALTERNATIVE_COLORSPACEs
Please provide feedback, if it works.
Greetings

**Comment by sir0drake** [comment]
Sir,
i got following error by trying to upgrade from root.
brgds

Input: 
iobroker upgrade iqontrol@1.5.6

Output:
Would you like to upgrade iqontrol from @1.5.5 to @1.5.6 now? [(y)es, (n)o]: y
Update iqontrol from @1.5.5 to @1.5.6
NPM version: 6.14.10
npm install iobroker.iqontrol@1.5.6 --loglevel error --prefix "/opt/iobroker" (System call)
npm ERR! code ETARGET
npm ERR! notarget No matching version found for iobroker.iqontrol@1.5.6.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/iobroker/.npm/_logs/2021-01-19T16_15_45_057Z-debug.log

.....

**Comment by sbormann** [comment]
Please try updating from admin web-interface by clicking the cat-button in the adapters-tab. Then chose iQontrol. Afterwards perform an upload like described in the troubleshooting-section in the iQontrol-Readme.

**Comment by sir0drake** [comment]
Hi there,
the upgrade has taken place successfully.
The colors can now be selected without any problem.
many thanks for your help
Good work !
