### ISSUE TITLE
Color information/settings only loaded on the second attempt

### ISSUE THREAD

**Issue by gswdn** [sbormann/ioBroker.iqontrol#163]
Describe the bug
===========

I have some devices/lights in ioBroker/iqontrol, that allow setting their color. They are organized in a room.
Navigation is
* Home
* Rooms
   * Bedroom
   * Living Room
   * ...

*bottom nav bar*
![image](https://user-images.githubusercontent.com/52855342/104131333-08928b00-5376-11eb-98ab-ef3259d6e917.png)

*rooms tab*
![image](https://user-images.githubusercontent.com/52855342/104131344-10522f80-5376-11eb-9a22-c38f0dc79faa.png)

Reproduce
=======

1. Open icontrol with start-page url https://raspi:8082/iqontrol/index.html?namespace=iqontrol.0
2. Click on "Rooms" in bottom nav bar
3. Select a room. Bedroom in my case.

**Observed behavior (1)**
Color-Information / settings for some lights are not displayed:
![image](https://user-images.githubusercontent.com/52855342/104131009-2eb72b80-5374-11eb-8462-a3e5a7eba0a5.png)
Lights in this case are custom made ESP286 light strips controlled via ioBroker objects linked to MQTT topics.

4. Click "rooms" in bottom nav bar again
5. choose "bedroom" again

**Observed behavior (2)**
Color information/settings now are displayed:
![image](https://user-images.githubusercontent.com/52855342/104131052-5e663380-5374-11eb-9953-614f4ed32c26.png)

Expected behavior
============
Color Information and settings should be displayed on the first attempt. See screenshot "observed behavior (2)"

Versions:
======
 - Adapter version: 1.5.5
 - JS-Controller version: 3.1.6
 - Node version: 10.23.1
 - Operating system: Raspbian GNU/Linux 10 (buster)

**Comment by DcFamas** [comment]
Hey, the issue is already opened in case #153.

**Comment by gswdn** [comment]
Damn! Yes. Really sounds like my issue.
Sorry for not reading the existing list.
I guess, we can close this one here, or?
Sorry that it seems to be a never ending story for you.
But thank you anyway for this great ioBroker adapter. I really enjoy it.

**Comment by sbormann** [comment]
Hi,
bitte mal mit der aktuellen Github-Version testen. Ich hoffe, es geht jetzt!
Bitte um Rückmeldung.
VG!

**Comment by gswdn** [comment]
Hi!
Finally found the time to update test ... thank you so much. Works now!
Have a fantastic weekend!
