### ISSUE TITLE
Adapter starten

### ISSUE THREAD

**Issue by Matt77CHE** [sbormann/ioBroker.iqontrol#164]
Guten Morgen
Ich wollte eigentlich diesen Adapter nutzen - da VIS wirklich nicht der Brüller ist.

Nun habe ich den Adapter installiert; die Hinweise mit https im admin und im web befolgt (beide auf https) und socket.IO auf integriert und bei nur web-sockets ist kein Häckchen.
Mein Problem nun ist, dass ich seit etwa einer Stunde warte und folgenden Screen sehe:
![iqontrol](https://user-images.githubusercontent.com/73795309/105018565-73625700-5a45-11eb-9a8f-c82dd0c331d3.jpg)

Dauert das so lange, bis er die Daten und Objekte geladen hat?

Ich habe mal versucht, den web nicht auf https zu stellen - Da kam zwar eine Meldung diesbezüglich, aber als ich diese mit ok bestätigt hatte, konnte ich dann trotzdem auf die Adapter-Oberfläche und mit Einstellungen beginnen...... was mir komisch vorkommt.

Ich habe den iobroker vor einer Woche neu aufgesetzt, Adapter; Node etc sind aktuell.
Sonst laufen alle instanzen sauber und gut.

Im Log habe ich dies stehen:

> 
iqontrol.0 | 2021-01-19 11:07:58.342 | info | (3974) state iqontrol.0.info.connection changed: true (ack = true)
-- | -- | -- | --
iqontrol.0 | 2021-01-19 11:07:58.335 | info | (3974) iQontrol ready.
iqontrol.0 | 2021-01-19 11:07:58.335 | info | (3974) Deleting unused Objects...
iqontrol.0 | 2021-01-19 11:07:58.334 | info | (3974) Creating Widget States...
iqontrol.0 | 2021-01-19 11:07:58.283 | info | (3974) Creating Popup States...
iqontrol.0 | 2021-01-19 11:07:58.272 | info | (3974) starting. Version 1.5.0 in /opt/iobroker/node_modules/iobroker.iqontrol, node: v12.20.1, js-controller: 3.1.6

Hat jemand eine Ahnung wo das Problem liegt?
Danke & Grüsse
Matt

**Comment by sbormann** [comment]
Bitte schick mal ein Log von der Entwicklerkonsole des Browsers bei Öffnen der Einstellungen (also nicht das Log aus ioBroker, sondern aus dem Browser, so wie hier beschrieben:

https://github.com/sbormann/ioBroker.iqontrol#troubleshooting


VG

**Comment by sbormann** [comment]
Bitte schick mal ein Log von der Entwicklerkonsole des Browsers bei Öffnen der Einstellungen (also nicht das Log aus ioBroker, sondern aus dem Browser, so wie hier beschrieben:

https://github.com/sbormann/ioBroker.iqontrol#troubleshooting


VG

**Comment by Matt77CHE** [comment]
....Also;
Habe das Ganze mit dem Firefox und dem Opera Browser versucht - hier die Ergebnisse:

![firefox](https://user-images.githubusercontent.com/73795309/105048378-cb13b900-5a6b-11eb-9844-9ad8f4875226.jpg)

![opera](https://user-images.githubusercontent.com/73795309/105048405-d535b780-5a6b-11eb-8aa2-c2065bc61484.jpg)

Das mit dem "Klick the line Number" hat bei mir nicht funktioniert; sah auch etwas anders aus...
Das mit dem "Maus over the Error" konnte ich auch nirgens finden.

**Comment by Matt77CHE** [comment]
wenn ich auf den index rechts klicke, komme ich auf die Adapter website.

**Comment by sbormann** [comment]
Hi, kann es sein, dass der web-Adapter mit https und der Admin-Adapter mit http läuft?
Dann installiere einen weiteren web-Adapter, der auch auf http läuft. Sowohl Admin, als auch ein Web-Adapter müssen im gleichen Modus laufen.

**Comment by Matt77CHE** [comment]
Hallo;
nope:

![admin](https://user-images.githubusercontent.com/73795309/105072015-9ca2d780-5a85-11eb-80ed-73d800ba4c54.jpg)

![web](https://user-images.githubusercontent.com/73795309/105072049-a9bfc680-5a85-11eb-94ac-2f64911c0178.jpg)

**Comment by Matt77CHE** [comment]
mit der Authentifikation habe ich auch schon rumgetüftelt - nichts

**Comment by Matt77CHE** [comment]
Ich habe jetzt auch mal einen zweiten web adapter installiert.
einer steht auf https; einer auf http. Mit admin adapter auf https versucht - geht nicht. Mit admin adapter auf http versucht - geht auch nicht.

**Comment by Matt77CHE** [comment]
Guten Morgen
Schade, dass dieser Adapter nicht läuft - sah eigentlich vielversprechend aus...

**Comment by Matt77CHE** [comment]
Arbeitet man noch an einer Lösung?

**Comment by sbormann** [comment]
Ich habe leider im Moment keine Idee, wo das Problem stecken könnte. CORS-Policy-Fehler treten auf, wenn man domainübergreifend arbeitet - bei ioBroker ist dies meist durch unterschiedliche Protokolle (http / https) der Fall. Aber das hast Du ja schon ausgeschlossen. 

Gibt es irgendwas besonderes an Deiner Konfig? Alles auf dem neuesten Stand (npm, js-controller, web-adapter, socket-io)? Ggf. mal den ioBroker-Installations-Fixer laufen lassen? Neustart wirst Du ja vermutlich schon versucht haben, oder?

**Comment by Matt77CHE** [comment]
ja, Neustart habe ich schon etliche hinter mir.
Wäre ja zu schön gewesen...

**Comment by Matt77CHE** [comment]
Socket io : 3.0.13
Node.js : v12.20.1
NPM : 6.14.10
WEB : 3.1.0

**Comment by sbormann** [comment]
Sind das die aktuellen Versionen? Ich hab die nicht im Kopf.

**Comment by sbormann** [comment]
Könntest Du das ggf. auch im Forum posten? Da wird von mehreren Leuten supported. Ggf. hat da noch einer eine Idee, ich bin ehrlichgesagt ratlos.
https://forum.iobroker.net/topic/22039/test-adapter-iqontrol-1-5-x

**Comment by Matt77CHE** [comment]
Ok, danke trotzdem schon mal - Ich habe es soeben noch ins andere Forum reingestellt...
