### ISSUE TITLE
Warnung nach Update des Adapters ver. 1.5.6

### ISSUE THREAD

**Issue by AlfredSch** [sbormann/ioBroker.iqontrol#165]
Hallo zusammen
Nach dem Update auf die ver. 1.5.6 bekomme ich eine Warnung im Log.
 
State "iqontrol.0.info.connection" has no existing object, this might lead to an error in future versions

Was muss ich anpassen?
Gruss
Fred

**Comment by sbormann** [comment]
Hi,
danke für den Hinweis, werde mich drum kümmern und im nächsten Update beheben. Brauchst erst mal nichts unternehmen, das ganze hat aktuell keine negativen Auswirkungen auf das System. 
VG!
