### ISSUE TITLE
State "iqontrol.0.info.connection" has no existing object

### ISSUE THREAD

**Issue by ToTXR4Y** [sbormann/ioBroker.iqontrol#166]
Beim starten des Adapters kommt es zu folgendem Warn-Eintrag im Logfile (JS Controller 3.2.8):
State "iqontrol.0.info.connection" has no existing object, this might lead to an error in future versions

- Behebung:
Einen passenden State im Strukturbaum des Adapters anlegen.

**Comment by sbormann** [comment]
Duplicate of #165 
Danke für den Hinweis! VG
