### ISSUE TITLE
Iqontrol Views werden nicht geladen

### ISSUE THREAD

**Issue by hetti72** [sbormann/ioBroker.iqontrol#167]
**Describe the bug**  
Seit ein paar Tagen habe ich auf verschiedenen Geräten das Problem das Iqontrol nicht geladen wird. Wenn ich die Startseite aufrufe wird lediglich der Hintergrund und leere Kacheln angezeigt, in der Mitte ist nur die Ladeanimation zu sehen. 
In der Entwicklerconsole ist immer der gleiche Fehler zu sehen. 
Nach mehrfachem Browser Reload wird die View dann geladen und alles funktioniert wie gewohnt. 

Meine Konfig:
Socket io : 3.0.12
Node.js : v12.20.0
NPM : 6.14.8
WEB : 3.2.0
Admin : 4.1.11
iqontrol : 1.5.5

![iqontrol1](https://user-images.githubusercontent.com/54002469/105814448-b8d8d400-5fb1-11eb-87ce-349d7963d95f.jpg)
![iqontrol3](https://user-images.githubusercontent.com/54002469/105814450-b9716a80-5fb1-11eb-8c78-9b4f97ab54ba.jpg)
![iqontrol2](https://user-images.githubusercontent.com/54002469/105814454-b9716a80-5fb1-11eb-9fff-6de168c0a039.jpg)

**Comment by sbormann** [comment]
Versuch mal bitte die aktuelle Github-Version, ob es jetzt klappt.

**Comment by hetti72** [comment]
Sieht gut aus mit der aktuellen Version 1.5.7 von Github. 
Ich konnte das Problem zumindest auf die schnelle nicht mehr nachstellen. Ich werde im laufe des Abends weitere Tests machen.

**Comment by hetti72** [comment]
Problem ist gelöst. Vielen Dank für den schnellen Support
