### ISSUE TITLE
Can't have web adapter at different url

### ISSUE THREAD

**Issue by tim3trick** [sbormann/ioBroker.iqontrol#168]
After installing the adapter I'm stuck with the spinners:
![image](https://user-images.githubusercontent.com/6930853/106619155-90804500-6570-11eb-9bcd-5a3fdc682f3c.png)
 (Dark Reader is on).

The reason for this is that I use custom DNS entries for my smarthome, e.g. iobroker sits at http://iobroker.asgard and my web adapter listens on http://smarthome.asgard . This is done with traefik, docker and a pi-hole as DHCP & DNS Server.
Calls are visible in the dev tools:
![image](https://user-images.githubusercontent.com/6930853/106619509-f53b9f80-6570-11eb-8ff8-43a4f1e46e4f.png)

We can safely ignore the CORS error, because there is no webserver under given domain & port anyway. 
Everything is on its own domain at Port 80 (until I find the time to lets-encrypt everything...)

Can you please add the possibility to define the URL of the web-adapter prior to connecting?

(CORS i can fix myself, this is just some traefik labeling) 

Kind regards,
tim3trick

**Comment by sbormann** [comment]
Hi,
you seem to have good knowledge. Any idea, how to achieve this? Do you have example-adapters where this is done?

**Comment by sbormann** [comment]
Still waiting for feedback, so i think this topic might not be acutal any longer. Therefore i will close it for now. If you need any further assistance, please feel free to reopen it! Best regards
