### ISSUE TITLE
Click on Tile doesn't work

### ISSUE THREAD

**Issue by Jibbonator** [sbormann/ioBroker.iqontrol#169]
**Describe the bug**  
If i click on the Tile instead of the Symbol nothing happens. No matter if i set to open a dialog or execute command.
Click on Symbol works fine.

**To Reproduce**  
Go to a Tile and click on it.

**Expected behavior**  
Either the command is executed oder dialog should open.

**Screenshots & Logfiles**  
Screenshot not helpful because nothing happens.
Nothing on log when i click the tile. Log set to debug on instances.

**Versions:**  
 - Adapter version: 1.5.7
 - JS-Controller version: 3.2.13
 - Node version: 12.20.1
 - Operating system: PiOS

**Additional context**  
I had to Restore my iobroker yesterday from mini backup and updated from an older version.
Don´t know which exactly.

**Comment by sbormann** [comment]
Hallo,

bitte die folgenden Schritte durchführen. Bei weiteren Problemen bitte vor allem den 2. Absatz beachten, hier wird beschrieben, wie man ein Log des Fehlers erzeugt und welche Screenshots für die weitere Analyse notwendig sind:

https://github.com/sbormann/ioBroker.iqontrol#troubleshooting

Vielen Dank!

**Comment by sbormann** [comment]
Hi,

im answering in german, if you need an englisch answer, please write me again!

Ich kopiere hier mal einen Beitrag aus dem Forum, da wurde gerade eine ähnliche Frage gestellt:

@sebi85 sagte in [Test Adapter iQontrol 1\.6\.x Vis](/post/586950):
> Hallo @s-bormann ,
> 
> bei mir funktionieren seit der Version 1.6 die "Popup" Geräte nicht mehr. Beim Klick auf das Icon wird das Popup nicht mehr geöffnet.
> 
> Ich habe die "Additional Infos" und "URL" gesetzt und normalerweise (d.h. < 1.6) hat sich dann beim Klick auf das Icon ein Popup mit den entsprechenden Daten geöffnet.
> 
> Sofern ich nun "lange" auf das Icon klicke öffnet sich ein kleines Popup wo ich dann "Eigenschaften" auswählen kann. Anschließend öffnet sich das "reguläre" Popup mit den gewünschten Informationen. Mir scheint es so, als würde er durch einen normalen Klick die Geräteeigenschaften nicht mehr öffnen.
> 
> Bei anderen Gerätearten (z.B. Thermometer) funktioniert das Klicken um den Dialog zu öffnen immer noch.
> 
> Wurde hier in dem Bereich etwas geändert bzw. hat jemand ein ähnliches Problem?
> 
> Ich verwende den google Chrome Browser.
> 
> Danke und viele Grüße,
> Sebastian

Hallo,
ja, da wurde tatsächlich in der 1.5.7 mit Hilfe von @siedi etwas geändert und besser konfigurierbar gemacht:
* (siedi) Added option clickOnTileOpensDialog to all devices. The logic is now:
    * If clickOnTileToggles is true => toggle
    * else if clickOnTileOpensDialog is true => open dialog
    * else if linked view is given => open link to view
    * else do nothing

Es gibt zwei Optionen, die für Dich interessant sein könnten:
![d2685c65-8205-4211-a6e5-f61a159a4d08-image.png](/assets/uploads/files/1614113148280-d2685c65-8205-4211-a6e5-f61a159a4d08-image.png) 

Bitte teste das mal und gib Rückmeldung, ob das den gewünschten Effekt hatte.

VG!

Bitte um kurze Rückmeldung, ob das Issue damit geschlossen werden kann.

**Comment by Jibbonator** [comment]
Mit den Einstellungen habe ich schon rumgespielt, das hat bei mir leider keinen Unterschied gemacht. ich habe habe eine Lösung gefunden. Ich habe ein Homematic Thermostat das aktuell mit meiner Homematic nicht verbunden ist, also offline ist. Sobald ich das in die Übersicht rein nehme, funktioniert das nicht mehr.
Kann das jemand bestätigen?

**Comment by sbormann** [comment]
Hallo, ist das ganze immer noch aktuell? Dann bitte noch mal eine kurze Rückmeldung geben. 
PS: Im Forum wird sich sehr aktiv von vielen Leuten beteiligt, hier wäre das ganze ggf. besser aufgehoben, weil man von mehreren Feedback bekommt. Denk mal drüber nach, das ganze dort hin zu verlagern: https://forum.iobroker.net/topic/22039/test-adapter-iqontrol-1-7-x-vis/
VG

**Comment by Jibbonator** [comment]
Mahlzeit.
Da sich das Problem bei mir nicht mehr zeigt, würde ich sagen es hat sich erledigt
