### ISSUE TITLE
ALTERNATIVE_COLORSPACE_VALUE setzt die Farbe neu beim starten von iQontrol

### ISSUE THREAD

**Issue by DcFamas** [sbormann/ioBroker.iqontrol#170]
**Describe the bug**  
Hallo Sebastian,
vielen Dank, dass du in [https://github.com/sbormann/ioBroker.iqontrol/issues/153](153) das Problem mit der alternativen Farbe gelöst hast. Leider habe ich seitdem zwei Probleme:

1. Der Ladebalken wird extrem lange angezeigt wenn auf die Ansicht gewechselt wird:
![grafik](https://user-images.githubusercontent.com/35306967/107207771-00734d00-6a01-11eb-8434-0bf636095915.png)

2. 
- ich stelle die Farbtemperatur ein und schließe iQontrol
- ich starte iQontrol in der Standardansicht (nicht die Ansicht inder sich die Lampe befindet)
- daraufhin wird die zuletzteingestellte Farbe gesetzt (bspw. Blau)

das lässt sich beliebig mit jeder Farbe und Farbtemperatur einstellen.

**Versions:**  
 - Adapter version: 1.5.5
 - JS-Controller version: aktuellste
 - Node version: aktuellste
 - Operating system: Debian

Danke für deine kommende Hilfe! :)

**Comment by sbormann** [comment]
Hi, sorry, hat lange gedauert. 
Zu 1.: Kommt der Ladebalken schon beim Öffnen der Seite? Wie genau ist die Konfiguration Deines Gerätes (welche Datenpunkte nutzt Du)?
Zu 2.: D.h. beim Start von iQontrol - selbst wenn nicht die Seite mit der Lampe geöffnet wird - stellt sich das ganze von weiß wieder auf Farbe? 

Oooh mann, ich glaube, in diesem Leben schaffe ich es einfach nicht mehr, alle Bugs aus dem Farbteil zu entfernen, kaum fixt man ein Problem, kommt irgendwo ein neues her!

Wie gesagt, schick mir mal bitte Deine Konfiguration, dann kann ich es vielleicht nachstellen. In meiner aktuellen Test-Konfiguration läuft nämlich tats. im Moment alles, wie gewünscht...

LG

**Comment by DcFamas** [comment]
Hey Sebastian,
kein Problem. Ich habe mir in der Zwischenzeit aber einfach zwei Lidl Glühbirnen über Zigbee gekauft.
Magst du die zwei Yeelight Glühbirnen dann zugeschickt haben zum ausprobieren/behalten?

Grüße

**Comment by sbormann** [comment]
Vielen Dank, die Lampen sind inzwischen da, sobald ich dazu komme, werde ich mal damit mal experimentieren. VG!!

**Comment by sbormann** [comment]
ALTERNATIVE_COLORSPACE wurde geupdated, ich hoffe, der Fehler ist damit behoben. Noch mal vielen Dank für das Zusenden der Lampen! LG!!
