### ISSUE TITLE
Zugriffsrechte für verschiedene Etagen und Tabs ist das möglich

### ISSUE THREAD

**Issue by Sirbuschi2003** [sbormann/ioBroker.iqontrol#172]
Guten Tag,

Ist es möglich Iqontrol so einzustellen das man eine Instanz für mehrere Etagen mit verschiedenen Zugriffsrechten nutzten kann. 
Das heißt ich habe einen IoBroker mit einer Iqontrol Instanz und möchte aber, dass das Tab im EG die Sachen aus dem KG oder DG nicht sieht. Aber das Tab im KG z.b alles sieht. Ist sowas möglich wie setzte ich sowas um. Danke

**Comment by sbormann** [comment]
Hi,
nein, mit einer Instanz ist das nicht möglich. Du könntest aber mehrere iQontrol-Instanzen anlegen. Die Konfig kann man ja relativ einfach von einer Instanz exportieren und in die anderen importieren. Dann kannst Du in jeder Instanz das löschen, was Du nicht haben möchtest und rufst dann von jedem Tablet die entsprechende iQontrol-Instanz auf.

Sicher ist das ganze aber nicht, denn die Instanzen unterscheiden sich ja nur über die URL. Man könnte von jedem Tablet natürlich auch die nicht gewünschten Instanzen aufrufen. Eine Nutzerverwaltung oder so etwas gibt es nicht.
VG!

**Comment by sbormann** [comment]
PS: Ggf. die Frage noch mal im Forum stellen, vielleicht hat da einer eine gute Idee, wie man das "basteln" könnte:
https://forum.iobroker.net/topic/22039/test-adapter-iqontrol-1-6-x-vis
