### ISSUE TITLE
Add vibration sensor as a device?

### ISSUE THREAD

**Issue by Sundancer78** [sbormann/ioBroker.iqontrol#173]
Is it possible to include the vibration sensor in the device selection?

**Comment by sbormann** [comment]
Shure. What exactly is needed (which datapoints does a vibration sensor provide)? I have none here, so i don't know. Maybe you can send a screenshot of the datapoints your device offers.

**Comment by Sundancer78** [comment]
Are these data points enough?

![VibSensor](https://user-images.githubusercontent.com/42901216/110182644-75be1c00-7e0d-11eb-90f7-965f7c97d806.png)

**Comment by sbormann** [comment]
I think, you could use the motion-sensor device for that:
Set vibration as STATE and use another icon should do the job.
Or do you need any further functionality?
PS: good icons can be found on icons8.de

**Comment by sbormann** [comment]
I assume, it is working now, therefore i close the issure now. If you need any further help, please reopen the issue at any time. Greetings!
