### ISSUE TITLE
Kachel wird nicht aktiv wenn bedingungswert 0 ist

### ISSUE THREAD

**Issue by hetti72** [sbormann/ioBroker.iqontrol#174]
**Describe the bug**  
Unter "bedingungen für eine aktive Kachel" funktioniert die prüfung "ist kleiner" bzw. "ist kleiner oder gleich nicht"  wenn der zu prüfende Wert 0 ist. Wenn z.b. "kleiner oder gleich 3" eingestellt wird, ist die Kachel aktiv wenn der zu prüfende Datenpunkt den Wert 3 oder 2 oder 1 hat. Ist der Wert des Datenpunkt 0, ist die Kachel nicht mehr aktiv.
Ich benutze diese Funktion mit dem Trashschedule adapter und prüfe auf den DP "days left". 

**To Reproduce**  
1. erzeuge einen beliebigen DP als Zahl und setze ihn auf 1
2. setze in einer beliebigen kachel die "aktiv prüfung" auf den erzeugten DP und die bedingung auf "kleiner oder gleich 1"
3. Die kachel ist nun aktiv
4. ändere den wert des erzeugten DP auf 0
5. die kachel ist nun nicht mehr aktiv

**Expected behavior**  
Die Kachel ist auch aktiv wenn der zu prüfende DP den Wert 0 hat

**Versions:**  
 - Adapter version: 1.6.2 (funktionierte  auch schon in der 1.5.7 nicht)
 - JS-Controller version: 3.1.6
 - Node version: 12.20.0
 - Operating system: Linux container

**Comment by sbormann** [comment]
Bestätigt, Fix kommt heute Abend! Danke für die Meldung!

**Comment by sbormann** [comment]
Sorry, bin gestern doch auf der Couch eingeschlafen :)
Jetzt ist der Fix aber online. VG!
