### ISSUE TITLE
Betr: Version Adapter Ver. 1.6.5

### ISSUE THREAD

**Issue by newcompuhelp** [sbormann/ioBroker.iqontrol#176]
Nach dem Update des Adapters wird die Startseite doppelt dargestellt, es werden auch die
Daten doppelt geladen!
Anbei ein Screenshot - Josef Seekatz
![qiontrol](https://user-images.githubusercontent.com/44464061/111914888-2ebe6080-8a74-11eb-9e7b-963d626bb13b.JPG)

**Comment by sbormann** [comment]
Danke für die Nachricht, Fix ist online. VG!
