### ISSUE TITLE
Lumary-LEDs RGB Auswahl

### ISSUE THREAD

**Issue by snaggo** [sbormann/ioBroker.iqontrol#177]
Hey, vorab, ich bin ein totaler Anfänger was ioBroker etc. angeht.
Ich möchte simpel Gesagt meine Geräte, hauptsächlich Lampen und LED-Strips von Lumary, die ich normalerweise über Alexa steuere, über ein Webinterface steuern, welches ich auf dem Tablet aufrufen kann. Das automatische erstellen der Geräte aus dem Alexa2.0 Adapter klappt soweit ganz gut, An/Aus und Dimmen wird erkannt. Funktioniert auch alles.
Problematisch wird's bei der Farbauswahl. Hier funktioniert leider nichts, egal was ich bei HUE oder ALTERNATIVE_COLORSPACE_VALUE angebe. 

Soweit ich herausfinden konnte, gibt es drei states für die Farbe, allerdings tut nur einer davon was.
Es gibt einmal "color-hue", "colorName" und "colorRGB". color-hue und colorName kann man ändern wie man möchte, die Farbe des Strips wechselt aber nur durch ändern von colorName, dabei ändern sich dann auch automatisch die Werte der anderen beiden States. Hier habe ich nur noch nicht herausgefunden, wie ich das in iQontrol einstelle.

Hier die states des Geräts:
![image](https://user-images.githubusercontent.com/82290536/114284821-e67ed680-9a52-11eb-8470-39daa9390ddf.png)

Falls noch was benötigt wird, lass es mich gerne wissen, reiche ich umgehend nach.
Bin für jede Hilfe dankbar!!

 - Adapter version: 1.6.1
 - JS-Controller version: 3.2.16
 - Node version: 12.22.1
 - Operating system: linux debian

**Comment by sbormann** [comment]
Hi, hmm, das ist natürlich irgendwie doof, da man ja mit Farbnamen sehr beschränkt ist in seiner Auswahl. Mit Schiebereglern bekommt man das ganze dann nicht hin. Möglich wäre es jedoch über eine Value-List, die Du z.B. über die ADDITIONAL_CONTROLS einbinden könntest.
Gibt es denn einen Adapter für die LEDs für ioBroker? So dass man nicht auf die Alexa-Datenpunkte angewiesen ist?

**Comment by sbormann** [comment]
PS: Im Forum gibt es eine aktive Gemeinschaft, vielleicht weiß hier jemand was mit den Strips anzufangen? https://forum.iobroker.net/topic/22039/test-adapter-iqontrol-1-7-x-vis/

**Comment by sbormann** [comment]
Falls es noch weitere Probleme gibt, bitte erneut melden.
