### ISSUE TITLE
iqontrol startet nicht mehr nach Admin Aktualisierung auf 5.03.

### ISSUE THREAD

**Issue by spidermike-74** [sbormann/ioBroker.iqontrol#180]
heute den Admin Adapter update auf 5.03. gemacht seitdem komme ich nicht mehr auf den Iqontrol Adapter.
VIS Anzeige auf dem Tablet funktioniert, komme halt nicht mehr zu den Einstellungen.

**Comment by RudiXXL** [comment]
bei mir ladt die Adapter Einstellungsseite seit Update auf Admin 5.0.3 beständig neu ohne das man Einstellungen tätigen kann... Bei Downgrade auf Admin 4.2.1 stable funktioniert alles wieder einwandfrei.

**Comment by sbormann** [comment]
Bestätigt. Lösung ist in Arbeit. Sorry dafür.

**Comment by sbormann** [comment]
Fix ist online (v1.7.1). Dateien und Ordner umbenennen geht aktuell zwar noch nicht, das wird aber mit der nächsten Admin-Version dann auch wieder gehen. Danke für die Rückmeldungen!
