### ISSUE TITLE
Can't create folder in adapter

### ISSUE THREAD

**Issue by algar42** [sbormann/ioBroker.iqontrol#182]
**Describe the bug**  
It is not possible to create any folders in adapter. I can only see the root '/' folder and 'Create folder' button does nothing:
Is it known bug? 

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/40002726/117068057-74d53800-ad33-11eb-8205-ce2c259be80d.png)

**Versions:**  
 - Adapter version: 1.8.0
 - JS-Controller version: 3.2.7
 - Node version: 12.22
 - Operating system:  linux

**Comment by sbormann** [comment]
What is your admin-adapter version?
Are there error messages in the browser log?
(See here how to get the logs: https://github.com/sbormann/ioBroker.iqontrol#troubleshooting )

**Comment by algar42** [comment]
Hello!
Admin version is 5.0.14. 
No there are no any errors in the adapter log.. Actually there is nothing at all is written to the console when I try to create folder.

![image](https://user-images.githubusercontent.com/40002726/117107269-fe175980-ad89-11eb-9e4e-952f374d5111.png)

Can this happen because I'm using Redis DB for states and objects?

**Comment by alternative4** [comment]
same issue for me

**Comment by algar42** [comment]
with old UI the behavior  is the same... not able to see any folders except '\' root folder and it is not possible to create any folders :(

**Comment by sbormann** [comment]
5.0.19 has a yet unsolved bug that prevents iqontrol to open. bluefox worx on a fix. Please try 5.0.15 (sorry, i should have mentioned that before).

**Comment by alternative4** [comment]
> @alternative4 Do you use redis as well?
> 
> Could you please try the new react-ui? (Go to Instances > Admin open settings and activate react. Then Reload the browser-window). Does it work here?

Yes, I use redis as well. Admin version is 5.0.14. Tried React UI - it doesn't work there either.

**Comment by sbormann** [comment]
Posted it in forum:
https://forum.iobroker.net/post/627910

**Comment by sbormann** [comment]
Ist das noch aktuell? Oder hat sich durch die vielen Updates in der letzten Zeit die Situation gebessert?

**Comment by algar42** [comment]
Yes, it's still relevant. Please take a look at the screen recording:
![iqontrol_folder](https://user-images.githubusercontent.com/40002726/128817374-d6fb8dc0-ebba-486d-8cd5-d31cadfc714c.gif)

Here is what I see in the browser console (actually it does not report anything during folder creation):
![image](https://user-images.githubusercontent.com/40002726/128818416-25b82c43-9559-432c-ad48-c2d0cd3b13f7.png)


IQONTROL: 1.8.2 
JS-CONTROLLER: 3.3.13
NODE.JS: V12.22.1

**Comment by sbormann** [comment]
Can you upload images? Or is it only the folder-creation? Whats if you try to use the "Files" Tab of admin, can you see the iqontrol.meta folder here? (You need to switch to expert settings):
![image](https://user-images.githubusercontent.com/49171332/129443386-020e65c4-d1a8-4505-ba54-d3a2c60a826f.png)

**Comment by algar42** [comment]
When I upload image in iQontrol it works for root folder:
![image](https://user-images.githubusercontent.com/40002726/129444362-e06fe8ca-564a-43a6-b28e-d97480593f98.png)
In this case uploaded image appears in "Files" in 'userimage' folder:
![image](https://user-images.githubusercontent.com/40002726/129444397-07b4c313-ef01-49b8-a56b-a29dec76c70f.png)

I can create folder from "Files" and upload image there:
![image](https://user-images.githubusercontent.com/40002726/129444421-c02ccf68-7732-46c3-8189-e87379b2b9f6.png)
But this folder is not visible in iQontrol interface:
![image](https://user-images.githubusercontent.com/40002726/129444443-b38b8c50-38a1-425a-aa95-4a2b5ca38076.png)

**Comment by algar42** [comment]
and, btw, there are no any default files/folder in iQontrol.meta.. I don't know why.

**Comment by sbormann** [comment]
Could you please try with actual github version of iqontrol and report if it works better now?

**Comment by algar42** [comment]
Hmm.. did a fresh install, i.e. completely deleted previous instance and adapted and installed it again from Git. 
Now I can't see iqontrol.meta folder in "files", i.e. it does not created by adapter after install:
![image](https://user-images.githubusercontent.com/40002726/129449006-3b9a7b17-1ce1-4ea4-92a9-7aba1670c7e7.png)

I still can't create folders/see folders from iqontrol interface. Behavior is absolutely the same as before - I can only upload image to the root "/" folder in which case it again appears in /userimages folder in "files":
![image](https://user-images.githubusercontent.com/40002726/129449144-ffc2561f-99ec-4e9b-8b2d-b2fd1218f9b3.png)

Additionally a strange /userimagesnull folder is created. :)

**Comment by sbormann** [comment]
...userimagesnull - very strange.

Could you please try again with the actual github version? I updated the createDir-Function and added an error message. Maybe that helps us discover the problem.

**Comment by algar42** [comment]
yoohoo... it works :)
Than you!!!!

![image](https://user-images.githubusercontent.com/40002726/129453226-e828dfd3-ea2c-4648-bece-aa815b97e3ba.png)

**Comment by sbormann** [comment]
That makes me happy! Thank you for your feedback!!
