### ISSUE TITLE
einstellungen 

### ISSUE THREAD

**Issue by sjfm-design** [sbormann/ioBroker.iqontrol#185]
admin 5.0.18 kommt nur mehr fehlermeldung: **can not read file not exist**
kein bearbeiten mehr möglich. admin 5.0.15 alles in ordnung.

**Comment by sbormann** [comment]
Bestätigt. Bekomme aber keine Fehlermeldung im Log. Habe das ganze als Issue im Admin-Adapter weitergegeben.

**Comment by sbormann** [comment]
Bluefox hat angekündigt, dass es mit der 5.0.21 wieder gehen soll. Hoffen wir das Beste :)

**Comment by sbormann** [comment]
Bei mir funktioniert mit der 5.0.21 wieder alles. Falls noch Probleme bestehen, bitte noch mal melden. VG!
