### ISSUE TITLE
Port für Webinterface ändern?

### ISSUE THREAD

**Issue by funboxbolzer** [sbormann/ioBroker.iqontrol#186]
Hallo,

kann man den Port für das Webinterface ändern? Ich würde gerne per mit DNS von extern zugreifen, jedoch ist 8082 ja nicht so zu empfehlen für die freigabe.
Dankeschön.
Klaus

**Comment by sbormann** [comment]
Hi, ich habs zwar nie selbst ausprobiert, aber theoretisch musst Du nur den Port im Webadapter ändern. Falls es nicht klappt, bitte einfach noch mal melden. VG
