### ISSUE TITLE
Dimmer value shows "off"

### ISSUE THREAD

**Issue by louisvangeldrop** [sbormann/ioBroker.iqontrol#188]
Switching off a dimmable lightbulb shows "off" in the level-info field

I am using a dimmable light-bulb and set state value to "on/off" state switch.

I set the "level" field to the dimmer value field. Value range 0-255. ( I don't know how to change this into a range 0-100% using the IQontrol linkeddevice ).

The Light-widget properly shows the proper dimmer value and the light symbol is on.

When I switch the lamp off, the dimmer value changes into "off". I wonder: is this correct? and if so can I change the "off" into another text?

**Comment by sbormann** [comment]
Hi, this behaviour is as expected (feature, no bug :) ).
You could try to change the text by adding a value-list where key 0 gets the value you like ("0%") - but i have not tried that. To edit the value list edit the customs of the linked datapoint via the wrench icon.
Greetings and good success!
