### ISSUE TITLE
problem with blind's up/down buttons

### ISSUE THREAD

**Issue by cowconnection** [sbormann/ioBroker.iqontrol#190]
when using the blind's up and down buttons, only false state is sent to the adaptor. checking with chrome, console shows that on mouse down nothing is sent, mouse up is sending false state.

is there any special idea by this behaviour that i did not understand yet?

i am using:
Node.js: v12.22.1
NPM: v6.14.12
Version: 1.6.4

**Comment by sbormann** [comment]
I think this is a bug.
Could you please try the actual github-version and tell me, if this fixes the problem?

**Comment by cowconnection** [comment]
tried out 1.8.0. 
now true is sent to the adaptor but no false. 
best would be to have the button state represented in the object of the target adaptor. 
the function should be like a momentary push button, or is there another intention?

**Comment by sbormann** [comment]
Hi, im not completely shure if i understand what you mean.
If you need iQontrol to submit "false", you can set UP_SET_VALUE or DOWN_SET_VALUE to "false". Then this will be transmitted when you click the button.

**Comment by cowconnection** [comment]
what i was trying to explain is:
button down => true
button up => false

like you would control a motor. button down - motor starts, button up - motor stops.

**Comment by sbormann** [comment]
Sorry to ask again,
with „button down“, do you mean the button “down” or do you mean holding down the button and with button up relasing it?

If you mean the two distinct buttons “up” and “down” and want to send “true” when klicking on the “up” button and “false” when klicking on the “down” button, you can use the SET_VALUES as mentioned in my last mail.

If you mean sending “true” when holding down a button and “false” when releasing it, than this is not possible at the moment. But for that you can use the STOP-Button and use “false” as SET_VALUE.

Hope that helps?


Von: cowconnection ***@***.***>
Gesendet: Montag, 28. Juni 2021 09:08
An: sbormann/ioBroker.iqontrol ***@***.***>
Cc: Sebastian Bormann ***@***.***>; Comment ***@***.***>
Betreff: Re: [sbormann/ioBroker.iqontrol] problem with blind's up/down buttons (#190)


what i was trying to explain is:
button down => true
button up => false

like you would control a motor. button down - motor starts, button up - motor stops.

**Comment by sbormann** [comment]
Is the problem solved?

**Comment by sbormann** [comment]
Please reopen if you need further help.
