### ISSUE TITLE
Die Möglichkeit was zu Ersetzen beim Kopieren von Geräte

### ISSUE THREAD

**Issue by ldittmar81** [sbormann/ioBroker.iqontrol#193]
Das Kopieren von Geräte ist eine sehr wichtige Funktion, denn man erstellt ein Gerät nach Wunsch und alle anderen Geräte die die gleiche Funktion haben sollen gleich reagieren.

Beim Alias-Manager gibt es die Möglichkeit beim kopieren der Aliase, Texte zu ersetzen:

![29-07-_2021_16-07-00](https://user-images.githubusercontent.com/9552828/127506993-94972bf5-e4f2-4696-8f38-6fc2bf62ce37.png)

Das gleiche wäre beim iQontrol ein Traum, denn zur Zeit muss man jedes Gerät nach dem Kopieren, manuell bearbeiten und die Verlinkung ändern.

**Comment by sbormann** [comment]
Hi, das ist eine sehr gute Idee! Mach ich sobald wie möglich. VG

**Comment by sbormann** [comment]
Ist jetzt in der aktuellen Github-Version zum Testen mit drin. Gib mal Rückmeldung, ob das so OK ist. VG!

**Comment by ldittmar81** [comment]
Echt super... Es funktioniert wie es sollte. Dennoch habe ich ein paar Anmerkungen, die das ganze noch besser machen würden. Beim Alias Manager werden Links (Ersetzen diese Zeichenfolge...) eine Liste der existierende Strings im original Objekt angezeigt.

<img width="1252" alt="Screenshot 2021-08-01 125804" src="https://user-images.githubusercontent.com/9552828/127768356-016ce8d6-957a-4c18-bcd7-70bd670d7506.png">

Außerdem ist es oft so, dass ein Gerät aus verschiedene Datenpunkte besteht. Deswegen kann man beim Alias-Manager auch x beliebige Ersetzungs-Regeln hinzufügen.

Nichts desto trotz: echt super :-)

**Comment by sbormann** [comment]
Jo, hast Recht, habs jetzt wie im Alias-Manager gemacht. Bitte testen (kam bisher noch nicht dazu, es ausführlich zu testen, Fehler sind also nicht ausgeschlossen). VG

**Comment by ldittmar81** [comment]
Genau so!! Super!! Es wird sogar in de Arrays ersetzt. Die Datenpunkte der Arrays werden aber nicht in der Auswahlliste gezeigt, sondern nur die DPs die außerhalb hinzugefügt worden sind.

**Comment by sbormann** [comment]
> Die Datenpunkte der Arrays werden aber nicht in der Auswahlliste gezeigt

:) Hatte gestern noch kurz drüber nachgedacht und war der Meinung, das merkt eh keiner :) 

Also, sehr cool, wie aufmerksam Du bist, ich werde es nachreichen :)

**Comment by sbormann** [comment]
Sollte jetzt gehen (zudem werden jetzt auch die Duplikate rausgefiltert). Ich glaube, so müsste es jetzt gut sein, oder?

**Comment by ldittmar81** [comment]
> :) Hatte gestern noch kurz drüber nachgedacht und war der Meinung, das merkt eh keiner :)
> 
Ich bin Entwickler - mir kann man nichts vormachen 🤣 - Apropos Entwickler: Komm doch mal zum ioBroker-Entwickler-Meeting - ist sehr informativ ;-) - das nächste Mal am 15.09

Hab es jetzt getestet und es passt :-) - Danke!!
