### ISSUE TITLE
Hide some objects on info A/B

### ISSUE THREAD

**Issue by ldittmar81** [sbormann/ioBroker.iqontrol#194]
It wold be great to have a option to hide values from array if its empty. And while we're at it, changing the text color for the object would be awesome.

**Comment by sbormann** [comment]
Hi, kannst Du mir noch mal genauer erklären, was Du willst? Habs glaube ich nicht ganz verstanden. VG

**Comment by ldittmar81** [comment]
Soo... Im Info A und B kann man Werte in einem Array angeben, die dann nacheinander angezeigt werden. Es wäre cool, wenn man die Möglichkeit hätte, leere Werte nicht anzuzeigen. Als Beispiel: ich zeige bei einem Kachel die aktuelle und die neueste Version. Wenn die aktuelle Version auch die neueste ist, ist das andere State leer und im Info wird 0 angezeigt... Schön wäre es, wenn man es dann gar nicht anzeigen würde.

Außerdem wäre eine eigene Textfarbe pro Wert im Array cool.

**Comment by sbormann** [comment]
Probier mal bitte die aktuelle Github-Version. Ich habs jetzt auf die Schnelle nicht getestet, aber mit etwas Glück machts was Du willst.

**Comment by ldittmar81** [comment]
Ich habe es probiert und es ist fast das, was ich mir vorgestellt habe. Ideal wäre es, wenn es dem leeren Wert einfach überspringen würde, denn jetzt zeigt er einfach nichts und wechselt zwischen Wert und nichts... sollte ich zum Beispiel mehrere leere Werte im Array haben, dann würde es zwischen viele leere Werte springen. Das mach ja wenig Sinn... Deswegen einfach im Array überspringen.

**Comment by sbormann** [comment]
Hatte glaube ich einen Denkfehler drin. Kannst Du es bitte noch mal probieren, ob es jetzt macht, was es soll?

**Comment by ldittmar81** [comment]
Genau so! Passt :-)
