### ISSUE TITLE
 Verhalten der Gerätekachel, wenn das Gerät inaktiv ist

### ISSUE THREAD

**Issue by ldittmar81** [sbormann/ioBroker.iqontrol#195]
Zu den "Verhalten der Gerätekachel, wenn das Gerät inaktiv ist" könntest du noch UNREACH ausblenden hinzufügen, denn es gibt Objekte, die wenn sie ausgeschaltet sind auch unreach werden.

**Comment by sbormann** [comment]
Ist in der aktuellen Github-Version jetzt mit drin (allerdings in der Sektion UNREACH).
