### ISSUE TITLE
Gerätename mit DP überschreiben

### ISSUE THREAD

**Issue by ldittmar81** [sbormann/ioBroker.iqontrol#196]
Es wäre echt cool, wenn man ein Gerätename im Kachel mit dem Text eines Datenpunktes überschreiben könnte - da ergeben sich dann ganz neue Möglichkeiten: z.B. Wetter-Kacheln - Als Gerätename hätten wir "heute", "morgen", "übermorgen" und dann? Zur Zeit wäre da Schluss. Man könnte dann z.B. ein DP mit dem Datum als "Gerätename überschreiben mit..." angeben. Das würde ich aber als Punkt im Gerät eintragen (Standard für alle Geräte - wie UNREACH)

**Comment by sbormann** [comment]
Hi, das geht schon, siehe hier: https://github.com/sbormann/ioBroker.iqontrol#device-names

Beispiel:
So habe mich meine Service-Meldungen konfiguriert:
Name = ``Service&shy;meldungen|{javascript.0.Device-Counter.Servicemeldungen.ACTUAL}``

Das ist das Custom des Datenpunktes javascript.0.Device-Counter.Servicemeldungen.ACTUAL:
![image](https://user-images.githubusercontent.com/49171332/127888062-3477433d-46f1-4975-86c3-0e74d0f96a43.png)

Und so sieht das dann aus:
![image](https://user-images.githubusercontent.com/49171332/127888188-fa40aaa4-93c6-4fab-9e33-5056f02691ed.png)

Ist es das, was Du meinst?

**Comment by ldittmar81** [comment]
Genau das :) - Ahh... Bald kommt Admin in Stable. Wie sieht es mit iQontrol 1.8.x aus?
