### ISSUE TITLE
moment not defined

### ISSUE THREAD

**Issue by pmbert** [sbormann/ioBroker.iqontrol#197]
just upgraded to version 1.8.1.

Shows only a blank page with no widgets.
Error message: moment not defined.

**Comment by sbormann** [comment]
Hallo,

bitte die folgenden Schritte durchführen. Bei weiteren Problemen bitte vor allem den 2. Absatz beachten, hier wird beschrieben, wie man ein Log des Fehlers erzeugt und welche Screenshots für die weitere Analyse notwendig sind:

https://github.com/sbormann/ioBroker.iqontrol#troubleshooting

Vielen Dank!

**Comment by pmbert** [comment]
Ich habe in index.html die folgende Zeile eingetragen, jetzt funktioniert es:

<script type="text/javascript" src="jquery/plugins/moment/moment.js"></script>

**Comment by sbormann** [comment]
Vielleicht ist das Update nicht korrekt durchgelaufen? Egal, hauptsache es läuft, bislang war das auch die einzige Meldung in die Richtung. Falls der Fehler noch mal auftritt, bitte einfach noch mal melden.

**Comment by pmbert** [comment]
Ich habe mir die index.html von Github heruntergeholt. Ich nehme an, das ist die richtige Version.

**Comment by sbormann** [comment]
Ja, das passt. VG
