### ISSUE TITLE
Configuration does not open after various updates

### ISSUE THREAD

**Issue by stevoboy** [sbormann/ioBroker.iqontrol#198]
The configuration tab does not open anymore but is in a contiunous refresh cycle. I suppose it is related to a couple of updates I made today.

This is my current configuration:
![image](https://user-images.githubusercontent.com/84937873/128608188-e7c0fd0f-5dd4-4f52-ac15-4666e59da01a.png)

Admin Version: v5.1.23

Any way to fix it? I have seen a similar bug report related also to a new admin version.

**Comment by sbormann** [comment]
Hi,

- [ ] which browser?
- [ ] which iQontrol-Version?
- [ ] please send debug logs from brower-console (F12) - see here https://github.com/sbormann/ioBroker.iqontrol#troubleshooting

**Comment by stevoboy** [comment]
- Chrome and Edge - cleared browser cache on both

- I deinstalled and reinstalled iqontrol with an empty configuration - that didn't fix the problem.
- 
Here is the debug log filtered to warning and error: 

VM249 socket.io.js:194 Uncaught DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
    at WebSocket.socket.onmessage (http://192.168.178.13:8081/socket.io/socket.io.js:194:28)

**Comment by stevoboy** [comment]
![image](https://user-images.githubusercontent.com/84937873/128646477-7c970654-2041-4d51-914c-acab73c34951.png)
Do I maybe have a problem with the ports? This is the current settings...

![image](https://user-images.githubusercontent.com/84937873/128646497-bd68bc1e-a650-4f00-972c-a2ae2a7eea9a.png)

I also cannot open Jarvis as well....

**Comment by bavarialogy** [comment]
Hi there,

I've got the same problem here. It seems that the configuration dialog loops while loading translations. This is my console output generated after looping for 1 time:
(see attached file)
[20210809_console_log.txt](https://github.com/sbormann/ioBroker.iqontrol/files/6954962/20210809_console_log.txt)


Once I exclude translate.js from the output, it gets much shorter:
`VM1794 socket.io.js:59 [2021-08-09T13:40:46.592Z] Try to connect
VM1812 index_m.js:4323 Loading iQontrol Settings
VM1812 index_m.js:4440 getLink of best fitting web-adapter
VM1812 index_m.js:4489 Got Link: http://iobroker.bvlgy:8082/iqontrol
VM1812 index_m.js:4508 Try to init socket.io
VM1794 socket.io.js:59 [2021-08-09T13:40:56.215Z] Try to connect
VM1812 index_m.js:4546 Inited socket.io
VM1811 conn.js:322 was offline for 1628516456.275s
VM1816 socket.io.js:59 [2021-08-09T13:40:56.545Z] Try to connect
VM1833 index_m.js:4323 Loading iQontrol Settings
VM1833 index_m.js:4440 getLink of best fitting web-adapter`

I observed that the controls are loaded in English first, then get updated with the German labels and after that, the loop occurs. Switching the system language to English didn't help either. May it have something to do with the socket.io connection?

My versions:
web v3.4.7
iqontrol v1.6.4
Node.js v12.22.4
NPM v6.14.14

I'll provide additional logs and information if needed.

**Comment by bavarialogy** [comment]
Update: I just recorded a complete debug profile with Chrome's dev tools. It covers two loops. 
[Profile-20210809T155823.zip](https://github.com/sbormann/ioBroker.iqontrol/files/6954994/Profile-20210809T155823.zip)

**Comment by sbormann** [comment]
Please update iQontrol to latest beta, that should solve the problem.

**Comment by bavarialogy** [comment]
Updating via Github (visible through expert settings) took me to v1.8.2 and solved the issue. Thanks alot!

**Comment by sbormann** [comment]
Im glad that helped. Sorry for the inconvenience, the next stable version will come soon.

**Comment by stevoboy** [comment]
I also solved the issue, by updating via Github. I will make better backups next time. It took me till 2 AM to make our roof windows work again ;-)
