### ISSUE TITLE
IQcontrol configuration not loading when updating from 1.82 to 1.91

### ISSUE THREAD

**Issue by looxer01** [sbormann/ioBroker.iqontrol#199]
Hi,
using iobroker with 

The configuration cant be loaded after upating to version 1.91.
similar issue can be found under "closed issues"

log
`
Failed to load resource: the server responded with a status of 403 (Forbidden)
:8082/iqontrol/images/icons/time_calendar_on.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:8082/iqontrol/images/icons/time_calendar_on.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:8082/iqontrol/images/icons/time_calendar_on.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:8082/iqontrol/images/icons/time_calendar_on.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:8082/iqontrol/images/icons/time_calendar_on.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
raw.githubusercontent.com/instalator/iobroker.benq/master/admin/benq.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/ioBroker.exchangerates/master/admin/exchangerates.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/iobroker.foobar2000/master/admin/foobar2000.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/ioBroker.haier/master/admin/haier.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/ioBroker.kodi/master/admin/kodi.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/ioBroker.mclighting/master/admin/mclighting.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/ioBroker.mercury/master/admin/mercury.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/ioBroker.lgtv-rs/master/admin/lg.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/ioBroker.mpd/master/admin/mpd.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/iobroker.mikrotik/master/admin/mikrotik.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/ioBroker.omnicomm-lls/master/admin/omnicomm-lls.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/ioBroker.sanext/master/admin/sanext.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/ioBroker.starline/master/admin/logo-192x192.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/ioBroker.vis-players/master/admin/players.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/iobroker.benq/master/admin/benq.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/ioBroker.exchangerates/master/admin/exchangerates.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/iobroker.foobar2000/master/admin/foobar2000.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/ioBroker.haier/master/admin/haier.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/ioBroker.kodi/master/admin/kodi.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/ioBroker.mercury/master/admin/mercury.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/ioBroker.mclighting/master/admin/mclighting.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/ioBroker.lgtv-rs/master/admin/lg.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/iobroker.mikrotik/master/admin/mikrotik.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/ioBroker.omnicomm-lls/master/admin/omnicomm-lls.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/ioBroker.vis-players/master/admin/players.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/ioBroker.starline/master/admin/logo-192x192.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/ioBroker.mpd/master/admin/mpd.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/ioBroker.sanext/master/admin/sanext.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/iobroker.benq/master/admin/benq.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/iobroker.foobar2000/master/admin/foobar2000.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/ioBroker.haier/master/admin/haier.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/ioBroker.exchangerates/master/admin/exchangerates.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/ioBroker.kodi/master/admin/kodi.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/ioBroker.lgtv-rs/master/admin/lg.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/ioBroker.mclighting/master/admin/mclighting.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/ioBroker.mercury/master/admin/mercury.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/ioBroker.starline/master/admin/logo-192x192.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/ioBroker.vis-players/master/admin/players.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/ioBroker.sanext/master/admin/sanext.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/ioBroker.omnicomm-lls/master/admin/omnicomm-lls.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/ioBroker.mpd/master/admin/mpd.png:1 Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/instalator/iobroker.mikrotik/master/admin/mikrotik.png:1 Failed to load resource: the server responded with a status of 404 ()
:8082/iqontrol/images/icons/time_calendar_on.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
index_m.js:2157 Uncaught (in promise) TypeError: Cannot read property 'push' of undefined
index_m.js:2157 Uncaught (in promise) TypeError: Cannot read property 'push' of undefined
    at index_m.js:2157
    at Array.forEach (<anonymous>)
    at index_m.js:2145
    at Array.forEach (<anonymous>)
    at load (index_m.js:2144)
    at adapter-settings.js:448
    at SocketClient.findAnswer (socket.io.js:255)
    at WebSocket.socket.onmessage (socket.io.js:163)

`

Iobroker  Plattform
linux Betriebssystem
linuxArchitektur x64 CPUs 4
Geschwindigkeit 2095 MHz
Modell Common KVM processor
RAM5.68 GB
Node.js v12.22.5
NPM  6.14.14

**Comment by sbormann** [comment]
Thanks for your feedback, should be hopefully fixed in 1.9.2.
Please try and report if the error is gone.
Many thanks!

**Comment by looxer01** [comment]
thank you so much for the quick reaction.
installed from github (link) and it works for me
 :)
