### ISSUE TITLE
Any docs guide us how to use this adapter?

### ISSUE THREAD

**Issue by SchumyHao** [sbormann/ioBroker.iqontrol#2]
It seems this UI is very potential. Is there any docs can let me know how to use this adapter?

**Comment by sbormann** [comment]
Hi, 

here is a little start guide. I hope that helps.

* Creating views.
	You can consider views as something like a pages.
* Then create devices on these views.
	Devices have a role, that detemines the function of the device, which icons are used and so on.
	Depending on that role you can link several states to the device. These will give the device its functionality.
	You you select 'Link to other view' as role to create links between the different views.
	You can also try to use the Autocreate-Function to chose an existing device from the iobroker-object-tree. Autocreate tries to find out the role and to match as many states as possible.
* Afterwards you can create a toolbar, wich is displayed as footer.
	Toolbar-Entrys are links to views.
	The first Toolbar-Entry will be your 'Home-View' with will be loaded at start.
* To give everything a fancy style, you can upload your own images.
	You can use your images as background-images for views, or for devices.
	The free builtin demo-wallpapers are from www.pexels.com.
