### ISSUE TITLE
Landscape mode for wall mounted Tablets

### ISSUE THREAD

**Issue by Stroell** [sbormann/ioBroker.iqontrol#205]
I´m starting to use this fantasic Adapter for my wall mounted Tablet! 👍
However, for landscape devices it would be great if you could pin/move/etc Tiles to the right side of the screen, instead of scrolling up and down.

**Comment by Stroell** [comment]
<img width="1036" alt="Bildschirmfoto 2021-09-03 um 21 11 43" src="https://user-images.githubusercontent.com/42348774/132055663-2fdde77c-0efc-4586-ba65-75731e246bdb.png">

Thanks for your response!
That´s an example (just made a really wide browser window 😉)

Instead of scrolling up and down it would be great if the Tiles would move to the right side

**Comment by sbormann** [comment]
Thank you. I just don't understand why the tiles break to new lines in your example. Have you set the "NL"(=New Line)-checkbox in the Devices tab? Here is how it hehaves in my case:
![image](https://user-images.githubusercontent.com/49171332/132063024-6f737a67-a6e1-46c9-8eac-ffd668ab8894.png)

**Comment by sbormann** [comment]
Please reopen if you have further questions.
