### ISSUE TITLE
Feature Request: "Save" on all levels of editing within iobroker-administration

### ISSUE THREAD

**Issue by astrakid** [sbormann/ioBroker.iqontrol#216]
When changing details in an object you need to submit all changes by pressing "ok" for getting back to the main iqontrol-admin screen and save those changes. that makes it uncomfortable for testing changes.

1. open iqontrol administration
2. open a device
3. e.g. open "additional_control"
4. change something
5. for submitting the changes you have to press ok in "additiional_control edit window"
6. then you have to press "ok" once again to get back to iqontrol admin main screen
7. press "save"

**Expected behavior**  
it would be very comfortable to get the save button on all levels of editing, to be able to quickly submit changes, check the results and edit again.

**Versions:**  
 - Adapter version: 1.9.9

**Comment by sbormann** [comment]
This would be cool (i'm missing that very often) - but saving is an iobroker framework function and that doesn't support it- or at least i don't know how to do it, sorry. Greeings!

**Comment by astrakid** [comment]
ok,thanks for the information. i will raise a feature request at iobroker.

**Comment by astrakid** [comment]
hi,
https://github.com/ioBroker/ioBroker/issues/361
you are asked to comment there, what is needed by iqontrol...

**Comment by astrakid** [comment]
i have to correct my statement: @sbormann you are asked to open an issue at iobroker what would be needed for this issue.
