### ISSUE TITLE
RGB bar is not displayed

### ISSUE THREAD

**Issue by o0shojo0o** [sbormann/ioBroker.iqontrol#218]
**Describe the bug**  
 Despite correct definition (I hope it) the RGB bar is not displayed.

**Screenshots & Logfiles**  

![image](https://user-images.githubusercontent.com/19333515/143143877-644b6f91-98f9-4c7f-9431-59b5d2c07f89.png) 
![image](https://user-images.githubusercontent.com/19333515/143143888-869fc025-1de0-40f6-b20b-ccb77462bf50.png) 
![image](https://user-images.githubusercontent.com/19333515/143143892-5ee33652-8a3f-4ecc-baf0-7a767fd7a07f.png) 
![image](https://user-images.githubusercontent.com/19333515/143143897-accfa22c-4c8f-4814-b393-585acb569024.png) 
 
```
renderDialog iqontrol.0.Views.Terrasse.devices.1 
index.js:7958 [] 
index.js:7566 Add timestamp to Garden Poles with value 0 
index.js:7764 !stateFillsDevice or badge is invisible - remove padding-top 
index.js:7566 Add timestamp to Garden Poles with value 0 
index.js:7764 !stateFillsDevice or badge is invisible - remove padding-top 
index.js:3078 Converting #RGB from #FF0044 to H|S|B/CT|B... 
index.js:3187 ...result is 344|100|100/null|null 
index.js:3022 Converting H|S|B/CT|B from 344|100|100/8.9|null to #RGB... 
index.js:3069 ...result is #ff0044 
index.js:5603 Not sending state, because a white value was changed, but AlternativeColorspace is without white 
index.js:3078 Converting #RGB from #FF0044 to H|S|B/CT|B... 
index.js:3187 ...result is 344|100|100/null|null 
index.js:4477 toolbarContextMenu end function - find active Toolbar Index
```

**Versions:**  
 - Adapter version: 1.9.16 
 - JS-Controller version: 3.3.19
 - Node version: v12.22.7
 - Operating system: Docker (ubuntu)

**Comment by sbormann** [comment]
Hi, 
ist das erst seit dem letzten Update wieder so?
VG

**Comment by o0shojo0o** [comment]
Moin @sbormann, 
Ja ich glaube, hatte die "alte" Version nur einen Tag drauf ^^ 
Bin noch ganz frisch mit deinem Adapter unterwegs ;)

**Comment by sbormann** [comment]
Hi, ich glaube, ich habe den Fehler gefunden. Kannst Du mal bitte die aktuelle Github-Version testen? D.h. auf das Katzenlogo im Adapter-Tab gehen -> Github -> iQontrol
Die Versionsnummer bleibt gleich, bitte nicht verwirren lassen. Wenn es bei Dir dann wieder läuft, veröffentliche ich das als neue Version

**Comment by o0shojo0o** [comment]
Ja läuft nun wieder :) 
Ich lasse mal das Issues offen so das Du das mit dem Commit closen kannst.
Danke für den schnellen Fix!

**Comment by sbormann** [comment]
Danke ebenso!
