### ISSUE TITLE
FLOT chart is displayed incorrectly after 30 seconds

### ISSUE THREAD

**Issue by o0shojo0o** [sbormann/ioBroker.iqontrol#219]
**Describe the bug**  
FLOT chart is displayed incorrectly after 30 seconds

**Screenshots & Logfiles**  
When loading the page fresh 
![image](https://user-images.githubusercontent.com/19333515/143309042-e0421b80-578d-4612-a4d4-6d52914266f9.png)
After 30 seconds
![image](https://user-images.githubusercontent.com/19333515/143309064-bf739002-503a-49e9-a65d-7641419a73cb.png)

**Versions:**  
- Adapter version: 1.9.16
- JS-Controller version: 3.3.19
- Node version: v12.22.7
- Operating system: Docker (ubuntu)

**Comment by sbormann** [comment]
Das Problem kommt bei FLOT vor, wenn über einen langen Zeitraum keine Daten vorhanden sind, d.h. wenn nur Änderungen aufgezeichnet werden. Man kann das umgehen, wenn man z.B. alle 10 Minuten (= 600 Sekunden) trotzdem einen Wert speichert:
![image](https://user-images.githubusercontent.com/49171332/144112871-37a17b14-16ac-4e9f-b8f0-6ddda4ebb778.png)

VG!

**Comment by o0shojo0o** [comment]
Das ist es nicht, Logintervall mit 60 Sek. ist bei mir default. 
![image](https://user-images.githubusercontent.com/19333515/144113453-8392919a-5cc4-49d4-aa29-378d1f989e8f.png)

**Comment by sbormann** [comment]
Dann habe ich leider keine schnelle Idee mehr dazu, sorry.

**Comment by sbormann** [comment]
Tritt das Problem nur auf, wenn in dem gesamten Zeitraum keine Änderung war?

**Comment by sbormann** [comment]
Da keine Rückmeldung mehr erfolgt ist, nehme ich an, das Problem ist erledigt. Andernfalls bitte erneut öffnen.
