### ISSUE TITLE
Vorschaubilder in den Einstellungen werden nicht angezeigt

### ISSUE THREAD

**Issue by hene42** [sbormann/ioBroker.iqontrol#223]
Hallo zusammen,

ich habe mir mal zum testen den iQontrol Adapter installiert jedoch werden die kleinen Vorschaubilder in den Einstellungen
nicht angezeigt. In der Visualisierung selbst werden die Bilder dann jedoch ganz normal angezeigt.

![001](https://user-images.githubusercontent.com/62837358/147495149-057d1bf8-8d68-4ebb-a5e7-8edc12820a88.jpg)

![002](https://user-images.githubusercontent.com/62837358/147495161-435ffa8c-f40b-4c44-9e9a-5267aeb6f035.jpg)

Mein System: Intel NUC mit Proxmox, ioBroker läuft in VM, Admin 5.2.3, Host 3.3.22, Web 3.4.12
Getestet mit Google Chrome und EDGE, Verlauf etc. wurden ebenfalls schon gelöscht

Danke.

**Comment by sbormann** [comment]
Bitte teste mal die aktuelle Github-Version von iQontrol. Falls es dann immer noch nicht geht, dann bitte mal mit rechtsklick auf eines der nicht funktionierenden Bilder klicken und "bild in neuem Tab öffnen" wählen (so heißts zumindest in chrome). Dann sieht man, welchen Dateiname das nicht funktionierende Bild hat - und den bräuchte ich dann.

**Comment by hene42** [comment]
Hallo, 

installiert habe ich die Version 1.11.0.
Wenn ich die Bilder in einem neuen Tab öffne geht alles.

Bei Wallpaper kommt zum Bsp.
http://192.168.178.140:8082/iqontrol/images/wallpaper/bakestone.jpg

bei allen Icon kommt aber immer das Gleiche:
http://192.168.178.140:8082/iqontrol/images/icons/various.png

Danke.

**Comment by sbormann** [comment]
Hmm, keine Ahnung, was das sein könnte. Wenn die Bilder im neuen Tab geöffnet werden, dann müssten sie doch auch funktionieren?? Bin erst mal überfragt. 
Das mit dem various.png ist übrigens ein eingebautes Fallback bei den Icons; wenn das Icon nicht gefunden wird, dann nimmt er das. 
Kannst Du mal bitte mit F12 die Browser-Konsole öffenen und schauen, welche Fehlermeldungen er gibt, wenn Du so eine Liste lädst? (Siehe readme unter Troubleshooting)

**Comment by tobkoh** [comment]
Also bei mir funktioniert es leider auch nicht. 
![Bildschirmfoto 2022-01-13 um 21 19 39](https://user-images.githubusercontent.com/26777201/149403489-ae7adaef-63f3-4f80-adb5-0e8047d02917.png)

**Comment by tobkoh** [comment]
Wenn ich jedoch in den files schaue sind alle vorhanden. 
![Bildschirmfoto 2022-01-13 um 21 24 39](https://user-images.githubusercontent.com/26777201/149404053-8baba7e8-15f5-41c3-8a5f-893a46a637a6.png)

**Comment by hene42** [comment]
Hi tobkoh, hast du eventuell BullGuard als Virenscanner?

**Comment by tobkoh** [comment]
Nein habe ich nicht.
Was extrem komisch ist, ich hab auf einem zusätzlichen Raspberry Pi noch eine unabhängige ioBroker Installation, da sind die Vorschaubilder sichtbar.

**Comment by hene42** [comment]
Okay, ich habe BullGuard als Virenscanner und habe bemerkt wenn ich den Secure Browser von BullGuard nutze dann wird alles angezeigt. Andere Browser funktionieren nicht. Auch auf einen Linux-Rechner kann ich die Bilder sehen. Daher denke ich das irgendein Programm irgendwas blockt. Eventuell sogar BullGuard selbst.

**Comment by tobkoh** [comment]
Also bei mir ist es so wenn ich auf meiner Hauptinstallation egal über welchen Browser versuche die Vorschaubilder anzuzeigen kommt immer dieser Fehler. Wenn ich jedoch auf meiner Test installation (Raspberry Pi) mit dem selben Laptop mit den selben Browsern, werden die Vorschaubilder angezeigt. 

Also glaube ich nicht das es am Laptop liegt. 
Ich habe auch mal versucht die Vorschaubilder in einem neuen Tab zu öffnen, keine Anzeige. 
Ebenso habe ich Vorgänger version von iqontrol installiert auch kein Erfolg

**Comment by sbormann** [comment]
Irgend eine chance, an eine erweiterte Fehlermeldung zu kommen? Ein Error-Code? Die Meldung "Failed to load resource" gibt ja nicht so viel her... Was passiert, wenn Du auf die URL hinter der Fehlermeldung oder auf die Fehlermeldung selbst klickst? Ggf. liefert ein anderer Browser eine bessere Fehlermeldung? Was ich komisch finde, ist der Port 8096 - stimmt der?

**Comment by tobkoh** [comment]
Hab das Problem gefunden. Ich hatte einen zweite Admin Instanz und eine zweite Web Instanz am installiert, jedoch beide nicht aktiviert. 
Hab jetzt beide runtergeschmissen und iqcontrol ebenfalls komplett neu installiert jetzt funktioniert es. 
Was jedoch komisch ist ich habe dies schon länger und am Anfang waren die Vorschaubilder sichtbar und von einem auf den anderen Tag waren diese weg.

**Comment by sbormann** [comment]
Ok, verstehe ich jetzt auch nicht, aber Hauptsache, es geht! Danke für die Rückmeldung!
