### ISSUE TITLE
Feature Request: Fernbedienung für Mi-Vacuum Roboter

### ISSUE THREAD

**Issue by Sundancer78** [sbormann/ioBroker.iqontrol#225]
Ist es möglich, eine Art Fernbedienung für Mi- Vacuum Roboter zu integrieren? so das die Datenpunkte des MI-Vacuum Adapters verwendet werden können?

**Comment by sbormann** [comment]
Hi, prinzipiell geht das mit ADDITIONAL_CONTROLS, frag mal bitte im Forum, da haben das schon einige gemacht.
https://forum.iobroker.net/topic/22039/test-adapter-iqontrol-1-11-x-vis 
VG
