### ISSUE TITLE
Integration of Openhab Adpater Items. 

### ISSUE THREAD

**Issue by jensfr1** [sbormann/ioBroker.iqontrol#23]
Hello, 
it would be cool if you could enable that openhab items get listed. Right now I dont see them. 

![image](https://user-images.githubusercontent.com/12272992/57365933-51984200-7186-11e9-8669-63c479a80a07.png)

![image](https://user-images.githubusercontent.com/12272992/57365974-61b02180-7186-11e9-8acc-77de15acbb8b.png)

Thanks, Jens

**Comment by sbormann** [comment]
Please try with next version that is coming soon, the autocreate function was reworked. Best regards!
