### ISSUE TITLE
Background Image eines Gerätes über Datenpunkt

### ISSUE THREAD

**Issue by HaggardFFM** [sbormann/ioBroker.iqontrol#234]
Hi Sebastian, 
ich habe eine Problem mit dem Hintergrundbildern auf Geräten. 
Ich möchte den Wert des Hintergrundbildes aus einem Datenpunkt auslesen. 
Datenpunkt: 0_userdata.0.test
Inhalt: ./images/wallpaper/bakestone.jpg

Bei Hintergrundbild gebe ich wie im Readme angegeben {0_userdata.0.test} ein. 
Dieses wird aber nicht angezeigt, und in den DEV Tools steht: 

`<div class="iQontrolDeviceBackgroundImage active" data-iqontrol-device-id="iqontrol.0.Views.Musik.devices.0" style="background-image:url(%7B0_userdata.0.test%7D);"></div>`

Wie kann ich das ändern bzw was mache ich falsch das der Parser hier nicht auf den Datenpunkt zugreift sondern die geschweiften Klammern falsch interpretiert. 

Getestet habe ich das mit Edge und Chrome. 

VG Harald

**Comment by sbormann** [comment]
Hi, du musst vor die geschweifte Klammer noch ein ``|`` packen.

**Comment by trovanaffm** [comment]
Hi Sebastian, habe ich gemacht. 
Keine Änderung:
![image](https://user-images.githubusercontent.com/62116621/153455636-31faa727-dfef-44a0-97d8-6b131adb6c26.png)
![image](https://user-images.githubusercontent.com/62116621/153455743-6ba2316a-cf12-4ef1-a170-c89e31384679.png)
