### ISSUE TITLE
importes Images (jpg) are not available to choose

### ISSUE THREAD

**Issue by Nogger82** [sbormann/ioBroker.iqontrol#241]
**Describe the bug**  
importes Images (jpg) are not available to choose

**Expected behavior**  
Using my own Images for rooms (for example). Pictures seem to be uploaded on my System, but i can´t chosse them.

**Screenshots & Logfiles**  
![iqcontrol_1](https://user-images.githubusercontent.com/102550384/166917807-999167d6-0827-4e78-9d13-51843806b57f.JPG)
![iqcontrol_2](https://user-images.githubusercontent.com/102550384/166917812-10d9171a-650e-42cf-8f12-da792db6def1.JPG)

**Versions:**  
 - Adapter version: 2.0.0
 - JS-Controller version: 4.0.21
 - Node version: v14.19.1
 - Operating system: buster

**Comment by Nogger82** [comment]
Update:
i downloaded some other pictures and these are usable without problems. Maybe it will be helpful, when the parameters for custom images are declared by the developers?

**Comment by Nogger82** [comment]
I prefer Email. Is this your full Email adress: sebastianborman.net ?

**Comment by sbormann** [comment]
Sorry, it swallowed the @ after sebastian :)

**Comment by Nogger82** [comment]
Something went wrong.

<sebastian@borman.net>: Email address could not be found, or was
misspelled (G8)

**Comment by sbormann** [comment]
sorry for that, please use double n for bormann...

**Comment by sbormann** [comment]
Oh my god, now i see what happened: Its the uppercase filetype-ending: .JPG does NOT work, .jpg works.
I need to fix the filters :)
But that is the solutions: just rename the filetype to .jpg.
