### ISSUE TITLE
Iqontrol complains about Admin version

### ISSUE THREAD

**Issue by jlegen** [sbormann/ioBroker.iqontrol#245]
little issue: since latest admin adapter update to 5.4.x, iqontrol (from ‚latest‘) shows a popup:
`Einige Operationen werden nur von Admin-Adapter-Versionen > 5.0.8 unterstützt. Bitte führen Sie ein Update des Admin-Adapters durch! `

**Comment by DocGame69** [comment]
Hier das gleiche.... Habe gerade schon im Forum geschrieben, da da ganze auch Auswirkungen auf die Adapterfunktionalität hat.

**Comment by sbormann** [comment]
Thanks, should be solved with the latest admin-version. Please comment, if the error persists!
