### ISSUE TITLE
Change IP address on which iqontrol waits for connections

### ISSUE THREAD

**Issue by filippolazzati** [sbormann/ioBroker.iqontrol#249]
Hi, I would like to connect to iqontrol through an address like 100.104.24.65:8082 instead of 192.168.1.55:8082. However, iqontrol accepts connections only on local address 192.168.*.*, so I am not able to connect to it from remote (I want to use tailscape, a NAT traversal tool). What can I do? Thanks

**Comment by filippolazzati** [comment]
I simply get connection refused. If I check with netstat -tulpn I get:
![giusta](https://user-images.githubusercontent.com/79703709/172482265-b3fffcb2-c10e-42ad-98cf-5db6994e4770.png)
Where I see that iobroker accepts connections on every address (::::8081), while iqontrol only on 192.168.*.*:8082

**Comment by sbormann** [comment]
What about other adapters that use the web-adapter? I think it is related to the web adapter.

**Comment by sbormann** [comment]
Try 0.0.0.0

**Comment by filippolazzati** [comment]
That is exactly what I want to do, thank you so much! But I cannot find the settings in iobroker

**Comment by sbormann** [comment]
![image](https://user-images.githubusercontent.com/49171332/172484198-a88aa646-8aba-4815-8269-01f83d1b9d67.png)
![image](https://user-images.githubusercontent.com/49171332/172484249-9ab995bd-769c-4186-afc8-2a6b0b0b9677.png)

**Comment by filippolazzati** [comment]
Ok, now I got it! Thank you!!!
