### ISSUE TITLE
Feature Request: min/max Values für flot-chart widget von Datenpunk

### ISSUE THREAD

**Issue by Stroell** [sbormann/ioBroker.iqontrol#250]
Hi, 
es wäre super, wenn man für ein flot-chart widget die min/max Werte von einem Datenpunkt ziehen könnte.
So könnte man z.B. min/max für die heutigen Temperaturen auslesen und im widget der aktuellen Temperatur verwenden

<img width="1278" alt="grafik" src="https://user-images.githubusercontent.com/42348774/184977848-2d7d1ccc-2b68-4226-8b70-a0508acf4b4d.png">

<img width="120" alt="grafik" src="https://user-images.githubusercontent.com/42348774/184978382-f8144c39-62d5-4464-9e39-5cd1c57bef67.png">

**Comment by sbormann** [comment]
Das ist relativ aufwändig zu realisieren, da das FLOT-Widget sich dann zuerst diese Datenpunkte ziehen müsste. Aber es gibt ja die Möglichkeit das ganze auf Automatik zu stellen: 
![image](https://user-images.githubusercontent.com/49171332/194325576-f1e04edd-adfe-462a-a488-ee991615e569.png)

Hilft das?

VG

**Comment by sbormann** [comment]
Bitte erneut eröffnen, falls es weitere Fragen gibt.

**Comment by Stroell** [comment]
Hi, sorry ich habe deine Antwort übersehen.
Bei Automatik funktioniert es nicht immer perfekt, aber wenn es zu aufwendig ist, ist es kein Problem 👍
