### ISSUE TITLE
Problem Iqontrol über Cloud 

### ISSUE THREAD

**Issue by Bjoern-W** [sbormann/ioBroker.iqontrol#252]
Hallo
Ich brauche Hilfe Ich habe das Problem schon im Issue ioBroker.cloud veröffentlicht, dort bekam ich aber die Antwort; "sollte die Frage nicht an iQontrol gehen als erstes?" darum stelle ich das Problem hier auch noch mal ein.
ich habe neuerdings ein Problem was ich mir nicht erklären kann.
Ich will eine neue Zigbee Steckdose in iQontrol einbinden die ich über iQontrol dann einfach nur an und ausschalten will.
Ich wähle als Gerätetyp wie immer Schalter aus und wähle unter STATE den Datenpunkt Switch aus.
Speicher alles und rufe den neue angelegten Schalter über iQontrol im WLAN auf.
So wie es sein soll kann ich die Steckdose AN und AUS schalten.

Aber jetzt zu meinem Problem, rufe ich iQontrol nicht über WLAN auf sondern übers Internet über die [Iobroker.net](http://iobroker.net/) Cloud auf funktioniert das schalten der Steckdose nicht. es schaltet einmal aber dann nicht mehr.

Alte bereits integrierte Steckdosen funktionieren sowohl über Wlan als auch über die Cloud (wobei bei einer der alten Dosen geht es jetzt auch nicht mehr)
Ich habe es dann noch einmal mit einer anderen Zigbee Steckdose und auch mit einer Sonoff Steckdose versucht, bei allen dasselbe Problem. Über WLAN funktioniert es aber nicht über die Cloud.
Hat noch jemand das Problem? Bzw. kann jemand mal versuchen ob es bei ihm funktioniert eine neu eingebundene Dose über die Cloud zu schalten.
Probeweise habe ich eine der Steckdosen statt über iQontrol über VIS eingerichtet und dann per Cloud aufgerufen. Dort funktionier das Schalten sowohl über WLAN als auch über die Iobroker Cloud.
Kann mir bitte jemand bei meinem Problem helfen? Ich bin echt am Verzweifeln.
Björn

Installierte Cloud Version: 4.2.2
Installierte iQontrol Version: 2.0.0
Node.js v16.17.1
JS Controller 4.0.23

**Comment by sbormann** [comment]
Wie auch im Forum geschrieben, bitte mal ein Log aus der Browser-Konsole wenn der Fehler auftritt schicken mit den entsprechenden Zeilen des Fehlers, siehe Troubleshooting in der Readme auf Github. Danke

**Comment by sbormann** [comment]
Hi, vielleicht habe ich es verschlampt, aber ich habe kein Log gesehen, sorry. Bitte einfach noch mal kurz schicken. 
Hier steht, wie es geht: https://github.com/sbormann/ioBroker.iqontrol#troubleshooting

**Comment by Bjoern-W** [comment]
Hi, du hast recht, ich hatte deine Mail auf dem Handy gelesen und dabei versehentlich Bezug auf ein anderes Thema genommen und darum versehentlich unpassend geantwortet.
Aber jetzt zu meinem geschildertem Problem, weil ich da nicht weitergekommen war habe ich mir inzwischen eine VPN Verbindung aufgebaut mit der ich auch ohne den Cloud Adapter die Steckdose, die mir Probleme bereitet hatte, jederzeit erreichen kann. Aber um dem geschilderten Problem auf die Schliche zu kommen habe ich es eben noch mal probiert die Steckdose über Iqontrol und Cloud zu erreichen und was soll ich dir sagen es funktioniert jetzt so wie es soll.
Wie ich neulich Tagelang das Problem hatte war ich echt am Verzweifeln, ich hatte alles wie immer gemacht aber die Steckdose ließ sich nicht schalten. Warum es jetzt funktioniert? keine Ahnung. ich kann dir nicht sagen welche Adapter, die da vielleicht mit reingespielt haben könnten, ich inzwischen aktualisiert habe.
Was gleich geblieben ist sind auf jeden Fall diese Adapter Versionen
Installierte Cloud Version: 4.2.2
Installierte iQontrol Version: 2.0.0
Node.js v16.17.1
JS Controller 4.0.23

Anscheinend hat sich das Problem jetzt alleine gelöst.
Danke das du mir helfen wolltest.
Gruß Björn
