### ISSUE TITLE
iQontrol über Cloud nicht mehr erreichbar 

### ISSUE THREAD

**Issue by FANAU-Softwareentwicklung** [sbormann/ioBroker.iqontrol#253]
Beim Aufruf sehe ich nur den Ladescreen von iQontrol. Solange ich in einer parallelen Sitzung in admin eingeloggt bin, funktioniert alles.

Dieses Problem habe ich nach einem Update von web und Cloud festgestellt.

admin 6.2.22
cloud 4.2.2
web 4.2.0
iQontrol 2.0.0
Node 14.20

**Comment by sbormann** [comment]
Hi, nutze Cloud nicht selbst, deshalb kann ich den Fehler nicht nachstellen. Bitte mal ein Log aus der Browser-Konsole wenn der Fehler auftritt schicken mit den entsprechenden Zeilen des Fehlers, siehe Troubleshooting in der Readme auf Github. Danke

**Comment by sbormann** [comment]
Falls das Problem weiter besteht, bitte erneut um Rückmeldung. VG!
