### ISSUE TITLE
Feature Request: Battery state -> 0=idle;1=charging;2=discharging

### ISSUE THREAD

**Issue by Saharel001** [sbormann/ioBroker.iqontrol#254]
Hallo zusammen,

ein icon für den Zustand "entladen" analog zu "laden" im battery widget würde für PV-Anlagen helfen.
Hier würde ich mich über eine Anpassung freuen.  

Vielleicht macht es hier Sinn die Icon´s bei beiden zuständen anzupassen (Blitz = entladen / Plug = Laden) oder so ;)

**Comment by sbormann** [comment]
Hi,
gute Idee. Habe ich eingefügt und auf Github hochgeladen.
Habe jetzt das ganze für Abwärtskompatibilität so geändert, dass es einen zweiten Datenpunkt "DISCHARGE" gibt.
Die Icons kannst Du ja in den Geräteoptionen ändern, so wie es Dir gefällt.
VG!!
