### ISSUE TITLE
Missing Devices - windspeed and rain

### ISSUE THREAD

**Issue by theengineer0815a** [sbormann/ioBroker.iqontrol#255]
Hallo! 

Hope you can add a windspeed sensor and a rain sensor to your list of devices.

Thanks

**Comment by sbormann** [comment]
Hi, 
what functionallity is needed for them?
Thanks

**Comment by theengineer0815a** [comment]
Thanks for the quick reply!

For Windspeed:
- For the states (true = wind, false = no wind) a windsock symbol horizontaly or hanging down
- The wind speed itself.
- Maybe the Beaufort scale with an Infotext.

For rain:
- For t he states (true = rain, false = no rain) an umbralla open or closed
- The value of the rain gauge.

I build it myself with the "Wert" Device-Type, but i am not satisfied with myself. As i want the values beside the icon and the space below for further information.

![image](https://user-images.githubusercontent.com/114805477/199189363-23c28174-550f-48dd-a969-2caa54916b06.png)

**Comment by sbormann** [comment]
Hi, you can use INFO_A and INFO_B to archieve this. You can also upload your own user-symbols for them.

**Comment by sbormann** [comment]
If you have further questions, please reopen the issue.
