### ISSUE TITLE
Steckdose wird nicht richtig erkannt 

### ISSUE THREAD

**Issue by MarkusMG3** [sbormann/ioBroker.iqontrol#259]
![inbound4071439208516430592](https://user-images.githubusercontent.com/79330802/208973990-88825275-48b9-4a25-bd51-8fa403d15e74.jpg)
Hallo Zusammen,
Habe das Problem, dass meine Zigbee Steckdose nicht richtig erkannt wird.
Auch werden mir keine wirklichen Werte angezeigt.

Kann ich als Anfänger irgendwas daran ändern?

Besten Dank und schöne Grüße
Markus

**Comment by MarkusMG3** [comment]
![inbound7160555714827576357](https://user-images.githubusercontent.com/79330802/208974019-09a1d8cc-e0cb-45f2-a0cd-fc593501a630.jpg)
![inbound3032539225024320870](https://user-images.githubusercontent.com/79330802/208974061-a4489fff-d75c-4450-ba26-9bcf4a77ff59.jpg)

**Comment by MarkusMG3** [comment]
Danke!

**Comment by DcFamas** [comment]
Gerät löschen und neu hinzufügen. Btw. ist das hier die falsche GitHub Page. Das gehört hierhin:
https://github.com/ioBroker/ioBroker.zigbee

Weiterhin ist das kein Issue sondern eher eine Frage.

**Comment by MarkusMG3** [comment]
Danke für deine Antwort.
Das Problem wurde durch ein neues Update behoben.
Danke! 
Haasen Markus
Unterwegs 

Am 28. Dezember 2022 11:28:36 MEZ schrieb DcFamas ***@***.***>:

**Comment by DcFamas** [comment]
Bitte noch dein Issue schließen. :)
