### ISSUE TITLE
Motion Detection Tile

### ISSUE THREAD

**Issue by Lou2401** [sbormann/ioBroker.iqontrol#26]
First of all thanks a lot for this very cool adapter. This was definitely what I was missing all the time. Easy to configure with a great output!

I am looking for a motion detection tile. I think I can use the Alarm tile. However an information what I would like to see there as well is the date and time when the last motion was detected. Either on the tile itself directly or in the opening box when you click on the tile.

![image](https://user-images.githubusercontent.com/7393999/57432015-e8233c80-7234-11e9-8270-d45f002abaf1.png)

You think that can be added?
Thanks a lot for your feedback!

Best regards
Marco

**Comment by DutchmanNL** [comment]
+1 I wanted to include mu motion sensor with brightness measurement.
In basic the tile "LightSensor" is working ok for it but not really the right icon (should be a moving person)

Would be great to :
- have a tile with motion detected (standstills & motion)
- time stamp of motion detected
- capability to add brightness ( most motion sensor also measure brightness )

**Comment by sbormann** [comment]
Should work now - except of time stamp. Will open a new issue for that.

**Comment by DutchmanNL** [comment]
confirmed 👍
