### ISSUE TITLE
Listen/Zähler spammen das log voll

### ISSUE THREAD

**Issue by DcFamas** [sbormann/ioBroker.iqontrol#261]
Hallo Sebastian,
seit gestern nutze ich die Funktion der Listen/Zähler. Zunächst hatte ich die Aktualisierungsrate auf 0 Sekunden, mittlerweile auf 1 Sekunde. Leider spammt diese Funktion das log von ioBroker voll. In meinem Fall wird nun jede Sekunde ein neuer Eintrag angelegt. Im Falle der 0 Sekunden waren es gut fünf Einträge pro Sekunde:

![grafik](https://user-images.githubusercontent.com/35306967/209965392-a95cdb1f-7fff-4de5-b11b-b1d6e49ae41c.png)

Ich glaube das logging des States kann komplett raus, oder?

Grüße

**Comment by sbormann** [comment]
Hi, benötigst Du die Aktualisierungsrate denn wirklich? Eigentlich aktualisieren sich die Counter automatisch, wenn sich etwas ändert. Das Intervall benötigt man nur in speziellen Situationen. Versuch es mal ohne.

**Comment by DcFamas** [comment]
Das wusste ich tatsächlich nicht, ich dachte das wäre ein Pflichtfeld. Hab entsprechend den Eintrag gelöscht, jetzt ist's Ruhe im Protokoll. Danke für deine Antwort! :)
