### ISSUE TITLE
Homeatic IP Control Mode

### ISSUE THREAD

**Issue by FujiHeavy** [sbormann/ioBroker.iqontrol#265]
Hallo, habe ein Problem mit dem Auto,Manuel und Boost Mode.
beim drücken eines dieser 3 knöpfe wird immer nur der Boost modus erneut gestartet, aber halt weder auto, noch der manuel modus

**Comment by frankhetterich** [comment]
Ich habe das selbe Problem. Ich habe lasse ein Gerät automatisch erstellen (HMIP WTH) und ändere danach den Typ auf Homematic IP Thermostat. 
Wenn ich dann auf einen der 3 Buttons klicke wird immer nur ein Boost ausgelöst

**Comment by sbormann** [comment]
Ist leider doch etwas komplizierter, als gedacht, bin aber dran.

**Comment by sbormann** [comment]
duplicat #251
