### ISSUE TITLE
Feature Request: Ändern des PowerStates beim Gerätetyp Media-Player/Fernbedienung

### ISSUE THREAD

**Issue by mllrmnn** [sbormann/ioBroker.iqontrol#267]
Hallo,  ich habe meinen AV-Receiver als Media-Player/Fernbedienung in iQontrol eingebunden, um bei geöffneten Dialog die entsprechenden Play/Pause etc. States steuern zu können. 

Nun ist es so, dass beim klicken auf das Kachel-Icon Play/Pause getoggelt wird, was bei einem reinen Player durchaus sinnvoll ist und bei mir in Verbindung mit einem HiFi-Berry auch Anwendung findet. Für meinen AV-Receiver fände ich es sinnvoll, dass man bei der Media-Player/Fernbedienung Kachel einstellen könnte ob Play/Pause oder der Power State getoggelt wird. Ist es möglich dies zu implementieren?

**Comment by sbormann** [comment]
Gute Idee. Habe ich gerade zum Testen auf Github hochgeladen. Bitte sag bescheid, ob es klappt wie gewünscht. Die Option findest Du unter den gerätespezifischen Optionen. vG

**Comment by sbormann** [comment]
Danke für die Rückmeldung!
