### ISSUE TITLE
IQontrol Blockly Popup closed bei StartURL

### ISSUE THREAD

**Issue by uwelingstaedt** [sbormann/ioBroker.iqontrol#268]
Hallo, ich habe ein Probelm mit den Popups aus Blockly. Popup wir angezeigt. Wartet auf meldung quittieren. Wenn aber dann die Start Url geladen wird, ist das Popup in iqontrol verschwunden. Trigger ich das Ereigniss vom Popup nochmal, so ist es wieder da. Ist das normal so?

**Comment by sbormann** [comment]
Hi, ja, das ist "by design" so. iQontrol überwacht den Popup-Datenpunkt auf Änderungen. 
Was wäre denn Dein usecase, ggf. fällt mir ja dazu was ein...

**Comment by uwelingstaedt** [comment]
Waschmaschine meldet fertig. Popup kommt. Sollte dann die start URL laden
oder die Ansicht wird aktualisiert ist das popup weg. Wäre gut wenn es es
merkt das es nicht quittiert wurde. Mit blockly Taste zum quittieren
erstellt. Klappt auch gut, solange die Seite nicht erneuert wird. Gruß Uwe

Sebastian Bormann ***@***.***> schrieb am Di., 21. Feb. 2023,
23:56:

**Comment by sbormann** [comment]
Hi, habe das Popup mal überarbeitet. Was Du vorhast, sollte nun mit den neuen persistent-Popups gehen:

Es gibt jetzt den neuen Datenpunkt `iqontrol.x.Popup.PersistentMessage`. Wenn man hier eine Nachricht eingibt, wird das Popup zwischengespeichert und bei jedem Start von iQontrol angezeigt, bis es bestätigt wird.

Man kann es auf verschiedene Weisen bestätigen:
* Durch Ablauf der Anzeigedauer (Duration)
* Durch Klick auf das Popup
Beides kann verhindert werden, wenn man den Datenpunkt `persistentUndismissible` auf true setzt. 

Dann kann man die Nachricht nur noch aktiv löschen. Dazu vergibt man in `persitentId` eine ID (beliebige Bezeichnung der Nachricht). Wenn man diese ID dann in `PERSISTENT_MESSAGES_DELETE_ID` einfügt, wir die gespeicherte Nachricht gelöscht. Fügt man hier "null" ein, werden alle Nachrichten gelöscht.

Zudem kann man eine Gültigkeitsdauer des Popups im Datenpunkt `PersistentExpires` angeben. Dies kann entweder ein Timestamp (Datum und Uhrzeit) sein oder eine Zeitdauer in Sekunden.

Es gibt noch den Datenpunkt PERSISTENT_MESSAGES_SHOW_ID, in den man eine ID schreiben kann, um dann eine gespeicherte Nachricht noch mal anzeigen zu lassen. Fügt man hier "null" ein, werden alle gespeicherten Nachrichten erneut angezeit.

Ferner gibt es noch zwei neue Optionen, die man auch bei normalen Popups nutzen kann: ClickKeepsOpen und ButtonClears. Die Beschreibung hierzu findet man in der Readme auf Github.


Ist jetzt zum Testen auf Github. Bitte mal testen und Rückmeldung geben, ob es läuft und Dein Problem löst.

Danke und Gruß

**Comment by uwelingstaedt** [comment]
Guten morgen, habe die Githubversion geladen und soweit durchgetestet. Musste den Blockly Baustein einmal löschen und neu einfügen. Danach funktioniert alles einwandfrei. Popups bleiben wie gewünscht vorhanden bis ich Sie durch betätigen anklicke. Auch die anderen Funktionen habe ich kurz getestet - sieht alles gut aus. Vielen Dank.

P.S. großes Lob für diese hervorragende Visalisierung
