### ISSUE TITLE
DataPoints in Dvice Names

### ISSUE THREAD

**Issue by Esto88** [sbormann/ioBroker.iqontrol#271]
**Describe the bug**  
Datapoint as Divice Name don´t behave linke discribed in the WIki:

![grafik](https://user-images.githubusercontent.com/11173026/218318728-f21c9b50-93e7-45bf-8406-01bfd716b560.png)

Testet all posibilitys but no one of them worked.

Installed Iqontroll: 
V2.1.0

**Comment by sbormann** [comment]
Please add a leading pipe-sign:
|{shelly.0.SHDM.....name|Shelly}

sorry the syntax is not very intuitive... it is
``Text while loading|Text after loading {iobrokerstate|fallback}``
