### ISSUE TITLE
[Feature request] link view to heading into another view

### ISSUE THREAD

**Issue by Breisgauer** [sbormann/ioBroker.iqontrol#273]
Hi, great adapter. May I raise this feature request for a future version of it:

CURRENT STATE
In the device list there is the option to link to another view by using "Linked View". When selected, a click on the device opens the configured view

FUTURE STATE
In the device list add the option to link to a section of another view by using "Linked View" and the "headers" configuration of the targeted view. When selected, a click on the device opens the configured view and jumps to the configured section

**Comment by sbormann** [comment]
Good idea. Will think about that!

**Comment by sbormann** [comment]
Habe es implementiert. War schwerer, als gedacht - viel Timing etc. (da ja teilweise die Elemente auf der Seite noch nachgeladen werden und sich damit ggf. der Anker-Punkt noch mal verschiebt etc.), aber bei mir lief es jetzt zuverlässig. Kannst Du mal testen? Danke und Gruß!

**Comment by Breisgauer** [comment]
Habe eben die Version von github installiert und ein paar schnelle Tests gemacht: Funktioniert super!
Ich teste noch etwas mit verschiedenen Devices und Netzwerkgeschwindigkeiten, um das Timing zu prüfen.
Vielen Dank soweit !!

**Comment by Breisgauer** [comment]
Läuft weiterhin ohne Probleme

**Comment by sbormann** [comment]
👍
