### ISSUE TITLE
Do not run with js-controller 5.0

### ISSUE THREAD

**Issue by GermanBluefox** [sbormann/ioBroker.iqontrol#276]
![image_2023-03-30_12-19-59](https://user-images.githubusercontent.com/4582016/228808391-e058be86-0d83-49a9-a9d9-3e58829fbeb4.png)

**Comment by Apollon77** [comment]
Yes, seems https://github.com/sbormann/ioBroker.iqontrol/blob/master/main.js#L1673 was always wrong but silently ignored in the past, not we check a bit better there and so the type do not match

**Comment by Apollon77** [comment]
@sbormann If you want to get an object getObjectAsync(id) is completely sufficient. The options are just needed for special behaviour if you e.g. ewant to limit it to a certain user or such. in your case in fact the options have no meaning because if you try to filter the type then this is not supported by getObject at all (and also had never). Right now you should get back 4 times the same object .... is this intended?

**Comment by foxriver76** [comment]
You are mixing lots of stuff like `getForeignObject` vs `getForeignObjects`

**Comment by sbormann** [comment]
yes, but in my opinion it makes sense. sometimes i need a specific object, sometimes all of them.

Is there any documentation how to use these functions? it's really time consuming to do it all by try'n'error.

**Comment by Apollon77** [comment]
As @foxriver76 already sdtated: getObject/getForeignObject (no "S" at the end!!) is just accessing the pure object via ID and works irrelevant of the object type! YOu aloways get the object if it is a valid ID.

getForeighObjects expects a Pattern as first parameter and allows to filter objects types as second parameter ("state" if not provided). But this only exists on that one method.

https://github.com/ioBroker/ioBroker.js-controller/blob/master/packages/controller/doc/classes/AdapterClass.md#getforeignobjectsasync

**Comment by sbormann** [comment]
Ok, thank you, i think i got it now. 
I did not know the documentation you sent me, many thanks for that.
And therefore i did not know that there is a difference in the syntax of getForeignObject and getFreignObjetcs.
I uploaded the corrected version on github for testing.

Many thanks!

**Comment by Apollon77** [comment]
Thank you!
