### ISSUE TITLE
iQontrol crashes after upgrade to iobroker.js 5.0.4

### ISSUE THREAD

**Issue by louisvangeldrop** [sbormann/ioBroker.iqontrol#280]

**Comment by louisvangeldrop** [comment]
<html>
<body>


host.raspberrypi4 | 2023-06-16 21:33:36.805 | error | instance system.adapter.iqontrol.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
iqontrol.0 | 2023-06-16 21:33:36.044 | error | Parameter "options" needs to be a real object but type "string" has been passed
iqontrol.0 | 2023-06-16 21:33:36.043 | error | Error: Parameter "options" needs to be a real object but type "string" has been passed at Validator.assertObject (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/validator.js:215:19) at Iqontrol.getObject (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:2447:35) at /opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js:2007:16 at new Promise (<anonymous>) at Iqontrol.getObjectAsync (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js:2006:16) at Iqontrol.createOrUpdateObject (/opt/iobroker/node_modules/iobroker.iqontrol/main.js:1673:25) at Iqontrol.createInfoConnection (/opt/iobroker/node_modules/iobroker.iqontrol/main.js:413:14) at Iqontrol.onReady (/opt/iobroker/node_modules/iobroker.iqontrol/main.js:1779:14) at Iqontrol.emit (node:events:513:28) at Iqontrol._callReadyHandler (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:9017:18)
iqontrol.0 | 2023-06-16 21:33:36.038 | error | unhandled promise rejection: Parameter "options" needs to be a real object but type "string" has been passed
iqontrol.0 | 2023-06-16 21:33:36.036 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().


</body>
</html>

**Comment by sbormann** [comment]
I uploaded a fix for this. Please try with actual github-version and provide feedback. Thanks!

**Comment by Sundancer78** [comment]
The Github version works for me too.
js-controller: 5.0.5
iqontrol: 2.2.0 from github
Node.js: v18.16.0

**Comment by louisvangeldrop** [comment]
The github version works. 
js-controller: 5.0.4
Thx for the prompt update.

**Comment by louisvangeldrop** [comment]
It also works with js-controller 5.0.5

**Comment by sbormann** [comment]
👍
