### ISSUE TITLE
Administration Optimization

### ISSUE THREAD

**Issue by jensfr1** [sbormann/ioBroker.iqontrol#29]
Hi, 
first of all I really like the tool as it is super simple to setup. 
Some room for improvement in the Administration. 

1) Sorting of Devices. Maybe a drag and drop sorting or numbering. It takes long to sort by Name and Heading if you have many devices. Maybe think about a tree view (2 levels)
2) Copy of Views and Devices or copy multiple dvices into a new view. 
3) Possibility to move toolbar to the top or left / right.

Thanks, Jens

**Comment by sbormann** [comment]
1. Drag and drop works with upcoming version.
2. Copying views is planned.
3. Toolbar positioning is not so easy because the jquery mobile framework doesn't support it (as far as i know), so i think i will not be able to realize this in the near future
Many thanks and greetings!
