### ISSUE TITLE
Add auto configuration for shelly devices

### ISSUE THREAD

**Issue by DutchmanNL** [sbormann/ioBroker.iqontrol#3]
Currently shelly devices are not auto configured, please find below the tree of an regular shelly device (shelly 1)

<img width="1478" alt="Schermafbeelding 2019-04-28 om 16 57 26" src="https://user-images.githubusercontent.com/7318445/56866195-db9e1900-69d6-11e9-9095-92b019624ca1.png">

**Comment by sbormann** [comment]
Could you please test with 0.0.7 if it works?

**Comment by DutchmanNL** [comment]
> Could you please test with 0.0.7 if it works?

looks great with 0.0.8, please note I have only the shelly 1 so not able to test other devices of the shelly manufacture for you.

closing this one

<img width="1021" alt="Schermafbeelding 2019-04-29 om 13 16 10" src="https://user-images.githubusercontent.com/7318445/56892826-13fa3180-6a81-11e9-8709-12774b34a028.png">
