### ISSUE TITLE
Timer implmentation in Light Switch

### ISSUE THREAD

**Issue by RESDE** [sbormann/ioBroker.iqontrol#307]
Hi,

I´m wondering how to achieve an timer based on a light which is already set up. To add an additional buttion seems not very easy to handle as the user would have to handle 2 tiles for on state.
Are there already a solution worked out?

Regards
Reiner

**Comment by mllrmnn** [comment]
How about using the "Additional Controls" feature?

**Comment by RESDE** [comment]
O.K. thanks. I did activate the option show always but no timer feature has beend available = to be chosen. Thanks for additonal detials maybe a bit more detail as I´m a rookie startig roght now with iQcontrol recently...

**Comment by mllrmnn** [comment]
Ah okay now i know what you mean. You could programm your Timer or whatever you want with javascript/blocky and then add the necessary States to iqontrol to trigger/control your task

**Comment by RESDE** [comment]
mmmmh I though Iqontrol could save me the detour via JSscript etc...
