### ISSUE TITLE
Konfigurationen im Frontend - kachelgröße

### ISSUE THREAD

**Issue by liv-in-sky** [sbormann/ioBroker.iqontrol#31]
aus forum:

könnte man die größe der kachen einführenl in der config page einstellen - kacheln : groß mittel klein

**Comment by jensfr1** [comment]
I guess it would also be good if a tile could be splitted in 2 or 4 parts.

e.g. For TV volume 1 tile with with for buttons would be sufficent for me like vol-up, vol-down, mute and on/off. I dont need a lot of thext as the incons would be sufficent.

**Comment by sbormann** [comment]
Made another solution:
Tiles will be zoomed to fit to the screen. 
I know, splitted or joyned tiles are another thing, but i think this does not fit to "philolophy" of iqontrol :)

**Comment by Moritz-Staat** [comment]
Hi! I dont know if you are planning on adding an option like this soon. But till then you can easily work around the problem and use the custom CSS segment. I did that and got the following results. It is by far not the best solution but optimal for small usecases like mine. 
![Screenshot_2024-07-03-10-18-27-177](https://github.com/sbormann/ioBroker.iqontrol/assets/132384832/c2582df4-66d6-4034-bc0a-c302cf820459)
![Screenshot_2024-07-03-10-18-35-789](https://github.com/sbormann/ioBroker.iqontrol/assets/132384832/9e59c0cc-6a43-46ec-9b6d-27af51b34268)


Code:
.iQontrolDevice, .iQontrolDeviceLinkToToggle {
    position: relative;
    width: 190px !important;
    height: 190px !important;
    max-width: 190px !important;
    max-height: 190px !important;
    min-width: 190px !important;
    min-height: 190px !important;
}

.iQontrolDeviceIcon {
    width: 140px !important;
    height: 140px !important;
    margin-bottom: 5px; 
}
.iQontrolDeviceName {
    position: relative;
    font-size: 20px !important;
    padding-top: 100px;
}

.iQontrolDeviceInfoAText, .iQontrolDeviceUnreach.active{
width: 20px !important;
height: 20px !important;
margin-left: 90px !important;
}

.iQontrolDeviceInfoAIcon{
width: 20px !important;
height: 20px !important;
margin-left: 80px !important;
}

.iQontrolDeviceState{
font-size: 15px !important;
margin-left: 70px !important;
}
