### ISSUE TITLE
Instanzeinstellungen laden nicht mehr

### ISSUE THREAD

**Issue by EinfachNurKlaus** [sbormann/ioBroker.iqontrol#312]
Seit kurzer Zeit, vermutlich - nach den letzten iob Updates - läd die Einstellungseite nicht mehr. Beim Öffnen der Seite erscheint kurz die normale Seite, verschwindet aber und wird zu Einstellung laden - mehr passiert nicht.
![fehler2](https://github.com/sbormann/ioBroker.iqontrol/assets/146920071/f307e1e8-efad-47aa-b596-6d0c09a0ca9d)
Die Vis ist normal erreichbar und funktioniert.

Die Konsole loggt gleichzeitig folgenden Fehler
![fehler1](https://github.com/sbormann/ioBroker.iqontrol/assets/146920071/8d02442c-d263-482d-a23c-2f4dc1de3d04)

Zur Analyse habe ich in eine leere Windows-VM iob mit dem neusten Installer 3.2 installiert und nur eine leere iqontrol Instanz hinzugefügt - identischer Fehler.

Grüße

**Comment by rotrichi** [comment]
Hallo Ich habe das gleiche Problem wie [EinfachNurKlaus](https://github.com/EinfachNurKlaus)
Gibt es eine Lösung?

**Comment by m2003b** [comment]
Auch bei mir das gleiche Verhalten, mit node 20 und auch mit der 18 funktioniert es im jetzigen Stand (jun 2024) von Iobroker nicht. Ich hatte dazu gestern ein Thema im IOB Forum eröffnet. 
Grüße

**Comment by errorflash** [comment]
Bei mir auch, dachte es liegt am RPi oder des OS aber bei beiden das gleiche. Auch bei mir sieht es so aus!

**Comment by di02p** [comment]
Gleiches Problem auf RPi 3 und RPi5 (Debian), bleibt beim Start hängen.
Fehler: [getObjectView] ERROR: TypeError: Cannot read properties of null (reading 'root')

**Comment by gartenjoe** [comment]
Lässt sich auch nicht mehr richtig installieren. Hängt an der gleichen Stelle . Schade wollte mich gerade damit befassen.

**Comment by EinfachNurKlaus** [comment]
da leider keine Antwort / Hilfe / Lösung in Sicht ist, habe ich nun selber mal nachgeschaut.
Es scheint eine Socket Anpassung im IOB stattgefunden zu haben, mit der der Adapter nicht klar kommt.

Ohne mich jetzt komplett reinzuarbeiten hier meine "Quick and Dirty" Lösung (läuft bei mir auf einem WindowsServer, sollte aber auch unter Linux helfen, ggf. andere Pfade) - Bei mir läufts damit, ohne Gewähr und wie immer beruhigt eine Sicherung die Nerven!

Folgende Datei editieren
/ioBroker/iobroker-data/files/iqontrol.admin/index_m.js 

In Zeile 2970++ werden auf Basis von Socketdaten Links zusammen gebaut, das schlägt fehl

Original: 
previewLink = (result[bestInstance].native.secure ? "https://" : "http://") + location.hostname + ":" + result[bestInstance].native.port + "/iqontrol";
var connectionLink = (result[bestInstance].native.secure ? "https://" : "http://") + location.hostname + ":" + result[bestInstance].native.port;
var forceWebSockets = result[bestInstance].native.forceWebSockets;

Die habe ich durch feste Daten meiner Installation ersetzt:
previewLink = "http://[meine IOBroker IP]:8082/iqontrol";
var connectionLink = "http://[meine IOBroker IP]:8082"
var forceWebSockets = false;

Speichern, IOB neustarten -> Läuft.

Hoffe das hilft manchem weiter. Noch mehr hoffe ich, dass der Adapter weiter am Leben gehalten wird da sonst echt nice!

Cheers

**Comment by errorflash** [comment]
> da leider keine Antwort / Hilfe / Lösung in Sicht ist, habe ich nun selber mal nachgeschaut. Es scheint eine Socket Anpassung im IOB stattgefunden zu haben, mit der der Adapter nicht klar kommt.
> 
> Ohne mich jetzt komplett reinzuarbeiten hier meine "Quick and Dirty" Lösung (läuft bei mir auf einem WindowsServer, sollte aber auch unter Linux helfen, ggf. andere Pfade) - Bei mir läufts damit, ohne Gewähr und wie immer beruhigt eine Sicherung die Nerven!
> 
> Folgende Datei editieren /ioBroker/iobroker-data/files/iqontrol.admin/index_m.js
> 
> In Zeile 2970++ werden auf Basis von Socketdaten Links zusammen gebaut, das schlägt fehl
> 
> Original: previewLink = (result[bestInstance].native.secure ? "https://" : "http://") + location.hostname + ":" + result[bestInstance].native.port + "/iqontrol"; var connectionLink = (result[bestInstance].native.secure ? "https://" : "http://") + location.hostname + ":" + result[bestInstance].native.port; var forceWebSockets = result[bestInstance].native.forceWebSockets;
> 
> Die habe ich durch feste Daten meiner Installation ersetzt: previewLink = "http://" + location.hostname + ":8082/iqontrol"; var connectionLink = "http://" + location.hostname + ":8082" var forceWebSockets = false;
> 
> Speichern, IOB neustarten -> Läuft.
> 
> Hoffe das hilft manchem weiter. Noch mehr hoffe ich, dass der Adapter weiter am Leben gehalten wird da sonst echt nice!
> 
> Cheers

besten Dank auch für mich als Linux Noob machbar und hat geklappt!! Endlich kann ich weiter machen.

Raspi 4 1GB Ram mit ioBroker funzt!!

**Comment by gartenjoe** [comment]
Super die Lösung von EinfachnurKlaus. Erfolg auf ganzer Linie. Danke

**Comment by rotrichi** [comment]
Hallo zusammen
Das hört sich ja echt gut an ,aber wie muss ich da genau vor gehen ich hab davon keine Ahnung !?

**Comment by errorflash** [comment]
War per SSH auf meinem raspi und habe unter /opt die datei mit nano geöffnet und die angegebenen Zeilen editiert und dann abgespeichert

**Comment by rotrichi** [comment]
ok aber bei mir läuft es auf proxmox

**Comment by rotrichi** [comment]
Kannst Du mir sagen was ich in der Console machen muss, wie gesagt ich habe davon keine Ahnung

**Comment by rotrichi** [comment]
Kann mir keiner Helfen ???

**Comment by EinfachNurKlaus** [comment]
Auf welcher Virtualisierung das läuft ist egal, interessant ist das Zielbetriebssystem und woher du kommst. Läuft auf dem Proxmox ein linux-container (sehr wahrscheinlich) ist ssh der Weg. Ist dein Arbeitsrechner ein Pinguin oder Mac, geht die Verbindung direkt. Unter Windows brauchst Du Hilfe von z.B. Putty, kitty, etc. Für Details bin ich allerdings der falsche Ansprechpartner. Bei mir läuft das alles nicht ohne Grund auf einem Windows Core Server. :-)

**Comment by mattuschek** [comment]
> ok aber bei mir läuft es auf proxmox

Wie kommst Du denn normalerweise per Kommandozeile zum ioBroker?

Bei mir läuft ioBroker im LXC-Container auch auf Proxmox.
Ich gehe von Windows aus mit PuTTY zum ioBroker.

**Comment by rotrichi** [comment]
Über die proxmox Konsole des Containers !


mattuschek ***@***.***> schrieb am Fr., 14. Juni 2024, 06:41:

**Comment by mattuschek** [comment]
@errorflash hat doch oben geschrieben, wo Du die Dateien findest.
Dateien liegen in /opt
`ls -lh /opt`

Und @EinfachNurKlaus hat oben sogar den ganzen Pfad genannt.
`ls -lh /opt/iobroker/iobroker-data/files/iqontrol.admin/index_m.js`

Dann die Datei mit nano editieren.
`nano /opt/iobroker/iobroker-data/files/iqontrol.admin/index_m.js`

**Comment by vepman** [comment]
@EinfachNurKlaus  Klasse, dass du Lösung hier gepostet hast. Top Job. Danke 👍

**Comment by mcm1957** [comment]
Link to repo:
https://forum.iobroker.net/topic/75088/iqontrol-h%C3%A4ngt-fest-nach-neuinstallation

**Comment by rotrichi** [comment]
> @EinfachNurKlaus Klasse, dass du die Lösung hier gepostet hast. Top-Job. Danke 👍

Hallo Leute  kann vielleicht mal einer genauer beschreiben was da gemacht werden muss 
Meiner Meinung nach gibt es viele Leute die das Problem mit dem Adapter haben. aber viele können oder trauen sich nicht zu mit dem Nano Editor zu Arbeiten.
Es wäre schön wenn sich einer von den Spezialisten mal die mühe machen würde und das für uns kleine Anwender zu erklären!!!
Danke

**Comment by vepman** [comment]
@rotrichi
> Hallo Leute kann vielleicht mal einer genauer beschreiben was da gemacht werden muss Meiner Meinung nach gibt es viele Leute die das Problem mit dem Adapter haben. aber viele können oder trauen sich nicht zu mit dem Nano Editor zu Arbeiten. Es wäre schön wenn sich einer von den Spezialisten mal die mühe machen würde und das für uns kleine Anwender zu erklären!!! 

@EinfachNurKlaus hat das doch oben erklärt. Ich bin auch nur "ein kleiner Anwender", 
aber mit irgendeinen Editor sollte man das schon hinkriegen.
3 Zeilen in der 'index_m.js' ab Zeile 2970 ersetzen, sollte wohl auch ein "Nicht-Spezialist" bewältigen können.
Erst wollte ich ja bei dem Tonfall nicht antworten. 🙄

**Comment by mattuschek** [comment]
> Hallo Leute kann vielleicht mal einer genauer beschreiben was da gemacht werden muss Meiner Meinung nach gibt es viele Leute die das Problem mit dem Adapter haben. aber viele können oder trauen sich nicht zu mit dem Nano Editor zu Arbeiten. Es wäre schön wenn sich einer von den Spezialisten mal die mühe machen würde und das für uns kleine Anwender zu erklären!!! 

Befehle siehe hier:
https://github.com/sbormann/ioBroker.iqontrol/issues/312#issuecomment-2168466462

Dann die 3 genannten Zeilen von hier ersetzen:
https://github.com/sbormann/ioBroker.iqontrol/issues/312#issuecomment-2163035412

**Comment by greatfireball** [comment]
Wenn ich an diesem Wochenende Zeit finde, kann man vielleicht einen Pull-Request zusammenbauen... Aber ich will mal nicht zu viel versprechen

**Comment by rotrichi** [comment]
> ls -lh /opt/iobroker/iobroker-data/files/iqontrol.admin/index_m.js



> @rotrichi
> 
> > Hallo Leute kann vielleicht mal einer genauer beschreiben was da gemacht werden muss Meiner Meinung nach gibt es viele Leute die das Problem mit dem Adapter haben. aber viele können oder trauen sich nicht zu mit dem Nano Editor zu Arbeiten. Es wäre schön wenn sich einer von den Spezialisten mal die mühe machen würde und das für uns kleine Anwender zu erklären!!!
> 
> @EinfachNurKlaus hat das doch oben erklärt. Ich bin auch nur "ein kleiner Anwender", aber mit irgendeinen Editor sollte man das schon hinkriegen. 3 Zeilen in der 'index_m.js' ab Zeile 2970 ersetzen, sollte wohl auch ein "Nicht-Spezialist" bewältigen können. Erst wollte ich ja bei dem Tonfall nicht antworten. 🙄

Es tut mir sehr leid wenn ich den falschen Tonfall gewählt habe !
Ich will doch niemandem zu nahe treten ! aber es gibt ja bestimmt viele Leute die so wie ich einfach nur einen iobroker  irgendwo laufen haben und sich den Adapter installiert haben um eine Visualisierung für ihre Haus Steuerung zu haben .
Du kannst doch nicht davon ausgehen das jeder in einem editor diese dateien verändern kann. Ich weis noch nicht mal wie ich in die richtige zeile komme (-:

**Comment by sjfm-design** [comment]
nachdem es mich nach dem admin update auf 7.0.2 auch erwischt hat, änderung gemacht, läuft wieder!
thnx @EinfachNurKlaus 
@rotrichi von ein bißchen eigeninitiative kann man schon ausgehn!
da mir die suche der zeilen zu mühsam war, bin ich halt per FTP programm auf den server gegangen, rein in den richtigen ordner, die datei sicherheitshalber gesichert und dann editiert.
fertig war der lack...

**Comment by errorflash** [comment]
Viele Wege führen nach Rom

**Comment by rotrichi** [comment]
Schlaue Sprüche schreiben hilft bestimmt allen weiter !
Übrigens läuft's bei mir auch wieder


da_Woody ***@***.***> schrieb am Mi., 26. Juni 2024, 07:27:

**Comment by mcm1957** [comment]
@rotrichi 
> Übrigens läuft's bei mir auch wieder 

Was hat sich geändert?
Was war die Ursache?
Was hast du getan damit es wieder läuft?

**Comment by rotrichi** [comment]
Einfach wie schon beschrieben die Dateien mit dem Nanoeditor geändert
Ich hatte nur das Problem das ich mich damit nicht ausgekannt habe aber ich
hab's trotz der großzügigen Hilfe von den Profis hinbekommen


Martin M. ***@***.***> schrieb am Mi., 26. Juni 2024, 07:49:

**Comment by mcm1957** [comment]
Ok, dann mal zusammengefasst:

**Der Adapter weist zur Zeit einen (eher schweren) Fehler auf der die Benutzung ohne manuellen Eingriff in die ausgelieferten Dateien blockiert. Ein Update ist daher notwendig.**

Details und Workaround siehe oben,

**Comment by rotrichi** [comment]
Das kann man so sagen !


Martin M. ***@***.***> schrieb am Mi., 26. Juni 2024, 08:00:

**Comment by m2003b** [comment]
Besten Dank an  @EinfachNurKlaus. 
Super Brückenlösung

**Comment by Lucky-ESA** [comment]
Hallo zusammen,
habe bei mir auch den Fehler was mir wohl jetzt erst aufgefallen ist. Bitte kein PR mit der o. g. Änderung erstellen. Es ist sinnvoller die Ursache zu finden und zu beheben. Habe mir das heute mal kurz angesehen und habe keine Lösung gefunden. Werde mal im Dev Chat nachfragen. Es wir noch schlimmer wenn der Javascript 9.x erscheint, dann werden wohl die Blocklys unter sendTo nicht mehr funktionieren bzw. vielleicht sogar alles nicht mehr.
Was ich allerdings noch nicht ganz verstanden habe, wenn ihr ins Adminmenue wechselt, dann müsst ihr doch den Error im Log erhalten...Kann den hier aber nicht finden...

Für mich sieht es hier nach ein Admin Adapter Thema aus, welcher diesen Fehler verursacht.

**Comment by EinfachNurKlaus** [comment]
> ... Es ist sinnvoller die Ursache zu finden und zu beheben. ...
> Habe jetzt mal ein [issues](https://github.com/ioBroker/ioBroker.socket-classes/issues/37) erstellt.

Hallo zusammen,
ja absolut, sehr gut. Ich hatte auch nur kurz durchgeschaut - da mir einfach die Zeit fehlt und ich auch nicht der js Guru bin - dabei nur gemerkt, dass übergebene Objekte leer sind. Es sind also sicher Änderungen am io-unterbau die Ursache.
Als aber keine Rückmeldung kam und ich ungeduldig bin, diese "Brücke" kommuniziert, für alle die auch nicht warten wollen.
Ich befürchte auch, dass die Probleme mit iqontrol bei den kommenden größeren Updates im iob zunehmen werden, wenn da keiner drauf schaut. Das macht mir Sorge, ob die Zeit die mittlerweile in meiner visu steckt verbrannt ist.

**Comment by greatfireball** [comment]
Gab eine neue Version des Admin Adapters (v7.0.7) damit lassen sich die Einstellungen von iqontrol (v2.3.0) wieder ohne manuelle Anpassung aufrufen.

Danke für das Issue @Lucky-ESA

**Comment by mcm1957** [comment]
https://github.com/ice987987/ioBroker.husqvarna-automower/issues/172

**Comment by mcm1957** [comment]
Und natürlich auch Danke an @bluefox für den raschen Fix.

**Comment by EinfachNurKlaus** [comment]
Fantastische Neuigkeiten. Getestet! Klappt! Vielen Dank. Man muss es nur an der richtigen Adresse platzieren! :-) Damit können wir diesen Punkt hier zu mindestens abhaken.
