### ISSUE TITLE
automatischer Seitenwechsel 

### ISSUE THREAD

**Issue by IQontrol-Nutzer** [sbormann/ioBroker.iqontrol#315]
Hallo, danke für die super IQontrol Visualisierung!
Nur durch diese Visu konnte ich als Neueinsteiger alles so visualisieren, wie ich es mir vorgestellte habe!

Jedoch stehe ich vor einem Problem mit dem automatischen Seitenwechsel....

Da ich nicht möchte, dass sich bei meinen neuen Geräten die Hauptseite "einbrennt" habe ich mir gedacht ich nutze die automatische Seitenwechsel-Funktion, als Schutz.
Meine Idee war daher, dass ich die Seiten im Minutentakt durchlaufen lasse...
nur bekomme ich das irgendwie nicht ganz hin mit dieser Funktion?

hat irgendwer eine Idee wie ich das umsetzen kann?

**Comment by Sascha-U** [comment]
Du kannst über die URL Parameter nutzen. Allerdings ist da nur eine Einstellung möglich nach welcher Zeit wieder zurück auf eine bestimmte Seite gewechselt werden soll. Also z.B. wenn du eine Homepage hast. 
returnAfterTimeTreshold=<time in seconds>
returnAfterTimeDestiationView=<viewID>
genauer ist es in der Anleitung beschrieben unter URL. Ich nutze das weil ich mir ein Widget gebaut habe das mir die Uhrzeit anzeigt. Wenn ich die Ansicht wechsele um etwas zu steuern, wird nach 20 Sekunden zurück auf die Seite mit der Uhrzeit gewechselt. Ansonsten wäre noch eine Option falls Du Wallpanel als Kiosk Browser Nutzt über ein Script die url zu ändern und einen Refresh anzustoßen.

**Comment by IQontrol-Nutzer** [comment]
Danke erstmals für die Antwort!

Das bedeutet, so wie ich es mir vorstellen würde, die Seiten / Ansichten im Minutentakt durchlaufen zu lassen, ist nicht irgendwie anders möglich?

Bin dann auch noch drauf gekommen, dass es dann sowieso nicht über die Android App funktioniert, da dort auch nur automatischer Seitenwechsel nach X Minuten auf die Startseite zum Auswählen gibt....

Schade...

Wie macht ihr das, dass euer Display nicht einbrennt?
Hatte ein älteres Tablet und dort sind die Gerätekacheln schon nach ein paar Tagen eingebrannt....

Bitte um Vor-Ratschläge bzw Ideen....
Danke euch!

**Comment by mcm1957** [comment]
@IQontrol-Nutzer 

Zur Lösung geb ich mal das Stichwort Bildschirmschoner.

Ansonsten bitte Diskussionen zu "wie geht das / wie macht ihr das etc im FORUM führen - wo du die Frage ja eh auch gestellt hast. Issues hier dienen zum Erfassen von Fehlern oder Featurevorschlägen und ersetzen kein Diskussionsforum.

@IQontrol-Nutzer 
Da anscheinend kein Problem bzw. kein Fehler vorliegt wäre es nett, wenn du das Issue wieder schließt. iQontrol hat derzeit sowieso ein kleines Wartingsproblem (zu wenig Zeit des Dev wahrscheinlich) und die Übersicht über echte Fehler ist schwieriger wenn Diskussionsissues existieren. DANKE.

**Comment by IQontrol-Nutzer** [comment]
mit einfm Bildschirmschoner sehe ich ja meine Visualisierung nicht?
Und wenn man genau darüber nachdenkt....ist meine Idee ja nicht falsch oder verkehrt...
oder etwa doch?

und OK, das war mir nicht bewusst...
