### ISSUE TITLE
Mehrere Schalter/Checkboxen unter  ADDITIONAL_CONTROLS anlegen

### ISSUE THREAD

**Issue by Knallix** [sbormann/ioBroker.iqontrol#322]
Guten Tag,

wäre es möglich als Ansatz z.B. in den  "ADDITIONAL_CONTROLS" mehrere Schalter/Checkboxen zu erstellen, wo dann jeweils der Wert gesendet wird, wenn man den "STATE"  vom Schalter auf True setzt ?

Vielen Dank

![image](https://github.com/user-attachments/assets/0a8a8b9d-b4cf-478c-ac55-185e19a02864)

oder gibt es eine andere Möglichkeit so etwas zu realisieren ?

Könnte dann so aussehen:

![image](https://github.com/user-attachments/assets/d4df93f8-1b2e-4cbc-82bc-0ac3a6b33697)

**Comment by mllrmnn** [comment]
Hi, ich nehme an unter den Schaltern ist ein Textfeld in dem true steht? Falls ja musst du den Datentyp vom verlinkten Objekt auf bool setzten. Die Anzeige in iQontrol liest den aus und passt die Anzeige dann entsprechend an( Textfeld, Button, Slider,...)

**Comment by Knallix** [comment]
Doch hast du verstanden :). Danke für den Hinweis 👍 .

Hier die Lösung:
![image](https://github.com/user-attachments/assets/a8e77186-94bf-45d0-89c5-b88a5acefb5b)

![image](https://github.com/user-attachments/assets/200508d8-75e0-41ed-afbe-32a3fccfa69c)
