### ISSUE TITLE
Add icon translation

### ISSUE THREAD

**Issue by SchumyHao** [sbormann/ioBroker.iqontrol#36]
**Describe the bug**  
When I set my ioBroker language to Chinese. It seems only adapter admin page is translated.
In frontend, Language still Germany.
<img width="514" alt="trans" src="https://user-images.githubusercontent.com/4982108/57867733-3be4e580-7834-11e9-8c4c-c6c40e94620f.png">

**To Reproduce**  

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by sbormann** [comment]
Thank you, will be fixed in next version - then system language of iobroker will be loaded and used.
