### ISSUE TITLE
Add timestamp

### ISSUE THREAD

**Issue by sbormann** [sbormann/ioBroker.iqontrol#39]

**Comment by sbormann** [comment]
Added in 0.0.34

**Comment by Lou2401** [comment]
I've updated to 0.0.34 but can't see where or how the timestamp can be added or accessed.

**Comment by sbormann** [comment]
![image](https://user-images.githubusercontent.com/49171332/59626359-f1f56500-913b-11e9-98af-eba6ca199b08.png)

**Comment by Lou2401** [comment]
Hi Sebastian,

Danke! Ich hatte es zunaechst auf dem Handy versucht. Dort funktioniert bei mir leider das neue force touch Menue nicht. Auch nicht durch langes druecken. Auf dem PC hingegen klappt es. Was koennte das sein? Ich nutze ein Honor 9 mit Android 9.

VG
Marco

**Comment by sbormann** [comment]
Hi, schau mal hier, das ist die Homepage vom verwendeten Plugin zur Druckerkennung. Gehen da die Beispiele?

https://pressurejs.com/index.html#examples

**Comment by Lou2401** [comment]
Guten Morgen,

ja, die Beispiele dort funktionieren. Dort werden sogar unterschiedliche Werte gezeigt, wenn ich unterschiedlich fest auf das Display druecke.

VG
Marco

**Comment by sbormann** [comment]
Hi,
Funktioniert auch Beispiel
5. "Deep" or Force Press?

Das ist die Methode, die ich aktuell verwende.

Lg

--
Von meinem iPhone aus gesendet

Am 18.06.2019 um 06:30 schrieb Lou2401 <notifications@github.com<mailto:notifications@github.com>>:


Guten Morgen,

ja, die Beispiele dort funktionieren. Dort werden sogar unterschiedliche Werte gezeigt, wenn ich unterschiedlich fest auf das Display druecke.

VG
Marco

**Comment by Lou2401** [comment]
Hi,
Ne. Das 5. Beispiel funktioniert leider nicht.
VG

**Comment by sbormann** [comment]
Hi,
probier mal, ob es mit der 0.0.35 geht?
VG

**Comment by Lou2401** [comment]
Hi Sebastian,

leider geht es auch mit deinem 0.0.35 Update nicht.

VG
Marco

**Comment by sbormann** [comment]
Sorry, dass sich das so schwierig gestaltet. Geht es mit der 0.0.36 vielleicht?

**Comment by Lou2401** [comment]
Hallo, leider nicht. Auch mit der 0.0.37 nicht.
Wie gesagt ich nutze den Chrome. Hier gibt es keine Reaktion.
Ich hab jetzt mal den Firefox installiert. Dort funktioniert der force press (lang anhalten). Allerdings funktioniert das einfache, kurze Druecken dort nicht

**Comment by sbormann** [comment]
Nächster Versuch mit der 0.0.38. Hätte nicht gedacht, dass das so schwierig wird. Das Problem ist, dass Android die APIs bislang nur sehr rudimentär implementiert hat und viele Hersteller deshalb eigene Schnittstellen eingebaut haben - und jede ist irgendwo im Detail etwas anders...

**Comment by Lou2401** [comment]
Leide noch immer nicht... Sorry!
