### ISSUE TITLE
Warnung EISDIR

### ISSUE THREAD

**Issue by sigi2345** [sbormann/ioBroker.iqontrol#43]
Hallo, die Warnung kommt immer wieder? Windows System

Cannot | 2019-05-29 15:38:15.016 | warn | read file iqontrol / images: {"errno":-4068,"code":"EISDIR","syscall":"read"}
-- | -- | -- | --

**Comment by sbormann** [comment]
Bei welchen Gelegenheit kommt die Fehlermeldung? Das hatte ich mal, wenn ich einem View kein Hintergrundbild zugewiesen hatte. Das checkt das Frontend aber inzwischen, seither habe ich die Fehlermeldung nicht mehr.

**Comment by sigi2345** [comment]
> Bei welchen Gelegenheit kommt die Fehlermeldung? Das hatte ich mal, wenn ich einem View kein Hintergrundbild zugewiesen hatte. Das checkt das Frontend aber inzwischen, seither habe ich die Fehlermeldung nicht mehr.

Alle haben einen Hintergrund, Meldung kommt sporadisch.

**Comment by sbormann** [comment]
Alles klar. Wenn Dir eine Systematik auffällt, welche Aktion die Fehlermeldung triggert, sag mir bescheid. Im Moment habe ich keine Idee, woher die Meldung kommt.

**Comment by sigi2345** [comment]
> Alles klar. Wenn Dir eine Systematik auffällt, welche Aktion die Fehlermeldung triggert, sag mir bescheid. Im Moment habe ich keine Idee, woher die Meldung kommt.

Fehler kommt jetzt bei jeden Start von iQcontrol

**Comment by sigi2345** [comment]
Aber im Prinzip ist es nur eine Warnung, kann geschlossen werden denke ich.

**Comment by sbormann** [comment]
Fixed with 0.1.8
