### ISSUE TITLE
State für Rolle Switch wird von 1=>0 nicht übergeben

### ISSUE THREAD

**Issue by chefkoch009** [sbormann/ioBroker.iqontrol#49]
Wenn ich im Browser auf ein Switch Element klicke, dann öffnet sich ein kleines Fenster mit einem switch darin. Ändert man diesen von 0 =>1 dann funtkioniert es. Von 1=>0 funktioniert es nicht.

Haben in der index.js folgendes geändert:

`line 2036   if(typeof states[_linkedStateId].val == 'number'){`
`line 2037   --  if(newVal) newVal = 1; else newVal = 0;`
`line 2038   ++   if(newVal && newVal === "true" ) newVal = 1; else newVal = 0; `
`line 2039   }`

Nun funktioniert es.

Browser Firefox, Chrome.

**Comment by sbormann** [comment]
Danke, wird in der nächsten Version gefixed. VG!
