### ISSUE TITLE
Homematic does not work properly

### ISSUE THREAD

**Issue by gujiys** [sbormann/ioBroker.iqontrol#52]
![211](https://user-images.githubusercontent.com/50275040/59967877-704e6e80-9563-11e9-9181-bd2c4c4db9bc.png)
![212](https://user-images.githubusercontent.com/50275040/59967879-70e70500-9563-11e9-9e85-dfa6ef2854a7.png)

**Comment by sbormann** [comment]
Try normal thermostat as homematic-thermostat is only for Homematic products.

**Comment by gujiys** [comment]
![30](https://user-images.githubusercontent.com/50275040/60047495-70ce3d00-96fc-11e9-9f97-e9a02e360f79.png)

**Comment by sbormann** [comment]
Hi, what exactly is not working? What is mode and power? Please send the RAW of the datapoint.

Von: gujiys <notifications@github.com>
Gesendet: Montag, 24. Juni 2019 21:51
An: sbormann/ioBroker.iqontrol <ioBroker.iqontrol@noreply.github.com>
Cc: Sebastian Bormann <sebastian@bormann.net>; Comment <comment@noreply.github.com>
Betreff: Re: [sbormann/ioBroker.iqontrol] Homematic does not work properly (#52)


[30]<https://user-images.githubusercontent.com/50275040/60047495-70ce3d00-96fc-11e9-9f97-e9a02e360f79.png>

**Comment by sbormann** [comment]
No further feedback - therefore closed. Please reopen, if the issue persists.
