### ISSUE TITLE
Error in iQontrol Konfiguration: "Keine socket.io Instanz gefunden"

### ISSUE THREAD

**Issue by AlexStephenLytton** [sbormann/ioBroker.iqontrol#54]
Seit dem Update auf Version 0.0.39 kann ich die Konfiguration der Instanz nicht mehr bearbeiten - es er scheint die Fehlermeldung "Keine socket.io-Instanz gefunden" als Popup sobald ich versuche, die Konfiguration in der Instanz-Ansicht zu öffnen.

In der web.0 Instanz steht die Option für socket.io auf Intern, VIS funktioniert problemlos, die Logfunktion von ioBroker ist unauffällig:

iqontrol.0 | 2019-06-24 05:24:21.185 | info | Deleting unused Objects...
-- | -- | -- | --
iqontrol.0 | 2019-06-24 05:24:21.185 | info | Created Devices: 467 (Toolbar.0000__Übersicht,Toolbar.0001__Licht,Toolbar.0002__Klima,Toolbar.0003__Technik,Views.Smart Home.0000__Balkon.STATE,Views.Smart Home.0000__Balkon.TEMPERATURE,Views.Smart H
iqontrol.0 | 2019-06-24 05:24:21.180 | info | Creating Options...
iqontrol.0 | 2019-06-24 05:24:21.022 | info | Creating Views...
iqontrol.0 | 2019-06-24 05:24:21.006 | info | Creating Toolbar...
iqontrol.0 | 2019-06-24 05:24:20.958 | info | starting. Version 0.0.39 in /opt/iobroker/node_modules/iobroker.iqontrol, node: v10.16.0

Alles andere kann ich frühestens morgen testen

**Comment by sbormann** [comment]
Ich habe eine neue js-Datei beim upload vergessen. Sollte mit der 0.0.40 hoffentlich funktionieren!
Danke für die Rückmeldung!

**Comment by ihavenonick** [comment]
gut, wollte ich auch gerade berichten

**Comment by AlexStephenLytton** [comment]
> Ich habe eine neue js-Datei beim upload vergessen. Sollte mit der 0.0.40 hoffentlich funktionieren!
> Danke für die Rückmeldung!

Kein Problem, man hilft doch gerne :)
