### ISSUE TITLE
Ansicht in App Möglich?

### ISSUE THREAD

**Issue by zakuma666** [sbormann/ioBroker.iqontrol#55]
Guten Tag,

erst einmal vielen dank für den tollen Adapter! Genau so was hab ich gesucht mit wenigen klicks einfach übersichtliche Views zu erstellen, die sich auch noch der Bildschirmgröße anpassen, da gefällt mir der Vis Adapter einfach nicht, man muss sich Stunden reinarbeiten bis man was passables erreicht.

Nun meine Frage, besteht die Möglichkeit die Ansicht statt im Browser in einer App darzustellen wie es bei Vis auch möglich ist? Vielleicht auch mit der selben App (iOS/Android)

Vielen dank schon mal.

**Comment by Lou2401** [comment]
Hallo,

stimme Dir absolut zu - der Adapter ist genial!

Ich habe das bei mir so geloest, dass ich einen Link aus Android/Chrome raus erstellt habe "Zum Startbildschirm zufuegen". Es erstellt sich damit ein App Icon auf dem Desktop und die (Browser)Ansicht sieht auch wie eine App aus.

VG
Marco

**Comment by sbormann** [comment]
Hi, einfach (bei iOS) im Safari auf das Teilen-Icon tippen und „zum Homebildschirm“ wählen. Schon ist es wie eine App. Sollte bei Android auch irgendwie gehen. LG

--
Von meinem iPhone aus gesendet

Am 26.06.2019 um 10:44 schrieb zakuma666 <notifications@github.com<mailto:notifications@github.com>>:


Guten Tag,

erst einmal vielen dank für den tollen Adapter! Genau so was hab ich gesucht mit wenigen klicks einfach übersichtliche Views zu erstellen, die sich auch noch der Bildschirmgröße anpassen, da gefällt mir der Vis Adapter einfach nicht, man muss sich Stunden reinarbeiten bis man was passables erreicht.

Nun meine Frage, besteht die Möglichkeit die Ansicht statt im Browser in einer App darzustellen wie es bei Vis auch möglich ist? Vielleicht auch mit der selben App (iOS/Android)

Vielen dank schon mal.

**Comment by zakuma666** [comment]
danke, auf Android hab ich es per "Startbildschirm Hinzufügen" gemacht, in iOS hab ich es hinbekommen, dass es in der Vis App läuft! (Sicherlich ist auch eine einfache Verknüpfung zum Homebildschirm möglich)

**Comment by sbormann** [comment]
Ja cool, wusste gar nicht, dass das geht! Kannst Du mal Deine Einstellungen dafür posten?

--
Von meinem iPhone aus gesendet

Am 26.06.2019 um 17:07 schrieb zakuma666 <notifications@github.com<mailto:notifications@github.com>>:


Closed #55<https://github.com/sbormann/ioBroker.iqontrol/issues/55>.

**Comment by zakuma666** [comment]
Hey

Hier sind die Einstellungen die ich gemacht hab zu sehen:
https://abload.de/img/img-20190626-wa0001qbjtt.jpg

**Comment by sbormann** [comment]
Cool, danke!

--
Von meinem iPhone aus gesendet

Am 26.06.2019 um 19:37 schrieb zakuma666 <notifications@github.com<mailto:notifications@github.com>>:


Hey

Hier sind die Einstellungen die ich gemacht hab zu sehen:
https://abload.de/img/img-20190626-wa0001qbjtt.jpg

**Comment by andreaskoerber** [comment]
Danke. Das habe ich ähnlich so gemacht. 
Nun möchte ich aber nur einzelne Widgets (oder zur Not einzelne Ansichten) auf dem Smartphone haben. Kann man irgendwie URLs einzelner Icons/Widgets oder Ansichten erzeugen die man gem. obigem Verfahren dann auf dem Smartphone installiert?
Dank im Voraus
