### ISSUE TITLE
Blind umkehren

### ISSUE THREAD

**Issue by j3sk0** [sbormann/ioBroker.iqontrol#56]
Hallo,

eine Möglichkeit der Jalousie/Rolladen zu negieren so das true gleich geschlossen bedeutet wäre schön, somit kann man sich die Umkehrung mittels eigene Datenpunkte und skript sparen.

Vielen Dank

**Comment by sbormann** [comment]
Ist in Planung 

VG

**Comment by sbormann** [comment]
Geht jetzt bei Jalousien ab der 0.0.46.
