### ISSUE TITLE
Homematic Thermostat funktioniert nicht mehr

### ISSUE THREAD

**Issue by SeniorCatweazle** [sbormann/ioBroker.iqontrol#58]
Hallo,

zur Zeit werden im Homematic Thermostat nur die Werte angezeigt. Änderungen kann ich keine vornehmen. Es öffnet sich kein popup Fenster. Wenn ich das herkömmliche Thermostat nehme geht es wie gewohnt. 

Gruß Sven

**Comment by sbormann** [comment]
Hmm, bei mir gehts. Habe da auch eigentlich gar nichts mehr geändert. Gibt es Fehler im Log? Mal iQontrol mit Debug-Mode im Browser (F12) öffnen und schauen, ob es da Fehler gibt.

**Comment by SeniorCatweazle** [comment]
Sorry war mein Fehler, hatte die Felder falsch gefüllt. Läuft alles wie es soll.

Gruß Sven
