### ISSUE TITLE
Feature-Request: Zustands und State-Datenpunkte getrennt einstellen

### ISSUE THREAD

**Issue by do1osc** [sbormann/ioBroker.iqontrol#59]
Es ist hilfreich, die Datenpunkte für "Aktueller Wert" eines DP's und das Schalten des Wertes getrennt einstellbar zu machen, da es Datenpunkte gibt die nur lesbar, aber nicht schreibbar sind und umgekehrt.
D.H. State wird in DP1 gesetzt, der Status steht aber in DP2.

Konkret ist das aufgefallen bei CONTROL_MODE (schreibbar, aber nicht lesbar) und SET_POINT_MODE (lesbar, aber nicht schreibbar) in einem HMIP-eTRV-Thermostat.

**Comment by sbormann** [comment]
Hi, das geht jetzt in den Datenpunkt Konfigurationen (Target Value ID). VG!
