### ISSUE TITLE
Schalter zum Aktivieren/Deaktivieren von Skripten funktionieren nicht

### ISSUE THREAD

**Issue by gswdn** [sbormann/ioBroker.iqontrol#61]
Repro:
- Adapterkonfiguration öffnen
- Tab Geräte wählöen
- beliebige Ansicht wählen
- neues manuelles Gerät
- Gerätetyp "Schalter"
- State auf "javascript.0.scriptEnabled.ServiceJobs.HomematicServicemeldungen" festlegen, wobei "ServiceJobs.HomematicServicemeldungen" ein Skript ist
- Schalter lässt sich im betätigen

Im Objektbrowser lässt sich der Status ändern.
Ebenso ändert sich der Status im Objektbrowser, wenn im Skriptbrowser das Skript aktiviert/deaktiviert wird.
Änderungen am Skriptstatus über den Objektbrowser/Skriptbrowser werden am iqontrol-Schalter hingegen korrekt wiedergegeben.

**Comment by sbormann** [comment]
Stimmt, wird in 0.0.46 gefixed. Danke.

**Comment by gswdn** [comment]
Vielen Dank für's schnelle Beheben. Und iqontrol im Allgemeinen :)

**Comment by gswdn** [comment]
Hallo Sebastian. Habe gerade mal auf die 0.1.1er Version aktualisiert. Ich habe den Fehler leider immer noch. Muss ich etwas spezielles beachten?

**Comment by sbormann** [comment]
In der Regel hilft ein manueller upload des Adapters nach dem Update und den Cache zu leeren. Wenn nicht, muss ggf. auch der iobroker nochmal neu gestartet werden. An sich sollte der Fehler weg sein.

**Comment by gswdn** [comment]
Hm. Dann mache ich bestimmt etwas falsch :-(. Habe jetzt den kompletten Raspi neu gestartet. Und einmal die Konfig exportiert, die Instanz des Adapters gelöscht, neue Instanz erstellt und Konfig wieder importiert. Auch Browser-Cache komplett gelöscht.

Für's Update gehe ich auf "Adapter", "Installieren aus eigener URL", Tab "Beliebig" und trage in "Adapter aus beliebiger Quelle installieren oder aktualisieren" die GitHub-URL "https://github.com/sbormann/ioBroker.iqontrol.git" ein. Unter Adapter wird dann auch iQontrol mit der Version 0.1.2 aufgeführt.

Was mir noch aufgefallen ist: wenn ich auf den Schalter selbst klicke, bewegt er sich nicht. Andere Schalter bewegen sich ja dann doch direkt. Klicke ich auf die Bezeichnung des Schalters, öffnet sich ein Popup-Dialog mit einer Textbox. Da kann ich dann true/false eintippen und auf "Absenden" klicken. Dann ändert sich auch der Wert des Schalters.

**Comment by sbormann** [comment]
Hi, dann hätte ich noch folgenden Vorschlag: Gehe auf den Schraubenschlüssel des Datenpunktes und ändere für iQontrol den Typ auf boolean ab. Geht es dann?

**Comment by gswdn** [comment]
Hi. 
Habe bei den Objekten ("javascript.0/scriptEnabled/...") die Rolle von "switch.active" auf "switch" geändert, da diese Rolle bei anderen Schaltern vergeben ist, bei denen der iQontrol-Schalter funktioniert. Ansonsten war als "Art" bereits "Logikwert" gewählt. Boolean selbst finde ich dort nicht.
Meintest Du diese Einstellung?

Auf jeden Fall: mit der Änderung funktioniert der iQontrol Schalter nun.
Frage mich nur, ob es gut ist, die Rolle zu ändern, da ja "switch.active" scheinbar die Standard-Rolle für Skripte ist und das ja auch Seiteneffekte haben könnte. Vermutlich wäre es dann doch besser, lieber auch die Rolle "switch.active" in iQontrol zu unterstützen, oder?
