### ISSUE TITLE
Rolladen Up/Down mit einstellbaren Werten

### ISSUE THREAD

**Issue by Lou2401** [sbormann/ioBroker.iqontrol#63]
Hallo Sebastian,

die Rolladen Buttons Up bzw. Down beschreiben aktuellen ein Objekt mit Boolean Werten. Der Homematic Aktor hat nur ein Level Objekt, was prozentual von 0 bis 100 eingestellt werden kann.

Waere es moeglich, die Up und Down Buttons so konfigurierbar zu machen, dass man sie jeweils mit dem Level Objekt verbindet, aber anstatt 0 oder 1 reinzuschreiben konfigurierbare Werte reinschreibt.

Im Falle des Homematic Aktors sollte es funktionieren, dass man 0 fuer Down (wuerde schon passen) und aber 100 fuer Up in das Level Objekt schreibt.

Danke und VG
Marco

**Comment by sbormann** [comment]
Hi, gute Idee, kommt mit dem nächsten Update! LG!
