### ISSUE TITLE
Grafiken in Config können nicht geladen werden

### ISSUE THREAD

**Issue by gswdn** [sbormann/ioBroker.iqontrol#64]
Repro:

- ioBroker läuft mit https
- Adapterkonfiguration iQontrol öffnen
- Tab "Bilder" wählen

-> Bilder werden nicht dargestellt

![image](https://user-images.githubusercontent.com/52855342/62408607-aa337b80-b5cb-11e9-9231-dd11de9381bf.png)

Vermutung:
Es wird versucht, die Grafiken per https zu laden. ioBroker läuft bei mir auch über https, Port 8081.
iQontrol scheint über Port 8082 und http zu laufen. Darüber werden dann wohl auch die Grafiken geladen.
Das Config-Interface versucht jedoch, die Grafiken per https von Port 8082 zu laden, was dann jedoch fehlschlägt.

Kopiere ich die Grafik-URL in die Adresszeile des Browsers und änderte https:// zu http://, kann die Grafik geladen werden.
![image](https://user-images.githubusercontent.com/52855342/62408652-48bfdc80-b5cc-11e9-855e-a2316ab7a79a.png)

Weiterhin:
In der URL gibt es einen doppelten Slash, der jeder erst einmal keine Auswirkungen zu haben scheint.

![image](https://user-images.githubusercontent.com/52855342/62408665-7ad13e80-b5cc-11e9-8025-e837731a3b46.png)

**Comment by sbormann** [comment]
Stimmt genau, was Du sagst. Es liegt daran, dass ich die Verbindung zum web-Adapter (über den kommen u.a. die Bilder) über das gleiche Protokoll habe statt finden lassen, über das der ioBroker Admin aufgerufen wurde. Das muss aber nicht zwangsläufig das gleiche sein (wie bei Dir: Admin über https://, der web-adapter läuft bei Dir aber auf http://). 

Ich baue jetzt eine Abfrage ein, auf welchem Protokoll der web-Adapter läuft.
Wird in der 0.1.4 gefixed!

Danke!

**Comment by MSchmitt67** [comment]
Hallo,
ich habe das selbe Problem, was kann ich tun?
iqontrol v3.0.0
web v7.0.8
Iobroker und Raspi sind aktuell

**Comment by MSchmitt67** [comment]
Hallo,
ich habe das selbe Problem, was kann ich tun?
iqontrol v3.0.0
web v7.0.8
Iobroker und Raspi sind aktuell

**Comment by Vumer4** [comment]
> Hallo, ich habe das selbe Problem, was kann ich tun? iqontrol v3.0.0 web v7.0.8 Iobroker und Raspi sind aktuell

Schau mal ob die http/https Einstellungen im admin und web Adapter gleich sind.
