### ISSUE TITLE
Tile als Button

### ISSUE THREAD

**Issue by MarcoLaser** [sbormann/ioBroker.iqontrol#65]
Moin,
Ich fänd es cool wenn man beim Gerätetyp Button, eventuell auch bei anderen, auf das Tile anstatt das Icon klickt es auch die gleiche Funktion hätte wie beim Icon. Bei vielen Anwendung braucht man das Pop Up fenster nicht und so geht es schneller. Eventuell ja auch mit einer Einstellung versehen sodass es jeder machen kann wie er mag.

PS: Tolle Arbeit die du da gemacht hast.

**Comment by sbormann** [comment]
Geht mit 0.1.8
