### ISSUE TITLE
Icon über URL

### ISSUE THREAD

**Issue by Lou2401** [sbormann/ioBroker.iqontrol#66]
Hallo Sebastian,

ich habe mir eine Werte Box mit der Wetterinformation im State erstellt: 

![image](https://user-images.githubusercontent.com/7393999/62875597-97374e80-bd23-11e9-87cf-2c87df4e8ad3.png)

Interessant wäre es, wenn man das Icon mittels URL Datenpunkt aktualisieren könnte.
Ich habe den Weatherunderground Adapter im Einsatz, der einen Datenpunkt iconURL bietet. Dieser hat z.B. diesen Inhalt: https://icons.wxug.com/i/c/v4/12.svg

Das Ergebnis sollte dann etwa so aussehen:

![image](https://user-images.githubusercontent.com/7393999/62876045-64418a80-bd24-11e9-9606-81b8cc59e79d.png)

Danke fuer Dein Feedback hierzu.
VG
Marco

**Comment by sbormann** [comment]
Hi, in der nächsten Version kann man zumindest externe URLs als Hintergrundbilder und als Icons einbinden. 

Jetzt müsste man noch ein Script schreiben, dass immer das entsprechende Icon immer auf diese URL kopiert (ginge z.B. über ein PHP-Script oder so), dann hätte man das gewünschte Ergebnis.

Vielleicht gibt es so was auch schon irgendwo? Z.B. liefert der DWD ja auch immer unter der gleichen URL die aktualisierte Wetter-Karte. Vielleicht gibt es das auch mit den Icons bei einem der Anbieter?? 


Die Icons als direkte Datenpunkte einzubinden ist von der Struktur her schwierig, deshalb geht es nur über diesen Umweg.

Kannst ja mal berichten, ob Du damit weiter gekommen bist.

LG!

**Comment by Lou2401** [comment]
Hi Sebastian,

den externen Link einzubinden sieht optisch schon mal sehr gut aus:

![image](https://user-images.githubusercontent.com/7393999/63368489-502e0680-c37e-11e9-9caa-dec140c1bd2f.png)

In dem Beispiel ist es die statische URL https://icons.wxug.com/i/c/v4/29.svg die ich hinterlegt habe. Der Weather Underground Adapter aktualisiert jeweils immer die URL. Man müsste demnach dynamisch die jeweils aktuelle URL in deine Icon Option laden. Schade das man in der Option nicht gleich einen Datenpunkt hinterlegen kann. Aber OK ich verstehe, dass die Struktur es nicht her gibt.

Ich verstehe denke ich deinen Ansatz. Nur würde ich dann auf einen lokale Datei verweisen, die dann per Script immer entsprechend des Eintrages im Weather Underground Datenpunkt runtergeladen wird und die lokale Datei austauscht - bei immer gleich bleibendem Dateinamen. Hmmm... lange Zeit ist es her, dass ich programmiert habe... :-)

VG
Marco

**Comment by sbormann** [comment]
Hi Marco,
ich schließe den Thread hier mal.
Wenn Du etwas erreicht hast, kannst Du ihn aber bitte noch mal eröffenen, und Deinen Weg kurz posten? Danke Dir und VG!
