### ISSUE TITLE
Erwähnung der letzten Änderung im Status

### ISSUE THREAD

**Issue by Lou2401** [sbormann/ioBroker.iqontrol#67]
Hallo Sebastian,

ich suche nach der Möglichkeit den Zeitwert der letzten Änderung eines Status gleich mit im Status Text zu erwähnen. 
So z.B. für den Bewegungsmelder:
![image](https://user-images.githubusercontent.com/7393999/62899514-3c6c1a00-bd58-11e9-88a6-858d4e7d6fd2.png)

Auch interessant wäre eine Anzeige in der Information ob jemand anwesend ist, oder nicht. Text hier dann z.B. "Abwesend seit 20:10".

VG
Marco

**Comment by martinschm** [comment]
Ja, das wäre super cool. Grade bei Bewegungsmeldern.

**Comment by DocGame69** [comment]
Das wäre super...
Will komplett von Material auf IQontrol umsteigen.
Bei Material habe ich den Timestamp bei BWM und Fenstersensoren (alles Xiaomi).
Die Prozentuale Batterieanzeige(der State ist im jeweiligen Adapter ja vorhanden) wäre auch super, da Batteriebestellungen aus CN ja einiges an Vorlaufzeit brauchen.
Ist da was machbar?

**Comment by sbormann** [comment]
![image](https://user-images.githubusercontent.com/49171332/63376940-39dc7680-c38f-11e9-81cb-7e403f24737e.png)


Batteriestand in Prozent könntest Du über den ADDITIONAL_INFO-Datenpunkt einblenden lassen (im Dialog, nicht auf der Kachel)

**Comment by Lou2401** [comment]
Klar. Gute Idee. Wie würdest du es dort darstellen für den Fall dass die letzte Änderung älter ist als der aktuelle Tag? Also noch ein Datum zeigen müsste. Haut das hin vom Platz her?

**Comment by sbormann** [comment]
Gute Frage. Man könnte es scrollen lassen. Oder nur das Datum zeigen. Was ist besser? 

Je länger es her ist, desto weniger interessiert ja die genaue Uhrzeit, oder? Und wenn, kann man ja immer noch im Popup nachschauen.

**Comment by DocGame69** [comment]
Material zeigt bis 24 Std., dann werden Tage angezeigt.
Ich finde das ist ideal und besser als das scrollen.

**Comment by Lou2401** [comment]
Ich tendiere auch zum Datum. Wie du schon sagst, das Detail kann man im Pop Up sehen.

**Comment by sbormann** [comment]
Geht jetzt mit der aktuellen Version!
VG!
