### ISSUE TITLE
Bei Ansichten wird eine Änderung vom Hintergrundbild nicht gespeichert

### ISSUE THREAD

**Issue by MiJo112** [sbormann/ioBroker.iqontrol#69]
In der Adapterkonfiguration wird eine nachträgliche Änderung des Hintergrundbildes der Ansichten nicht gespeichert.
Fehler tritt in allen Browsern auf.
Selbst beim Klick auf "Speichern" nicht.

**Comment by sbormann** [comment]
Mit der 0.1.11 geht es hoffentlich. Falls doch nicht, bitte wiedereröffnen! VG
