### ISSUE TITLE
Zeige "Aus" wenn RGB auf 0 ist

### ISSUE THREAD

**Issue by MiJo112** [sbormann/ioBroker.iqontrol#72]
Hi,
noch ein Verbesserungsvorschlag:
Wenn beide Helligkeiten auf 0 sind, dann könnte Aus auf der Kachel angezeigt werden.
Im Idealfall könnten bei An beide Prozentwerte angezeigt werden.
![grafik](https://user-images.githubusercontent.com/35043404/63538149-923e8000-c517-11e9-8492-600884460ae6.png)

**Comment by sbormann** [comment]
Hi, hat Dein Gerät keinen Schalter (meist STATE-Datenpunkt)? Oder ein master-LEVEL? Wenn das verlinkt wird, dann wird auch ein Status-Text generiert und angezeigt. VG!

**Comment by sbormann** [comment]
Bitte neu eröffnen, falls noch nicht gelöst und noch von Interesse. VG!
