### ISSUE TITLE
Homematic IP 

### ISSUE THREAD

**Issue by LorenJaffrey** [sbormann/ioBroker.iqontrol#75]
I have issues setting up Homematic IP BROLL and BBL as shutter (Jalousie).
iQontrol seems to require a dedicated up and down signal whereas the devices only give the current shutter (and slats for BBL) state.
The bar also seems to display a value from 0 to 100 whereas the device works with values between 0 and 1.
Is there any possibility to support this? For example configure min and max shutter level and setting the shutter level directly instead of working with up and down signals?

**Comment by sbormann** [comment]
Hi,

iQontrol should accept a level as setpoint - you can, but you dont have to define dedicated buttons with up and down. 

Also the min and max of the datapoint is used to set the borders of the bar. If they are not correctly defined in the datapoint of the homematic ip device, you can modify them via the wrench-symbol of the datapoint. Go to the iqontrol tab and set your custom min and max to 0 and 1.

If you have further problems, please post a screenshot of device's datapoints and the raw of the level-(or state?)-datapoint. Maybe you could also post screenshots of your iqontrol-configuration.

Best luck,
  Sebastian

**Comment by LorenJaffrey** [comment]
Hi Sebastian,

thank you for your answer! I figured out the main problem was that the device was set to readonly which caused the bar to display incorrectly as well as not being editable. After removing the checkbox setting the shutter level works fine. However i didn't find how to set the slats accordingly. The only other datapoint which i thought could be responsible is "direction". But this does not seem to work.
Is there a possibility to control shutter ans slats or just the shutter?

**Comment by sbormann** [comment]
Hi could you please post a screenshot, wich datapoints the homematic device offers?

**Comment by LorenJaffrey** [comment]
![hmip_datapoints](https://user-images.githubusercontent.com/1888569/64022995-a85fc800-cb37-11e9-9c4a-db0442bdd814.PNG)

**Comment by sbormann** [comment]
Hi,

0.1.14 will provide a higher resolution for level-sliders, if the range is small. Please report if this solves the problem with the slider?

I will also add slatsState soon, but, for now it is not possible to set the slats.

Greetings, Sebastian

**Comment by LorenJaffrey** [comment]
Thank you Sebastian,

i will await the next update!

**Comment by sbormann** [comment]
Slats are now available in 0.2.0.
