### ISSUE TITLE
DeviceType Blinds: Option "Invert Level" has no effect

### ISSUE THREAD

**Issue by t0mcat1337** [sbormann/ioBroker.iqontrol#76]
Hi,

I have blinds with a "level" state which has a value of 100% when the blinds are completely closed (down) and a value of 0% when they are completely up (open). 
I added this state to  a device type "blinds" in iqontrol. When the blinds are closed (down, value is 100%) and I open the iqontrol frontend, the blinds icon is "open (up)" and also the text is "open".
I found the Option "Invert Level (0=opened)" at the Device settings but when I check it, it has no effect. The icon and the text stay saying "open".

Seeme to be bug, isn't it?

Thx in advance
T0mc@

**Comment by sbormann** [comment]
Hi, for me it works as it should.
You have two options to invert:
- In Device settings "Invert Level (0=opened) and
- In Datapoint-Settings (Wrench-Icon)

Maybe you have both options set? That would lead to a double-invert, wich means it is not inverted at the end.

Greetings, Sebastian

**Comment by t0mcat1337** [comment]
Hi Sebastian,

no, I didn't even realized the second option. I just double-checked, that the checkox "Invert Level" in device settings is checked and in the datapoint settings the "invert" option under "iqontrol" is unchecked (as it was all the time). Not even the "activate" box is checked in the datapoint settings...

Greetings

**Comment by d1nd141** [comment]
Hello,
i confirm, i have the same problem with a FHEM Homematic HM-LC-BL1PBU-FM adapter.
0% is open, 100% closed. Unfortunately "inverting" does not work.

**Comment by sbormann** [comment]
I checked again, for me it works. I have no idea, what causes the issue.
Could you please check, if the other invert option (in datapoint-settings = wrench-icon) works as expected?
And could you please send the raw of the level-datapoint you are trying to invert (maybe min and max is missing?)
Greetings, Sebastian

**Comment by d1nd141** [comment]
Ok, i played around with both "Invert" settings. Unfortunately no change. Both on, both off, or only one on.
Also i set "Level" as "Role".
Do you mean this raw?

`{
  "_id": "fhem.0.Kueche_Rollladen.level",
  "type": "state",
  "common": {
    "name": "Kueche.Rollladen level",
    "type": "number",
    "role": "value",
    "read": true,
    "write": false,
    "custom": {
      "iqontrol.0": {
        "enabled": true,
        "readonly": true,
        "invert": false,
        "unit": "",
        "type": "number",
        "role": "level",
        "targetValueId": "",
        "states": {}
      }
    }
  },
  "native": {
    "Name": "Kueche.Rollladen",
    "Attribute": "level",
    "Readings": true
  },
  "from": "system.adapter.fhem.0",
  "user": "system.user.admin",
  "ts": 1565895604535,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

**Comment by sbormann** [comment]
Two things:

1) Here is no min and max defined - but these values are required to invert. 

If not defined, iQontroll will use 0 and 100 as default values. Could you please check, are these the right min and max values for this datapoint? Maybe it is 0 and 1? 

Since version 0.1.11 you can define min and max for iqontrol in the datapoint-settings (wrench-icon). Please try to set here min and max to 0 and 100 or 0 and 1. Does this fix the problem?

2) The datapoint is readonly ("write": false). This would mean, you could only SEE the actual blind level - but you can't SET it by this datapoint. Does your device provide another datapoint for SETTING the level?

Greetings, Sebastian

**Comment by d1nd141** [comment]
Hi Sebastian,
instead of the "level" reading i took now the "pct" reading and it works fine:

`{
  "_id": "fhem.0.Kueche_Rollladen.pct",
  "type": "state",
  "common": {
    "name": "Kueche.Rollladen pct",
    "type": "number",
    "role": "level.blind",
    "read": true,
    "write": true,
    "min": 0,
    "max": 100,
    "unit": "%",
    "smartName": {
      "de": "Kueche.Rollladen",
      "smartType": "kein Typ"
    },
    "custom": {
      "iqontrol.0": {
        "enabled": true,
        "readonly": false,
        "invert": true,
        "unit": "%",
        "type": "number",
        "role": "",
        "targetValueId": "",
        "states": {
          "min": "0",
          "max": "100"
        }
      }
    }
  },
  "native": {
    "Name": "Kueche.Rollladen",
    "Attribute": "pct",
    "possibleSets": true,
    "slider": true,
    "level_dimmer": true,
    "level_blind": true,
    "Readings": true
  },
  "from": "system.adapter.fhem.0",
  "user": "system.user.admin",
  "ts": 1565895601726,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`


Thanks for your Help!

**Comment by t0mcat1337** [comment]
Hi Sebastian,

for me the problem still exists... here is the raw of my datapoint:
```
{
  "type": "state",
  "common": {
    "name": "Wohnzimmer Rollo Fenster",
    "desc": "level of device 1010000",
    "type": "number",
    "role": "level.blind",
    "unit": "%",
    "min": 0,
    "max": 100,
    "read": true,
    "write": true,
    "smartName": {
      "de": "Wohnzimmer Rollo Fenster"
    }
  },
  "native": {},
  "from": "system.adapter.homepilot.0",
  "user": "system.user.admin",
  "ts": 1567018529177,
  "_id": "homepilot.0.devices.RolloTronStandardDuoFern.1010000.level",
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  }
}

```
At the moment the blind is completely closed and the value says "100" in ioBroker:
![Screenshot_20190902-113110_Chrome](https://user-images.githubusercontent.com/3826246/64104800-4096c080-cd75-11e9-8bef-62b6e7859de5.jpg)

This also can be seen in the WebApp of the original Gateway device:
![Screenshot_20190902-112730_Chrome](https://user-images.githubusercontent.com/3826246/64104667-f31a5380-cd74-11e9-84b1-de819c586d0d.jpg)

In iQontrol "Invert Level" Checkbox is checked:
![Screenshot_20190902-113332_Chrome](https://user-images.githubusercontent.com/3826246/64104940-8784b600-cd75-11e9-8800-7c4f4b63c429.jpg)
The datapoints (wrench) Invert Checkbox is unchecked:
![Screenshot_20190902-113541_Chrome](https://user-images.githubusercontent.com/3826246/64105111-d92d4080-cd75-11e9-9857-60a115c79873.jpg)

But the iQontrol Frontend sais "open":
![Screenshot_20190902-113717_Chrome](https://user-images.githubusercontent.com/3826246/64105211-1265b080-cd76-11e9-8500-35ca646c970d.jpg)

Any idea?

**Comment by t0mcat1337** [comment]
I just dived into your corresponding JavaScript code and found the bug:

in "index.js" the responsible code is this:
```
   case "iQontrolBlind":                                                                                                                                                         
.
.
.
.
                                                                                        if(_deviceId && usedObjects[_deviceId] && typeof usedObjects[_deviceId].native != udef && typeof usedObjects[_deviceId].native.invertActuatorLevel != 
udef && usedObjects[_deviceId].native.invertActuatorLevel == "true") invertActuatorLevel = !invertActuatorLevel;

```

In the "if" the checked object property is "invertActuatorLevel".  But examining the Objet in "usedObject[_deviceId].native" one can see, that the correct property name is "invertBlindLevel":
![20190902_170742](https://user-images.githubusercontent.com/3826246/64123274-38a24500-cda4-11e9-808a-ccc9e803b66e.jpg)


So changing all "invertActuatorLevel" to "invertBlindLevel" in the "if" Line like this:

```
if(_deviceId && usedObjects[_deviceId] && typeof usedObjects[_deviceId].native != udef && typeof usedObjects[_deviceId].native.invertBlindLevel != ude
f && usedObjects[_deviceId].native.invertBlindLevel == "true") invertActuatorLevel = !invertActuatorLevel;
```

solves the problem.

**Comment by sbormann** [comment]
Hi, many thanks for your research that takes us a large step further to the problem.

I renamed the option from invertBlindLevel to invertActuatorLevel a few versions ago, because this is a more common name and so the same code can be later used in other, similar actors (like garage door and so on).

That takes us to the question why you have the old option name "invertBlindLevel" in the Object? In the actual version of the index_m.js, wich is responsible for creating the options, it is correctly named. So maybe you have an old version of index_m.js (backend) but a new (incompatible) version of index.js (frontend)?

Several users reported problems while upgrading to a new version. In most cases a simple upload and clearing of the cache fixed the problem. Please try the following steps and please report me, if this fixed the problem:

[Troubleshooting](https://github.com/sbormann/ioBroker.iqontrol#troubleshooting)

Thanks, Sebastian

**Comment by t0mcat1337** [comment]
That's indeed strange ... 
If I understand iobroker correctly, the "source" for uploadable adapters / creating instances of them is under <iobroker>/node_modules. Here one can find a folder "iobroker.iqontrol" with the same structure as here in github. Here I grepped for "invertActuator" and found it in "www/index.js" and a grep for "invertBlind" gives "admin/index_m.js". So for me it seems that already in the source dir for iQontrol the vars are mixed.

As a plus I can't remember I have updated the iQontrol adapter but just installed it once.

In the Troubleshooting Section you just say "Re-Upload the adapter again (physically to <iobroker>/iobroker-data/files) from the source (physically <iobroker>/node_modules)", correct?
This can also be done at the commandline with "iobroker upload iqontrol". This didn't solve the problem as the source files are wrong as I described.

BTW: In iobrokers Adapter Section the iqontrol version installed / availabel is "0.1.0" which don't correspond with the GitHub Release Version Numbers... is that correct?

**Comment by t0mcat1337** [comment]
I clicked around in the commit history and found out, that till this commit at 01.08.:
https://github.com/sbormann/ioBroker.iqontrol/commit/9cc4f6fe2c597b5c94283515bd3a2cc18b82f35c#diff-b0a0d64060c0c0c2e8e8fc481a502346

the bug was present from the first release on (27.07.)... until 01.08. in www/index.js the var in the if was named "invertActuatorLevel" but in admin/index_m.js it was created as "invertBlindLevel"

In the mentioned commit one can read "...Fixed invert level for blinds..."

So I assume that I have an older Version of the Adapter installed, but iobroker sais, ther is no newer one existing...

**Comment by sbormann** [comment]
Everything you said is 100% correct.
You can update to the newest (beta) version via the cat-symbol or you switch from stable to latest repository in settings of iobroker (wich affects all adapters - iobroker will offer you the latest betaversion of all adapters).
