### ISSUE TITLE
NewFeature : RGB to HEX

### ISSUE THREAD

**Issue by DutchmanNL** [sbormann/ioBroker.iqontrol#77]
Please add the capability to have an HEX value as color set instead of RGB only.
Zigbee devices (like the Ikea bulbs) use HEX values and not RGB.

**Comment by sbormann** [comment]
Hi, could you post an example of a hex value? I thought #rrggbb like #ff0012 is a hex value?



--
Von meinem iPhone aus gesendet

Am 04.09.2019 um 12:09 schrieb Dutchman <notifications@github.com<mailto:notifications@github.com>>:


Please add the capability to have an HEX value as color set instead of RGB only.
Zigbee devices (like the Ikea bulbs) use HEX values and not RGB.

**Comment by DutchmanNL** [comment]
> Hi, could you post an example of a hex value? I thought #rrggbb like #ff0012 is a hex value?
> […](#)

example : #ffd700

<img width="1496" alt="Schermafbeelding 2019-09-04 om 20 53 10" src="https://user-images.githubusercontent.com/7318445/64282573-03d5ef80-cf56-11e9-9dd1-f0a2f3f20539.png">

values can be calculated as regular : 

<img width="739" alt="Schermafbeelding 2019-09-04 om 20 54 08" src="https://user-images.githubusercontent.com/7318445/64282644-2ff17080-cf56-11e9-8f06-5b26abf28d04.png">

**Comment by sbormann** [comment]
Hi, you can use #rgb, i think this is exactly what you are looking for.

Greetings, Sebastian

--
Von meinem iPhone aus gesendet

Am 04.09.2019 um 20:54 schrieb Dutchman <notifications@github.com<mailto:notifications@github.com>>:


Hi, could you post an example of a hex value? I thought #rrggbb like #ff0012 is a hex value?
…

example : #ffd700

[Schermafbeelding 2019-09-04 om 20 53 10]<https://user-images.githubusercontent.com/7318445/64282573-03d5ef80-cf56-11e9-9dd1-f0a2f3f20539.png>

values can be calculated as regular :

[Schermafbeelding 2019-09-04 om 20 54 08]<https://user-images.githubusercontent.com/7318445/64282644-2ff17080-cf56-11e9-8f06-5b26abf28d04.png>

**Comment by DutchmanNL** [comment]
hmm I adjusted the settings but the values does not change when changed in iqontrol view : 

<img width="1495" alt="Schermafbeelding 2019-09-05 om 20 57 29" src="https://user-images.githubusercontent.com/7318445/64370952-c8075c80-d01f-11e9-89c4-11499c184dab.png">

<img width="1107" alt="Schermafbeelding 2019-09-05 om 20 58 07" src="https://user-images.githubusercontent.com/7318445/64371004-de151d00-d01f-11e9-8eb0-b6758fbf4ea6.png">

<img width="638" alt="Schermafbeelding 2019-09-05 om 20 58 22" src="https://user-images.githubusercontent.com/7318445/64371033-e8cfb200-d01f-11e9-95be-3ab0db0eee98.png">

<img width="350" alt="Schermafbeelding 2019-09-05 om 20 58 41" src="https://user-images.githubusercontent.com/7318445/64371053-f38a4700-d01f-11e9-8d01-d90339734a3b.png">

**Comment by sbormann** [comment]
You are right, this is a bug. Ill check how to fix it.

**Comment by sbormann** [comment]
OK, found it - dumb error. Used [] instead of () to call a function. Will be fixed in 0.1.15 wich uploads right in the moment. Thanks for reporting the error.

**Comment by DutchmanNL** [comment]
perfect, fixed confirmed thank you !!!
