### ISSUE TITLE
Empty Page

### ISSUE THREAD

**Issue by joeflower** [sbormann/ioBroker.iqontrol#78]
Nach Update von 0.1.15 auf 0.2.0
habe ich in der Istance (Adapterkonfiguration) eine leere Seite.
Neustart half nix. Browsercache leeren auch nicht.
Der Adapter läuft und die Weboberläche wird auch wie vorher konfiguriert angezeigt.
Nur Konfigurieren geht nicht mehr.

**Comment by sbormann** [comment]
Der Fehler wurde gerade auch im Forum gemeldet und hoffentlich mit der 0.2.1 gefixed. Wenn nicht, einfach noch mal melden. Danke und VG!

**Comment by joeflower** [comment]
Hi

Version 0.2.1 funktioniert wieder einwandfrei.

Danke für die schnelle Problembehebung.

 

P.S: nächstes mal schau ich auch vorher ins Forum :-)

 

Joe

 

Sent: Saturday, September 07, 2019 at 1:55 PM
