### ISSUE TITLE
There are two links to iQontrol at the overview screen

### ISSUE THREAD

**Issue by sbormann** [sbormann/ioBroker.iqontrol#8]
I don't know how to customize io-package.json that
- There is only one link on overview-page
- There is a link at web-adapter-page
- There is a link at instances-page

Can anyone help?

**Comment by ldittmar81** [comment]
As I have already said: delete the welcome screen and you have only one more. :stuck_out_tongue:

**Comment by sbormann** [comment]
Corrected in 0.0.13:
welcomeScreen changed to welcomeScreenPro -> These will only appear in web-adapter, but not in overview.
