### ISSUE TITLE
Fehler mit JS-Controller Version 2.0.2 Beta

### ISSUE THREAD

**Issue by sigi2345** [sbormann/ioBroker.iqontrol#81]
**Screenshots & Logfiles**  
![Screenshot (4139)_LI](https://user-images.githubusercontent.com/41079106/65226208-bebdcb80-dac6-11e9-906d-29f377eeb605.jpg)

![Screenshot (4137)](https://user-images.githubusercontent.com/41079106/65226243-ced5ab00-dac6-11e9-9e50-2705594e6450.png)

**Versions:**  
 - Adapter version: 0.2.4
 - JS-Controller version: **2.0.2**
 - Node version: 10.16.3
 - Operating system: Windows

**Additional context**  
Neuer Beta JS-Controller installiert, seit dem funktioniert der Adapter nicht mehr Richtig.
Die UI wird geöffnet, aber es kommen keine Daten mehr und man kann auch keine Geräte mit den Icon Bleistift bearbeiten.
Sigi

**Comment by Apollon77** [comment]
Anything in the log?

**Comment by Apollon77** [comment]
maybe when you start adapter in debug mode?

**Comment by Apollon77** [comment]
PS: Debug mode can be nowe changed on the floy: system.adapter.NAME.X.logLevel :-)

**Comment by sbormann** [comment]
Hi Sigi,
bitte mal posten, was bei geöffneter Entwicklerkonsole (F12) gemeldet wird, sowohl in der Admin-Oberfläche, als auch im Frontend. Ist bestimmt irgendwas mit dem socket... LG

**Comment by Apollon77** [comment]
Wenn Socket dann sollte der controller 2.0 aber raus sein ... ... we will see :-)

**Comment by sbormann** [comment]
Ja, bin mal auf die Fehlermeldungen gespannt. Hatte noch keine Gelegenheit den 2.0 Controller zu testen - das mit dem Socket war nur so ein Gefühl ;)

**Comment by sigi2345** [comment]
![Screenshot (8)](https://user-images.githubusercontent.com/41079106/65343711-f10a1e80-dbd5-11e9-8a47-0423b78d9a82.png)

**Comment by Apollon77** [comment]
Und im normalen log ist nix? Port 8091 wird von wem bereitgestellt?

**Comment by sigi2345** [comment]
> Und im normalen log ist nix? Port 8091 wird von wem bereitgestellt?

Adapter WEB , diesen habe ich umgestellt weil ich ja 2 Installationen habe.

**Comment by Apollon77** [comment]
Du rennst denke ich auch in den Bug rein der im Forum berichtet wurde:

```
2019-09-20 20:39:45.438 - error: host.Medion(iobroker) TypeError: Cannot read property 'admin.admin' of undefined
at ObjectsInMemoryServer._readDir (C:\Program Files\iobroker\iobroker\node_modules\iobroker.js-controller\lib\objects\objectsInMemFileDB.js:584:50)
at checkFileRights (C:\Program Files\iobroker\iobroker\node_modules\iobroker.js-controller\lib\objects\objectsInMemFileDB.js:683:33)
at objects.checkFile (C:\Program Files\iobroker\iobroker\node_modules\iobroker.js-controller\lib\objects\objectsUtils.js:248:20)
a
```

Bitte mal auf die 2.0.5 warten und neu versuchen. Die sollte das fixen

**Comment by sigi2345** [comment]
Ok, 2.0.5 installiert. IQontrol auch neu installiert. Bleistift geht jetzt. Daten kommen keine. Kann es sein das keine Werte kommen weil ich den Web Adapter umgestellt habe? Auf Port 8107.

![Screenshot (15)_LI](https://user-images.githubusercontent.com/41079106/65371912-fa909680-dc68-11e9-807f-63ce48d13728.jpg)

**Comment by Apollon77** [comment]
Was zeigt Browser Konsole?

**Comment by sigi2345** [comment]
> Was zeigt Browser Konsole?

![Screenshot (18)_LI](https://user-images.githubusercontent.com/41079106/65372370-ab9a2f80-dc6f-11e9-9e07-f9fc5b92e077.jpg)

**Comment by Apollon77** [comment]
Deine object dB is file oder redis?

**Comment by sigi2345** [comment]
> Deine object dB is file oder redis?

file

**Comment by simatec** [comment]
Kann auf meiner Testumgebung den fehler auch bestätigen

**Comment by Apollon77** [comment]
Ich denke es hat was mit dem file abholen zu tun. Controller 2.0 ist da etwas strikter als vorher. Muss ich mir ansehen. 

Ich habe eine Vermutung. Die muss ich aber erst bestätigen.

**Comment by Apollon77** [comment]
Bitte mal die Ausgabe von „iobroker list files“ Posten.

**Comment by Apollon77** [comment]
Aber jetzt mal frech gefragt ... ist der Pfad korrekt? Da wo die 404er stehen das sind userimages ... muss das nicht "iqontrol.meta" als Basispfad sein?

**Comment by Apollon77** [comment]
Und BTW: Diese Migration der Userfiles die Du eingebaut hast per "rename" ... sorry aber die dürfte so nicht tun ... auch vorher nicht. Rename geht nur "innerhalb" einer "Basis-ID" ... Du willst ja aber von iqontrol -> iqontrol.meta verschieben, korrekt? Das kann rename nicht. Um das zu tun musst Du die Files lesen und neu schreiben

**Comment by Apollon77** [comment]
@sigi2345 Versuch mal so ein File was in deinem Letzten Screenshot ein Error 404 gab mit "iqontrol.meta" anstelle "iqontrol" im Browser aufzurufen. kommt es dann?

**Comment by Apollon77** [comment]
Weiter: Man kann mit controller 2.0 auch keine Bilder via Admin hochladen. grund: Der Pfad der ensteht ist userimages//filename.png ... wenn man ins "root" hochlädt ... Ich hab das im controller 2.0 jetzt gefixt das der Pfad korrekt umgeschrieben wird (also mehrere "/" korrekt ersetzt durch eins), aber bin nicht sicher ob das 100% kompatibel zu vorher ist.

Mit den letzten Änderungen (kommt nachher als 2.0.6) kann ich zumindestens Images hochladen via iqontrol aktuelle Version.

Verzeichnisse gehen immer noch nicht. Das würde ich dich bitten im Adapter zu fixen. Aktuell liesst Du Verzeichnisse und wenn Sie keinen Fehler liefern sind sie existent. Das war bisher auf File ebene korrekt, aber auch hier war es schon möglich ganze Verzeichnisstrukturen auf einen Schlag anzulegen auch wenn die Parents nicht da waren. Also um zu checken ob ein Dir da ist ist es korrekter das Parentverzeichnis zu lesen und zu prüfen ob da ein Eintrag mit "isDir=true" mit dem Namen zurückkommt.

**Comment by sigi2345** [comment]
@sigi2345 Versuch mal so ein File was in deinem Letzten Screenshot ein Error 404 gab mit "iqontrol.meta" anstelle "iqontrol" im Browser aufzurufen. kommt es dann?

Mache ich, habe einen kleinen in der Birne. Bruder hat 50er Feier.

**Comment by Apollon77** [comment]
2.0.6 vom controller auf GitHub.
@sigi2345 Koi stress

**Comment by sbormann** [comment]
> Verzeichnisse gehen immer noch nicht. Das würde ich dich bitten im Adapter zu fixen. Aktuell liesst Du Verzeichnisse und wenn Sie keinen Fehler liefern sind sie existent. Das war bisher auf File ebene korrekt, aber auch hier war es schon möglich ganze Verzeichnisstrukturen auf einen Schlag anzulegen auch wenn die Parents nicht da waren. Also um zu checken ob ein Dir da ist ist es korrekter das Parentverzeichnis zu lesen und zu prüfen ob da ein Eintrag mit "isDir=true" mit dem Namen zurückkommt.

Hi, kannst Du mir noch ein paar Tipps geben, was ich genau nachbessern soll? Wie kann man ganze Verzeichnisbäume anlegen, auch wenn die parents nicht da sind? Und wo soll ich das mit dem parent und isDir=true machen? In der checkExistance-Funktion (Zeile 2206)? Danke und VG!

**Comment by sigi2345** [comment]
Erkenntnis ist: iqcontrol geht mit js 1.5.14
Mit 2.0.6 nicht. Es kommen keine Werte . Backend geht aber.

**Comment by Apollon77** [comment]
Also ich baue noch am file Kram. Vllt krieg ich es kompatibel. Warum keine Werte kommen wäre interessant zu wissen woran es liegt. Da habe ich keine Erklärung.

**Comment by Apollon77** [comment]
Also File Handling tut nun mit der 2.0.7 vom controller wie vorher.

Jetzt: Woran kann es liegen das keine Daten kommen?

**Comment by sigi2345** [comment]
> Also File Handling tut nun mit der 2.0.7 vom controller wie vorher.
> 
> Jetzt: Woran kann es liegen das keine Daten kommen?

Geht leider noch nicht.
Mir ist aufgefallen, das wenn ich irgendetwas ändere und auf speichern klicke diese Meldung kommt.
Dieses Verhalten habe ich beim Normalen System nicht. Es scheint so als die Änderungen nicht übernommen werden.
![Screenshot (33)](https://user-images.githubusercontent.com/41079106/65395095-88b66b00-dd96-11e9-95fc-aca865cbcf1c.png)

**Comment by sbormann** [comment]
> Also File Handling tut nun mit der 2.0.7 vom controller wie vorher.

Worldclass! Danke Ingo!

> Jetzt: Woran kann es liegen das keine Daten kommen?

Gibt es denn keinen Fehler in der Konsole? Ich habe bislang noch keine 2.0 Testumgebung...

**Comment by Apollon77** [comment]
Wie bekommt iqontrol frontend denn die Daten? Wo subscribst du auf welche States?

**Comment by sigi2345** [comment]
> Gibt es denn keinen Fehler in der Konsole? Ich habe bislang noch keine 2.0 Testumgebung...

Mal einen Debug Log:

[List_files.zip](https://github.com/sbormann/ioBroker.iqontrol/files/3640233/List_files.zip)

**Comment by sbormann** [comment]
Danke Sigi, da scheint schon mal alles OK zu sein. Kannst Du jetzt noch mal vom Frontend ein Log senden aus der Entwicklerkonsole (F12)?

**Comment by sbormann** [comment]
> Wie bekommt iqontrol frontend denn die Daten? Wo subscribst du auf welche States?

Der Socket wird ab Zeile 459 konfiguriert:
https://github.com/sbormann/ioBroker.iqontrol/blob/8aaefaf0a40f1e2d48d785aafb0dbb11321aca60/www/index.js#L459

Die ConnectionCallbacks werden direkt im Anschluss angelegt.

Und in Zeile 5306 an Ende der $(document).ready-Funktion wird der Socket gestartet:
https://github.com/sbormann/ioBroker.iqontrol/blob/8aaefaf0a40f1e2d48d785aafb0dbb11321aca60/www/index.js#L5306

**Comment by sigi2345** [comment]
> Kannst Du jetzt noch mal vom Frontend ein Log senden aus der Entwicklerkonsole (F12)?

Was meinst du?

**Comment by sbormann** [comment]
Hmm, das log gibt nichts her, da sieht es eigentlich so aus, als würde er alles richtig bekommen...

**Comment by sigi2345** [comment]
> Hmm, das log gibt nichts her, da sieht es eigentlich so aus, als würde er alles richtig bekommen...

Ja, dachte es mir. Kannst es gerne per TeamViewer mal ansehen.

**Comment by Apollon77** [comment]
Nochmal die Frage: Wie funktioniert denn das "Aktuelle State Werte bekommen?" Ok, ich sehe in conn.js ein "subscribe "*" ". Das sollte an sich tun

@sigi2345 Hast Du auch vis? Bekommt das noch aktuelle Werte?

**Comment by sigi2345** [comment]
> @sigi2345 Hast Du auch vis? Bekommt das noch aktuelle Werte?

Ja, und auf meinen anderen System geht es.

**Comment by Apollon77** [comment]
Ok, also ich habe bei mir mal getestet mit Debugger auf meinen 2.0er testsystem. Ich bekomme mal mindestens alle State-Changes rein auf "stateChanged" Ebene. Da ich aber da gerade kein echten Frontend habe ist das nur die Datenebene. Wenn das aber tut sollte die 2.0 generell tun wie geplant. (Mal abgesehend avon das subscribe(*) zB via clkoud für ziemlichen Overhead führen kann.

@sigi2345 und vis mit 2.0er controller tut auch?

Also mir würde jetzt nur eine Debugging session einfallen via Teamviewer oder sowas ... Da ist aber bestimmt @sbormann besser also ich ;-)

**Comment by sbormann** [comment]
> Ja, dachte es mir. Kannst es gerne per TeamViewer mal ansehen.
@sigi2345 Gute Idee, das machen wir. Heute ist es mir allerdings zu spät. Können ja morgen mal schauen, ob wir gemeinsam Zeit finden.

**Comment by sigi2345** [comment]
> > Ja, dachte es mir. Kannst es gerne per TeamViewer mal ansehen.
> > @sigi2345 Gute Idee, das machen wir. Heute ist es mir allerdings zu spät. Können ja morgen mal schauen, ob wir gemeinsam Zeit finden.

Ok

**Comment by sigi2345** [comment]
> @sigi2345 und vis mit 2.0er controller tut auch?

iqcontrol geht mit 1er controller
mit 2er werden keine Daten angezeigt, Vis geht überall.

**Comment by Apollon77** [comment]
Ich bin hoch gespannt auf die Lösung. 

@sigi2345 mal blöde Frage: werden Daten gesetzt wenn sich ein Wert mit 2,0
ändert? Nicht das irgendwie das initiale laden der Daten nur kaputt ist?

Ich experimentiere morgen sich mal bissl rum.

**Comment by sigi2345** [comment]
> werden Daten gesetzt wenn sich ein Wert mit 2,0
> ändert?

Meinst du in den Objekten?

**Comment by Apollon77** [comment]
Ne meinte im iqontrol frontend

**Comment by sigi2345** [comment]
> Ne meinte im iqontrol frontend

Hm Wo und Wie sehe ich das?

**Comment by Apollon77** [comment]
im Fiqontrol rontend? Das nach einem update der Werte plötzlich welche da sind?

**Comment by sigi2345** [comment]
> im Fiqontrol rontend? Das nach einem update der Werte plötzlich welche da sind?

Nein

**Comment by ihavenonick** [comment]
Bei mir unter Debian Buster auch keine Daten und Schalten mehr möglich.

**Comment by Apollon77** [comment]
So ... ich habs jetzt konfiguriert ... und es tut ... das Problem ist eher das das Admin FE wohl nichts epciehrn kann ... ich musste also diese linkedStates (BTW keine offizielle Rolle tttssstttttsssttttssss ...)  manuell aufsetzen.
@sigi2345 passt bei dir das setup der "linked states" denn noch?

**Comment by sigi2345** [comment]
> @sigi2345 passt bei dir das setup der "linked states" denn noch?

Was für linked states? Du sprichst immer Spanisch mit mir.

Sollte es also schon gehen? Controller update nötig?

**Comment by Apollon77** [comment]
@sigi2345 Schau mal in die Objekte vom iqontrol.0 ... da gibt es die views und alle deine angezeigten Datenpunkte ... und die haben dort states mit dem namen und .STATE am End eund sowas ... zeig mal screenshot bitte bzw vergleiche mal die anzeige im Admin zwischen 1.5 und 2.0

Ich bin jetzt soweit:
- Also ich kann im Admin ändern. Manchmal beim speichern kommt die Medung wegen "Da kann was nicht gespeichert werden..." Wann das kommt weiss ich nicht. wenns tut ist aber alles ok und das Objekt aktuell.
Dann denke ich das der Adater neu startet und die Infos aus dem Objekt in die ganzen einzelobjekte synct (@sbormann  korrekt?) ... das passiert irgendwie nicht

**Comment by sigi2345** [comment]
> * das passiert irgendwie nicht

Ja, das habe ich oben schon geschrieben.

1.5
![Screenshot (55)](https://user-images.githubusercontent.com/41079106/65517397-f1126300-dee2-11e9-9728-16f971154c32.png)

RAW:
`{
  "from": "system.adapter.iqontrol.0",
  "user": "system.user.admin",
  "ts": 1569327867811,
  "common": {
    "name": "STATE",
    "desc": "created by iQontrol",
    "role": "linkedState",
    "type": "string",
    "def": "",
    "read": true,
    "write": false,
    "icon": ""
  },
  "native": {},
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "iqontrol.0.Views.Test.0005__CCU2.STATE",
  "type": "state"
}`

2.0
![Screenshot (52)](https://user-images.githubusercontent.com/41079106/65517415-f96a9e00-dee2-11e9-8845-57cbd8def128.png)

RAW:

`{
  "from": "system.adapter.iqontrol.0",
  "user": "system.user.admin",
  "ts": 1569328088263,
  "common": {
    "name": "STATE",
    "desc": "created by iQontrol",
    "role": "linkedState",
    "type": "string",
    "def": "",
    "read": true,
    "write": false,
    "icon": ""
  },
  "native": {},
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "iqontrol.0.Views.Test.0005__CCU2.STATE",
  "type": "state"
}`

**Comment by sbormann** [comment]
Oha, immerhin, der Fehler scheint gefunden. Gefällt mir aber nicht, weil ich ehrlichgesagt mit dem async und chaining voll auf Kriegsfuß stehe. Ich habs einfach nach wie vor noch nicht voll kapiert, wie das genau geht. Aber hilft ja nix, ich werde da wohl ran müssen. Vielleicht habe ich es anschließend dann endlich mal kapiert :)
Danke Ingo und Siggi für die Hilfe bis hier her!

**Comment by sigi2345** [comment]
> Danke Ingo und Siggi für die Hilfe bis hier her!

Bitte sehr.
Frage, gibt es ev. eine Möglichkeit als Option default Werte zu laden? Also Farbe, Schriften usw. zurück zu setzen.

**Comment by sbormann** [comment]
> Frage, gibt es ev. eine Möglichkeit als Option default Werte zu laden? Also Farbe, Schriften usw. zurück zu setzen.

Mit dem (X) hinter jeder Option wird wieder der Default-Wert gesetzt.

**Comment by Apollon77** [comment]
@sbormann also ich habe die eine genannte STelle mal umgebaut bei mir. einfach alle "var" bei den Variablendeklarationen als const (wenn nicht mehr geändert sondenr nur einmalig erstellt) oder "let" definieren. Dann kannst Du fast den code von mir nehmen und in deiner setStateValue kannst du es direkt genauso umbauen. Das tut dann.

var = "globaler Scope" = function
const/let = "Lokaler Scope aktueller "block" (quasi { ...} ) und "nach unten"

**Comment by sbormann** [comment]
So, die 0.2.6 ist online mit einer angepassten main.js. Habe alles jetzt mit .then verknüpft und var zu let gemacht. Läuft bei mir mit dem alten Controller. Läuft es jetzt mit dem 2.0er Controller???

@Apollon77 : Bei Zeile 330 bin ich mir nicht sicher - hier nutze ich weiter ein callback. Ist das richtig so? Wenn nein, wie muss es angepasst werden?

**Comment by Apollon77** [comment]
Zu Zeile 330: In meiner Welt ist der Chargeback dort falsch weil Du async nutzt (mal abgesehen davon: wer zwingt dich dazu? ;-)) ) ... @AlCalzone ... Tip how to change it?

**Comment by sigi2345** [comment]
Hurra!!!!! Perfekt funktioniert.
![Screenshot (57)](https://user-images.githubusercontent.com/41079106/65551253-c5fb3400-df21-11e9-84af-77d923af1630.png)

**Comment by Apollon77** [comment]
Ich notiere 0.2.6+ für controller 2.0 :-) Good Job!
@sbormann Ich hab AlCalzone nochmal die Frage geschickt ... ich nutze Async stuff selbst noch nicht, von daher kann ich wenig helfen

**Comment by sbormann** [comment]
Mann, da bin ich froh 😁 

Noch mal zu Zeile 330:

@sigi2345 : Kannst Du mal bitte testweise ein Gerät löschen? Wenn die kritische Zeile 330 funktioniert, müsste das Gerät auch im Frontend verschwinden (nach Reload natürlich). Wenn Zeile 330 noch Probleme macht, bleibt es hingegen im Frontend (Zeile 330 ff sorgt dafür, dass im Backend nicht mehr vorhandene Datenpunkte auch aus den ioBroker-Objekten und damit im Frontend entfernt werden).

**Comment by Apollon77** [comment]
@sbormann naja so oder so sollte man async und callbacks nicht mischen, also auch wenn er tut solltest Du es so umbauen wie es sein muss :-)

Mein tipp wäre übrgens:
```
		this.getAdapterObjectsAsync().then(obj => {...});
```
Versuch mal. DIese Methode hat eh keinen "err" Parameter 8auch nicht als zweiten Parameter.

**Comment by sbormann** [comment]
Perfekt, Dein tipp funktioniert! Kommt dann im nächsten Update.
Danke Euch! Schließe den Issue.

**Comment by simatec** [comment]
Habe soeben das ganze auch noch einmal mit den aktuellen Versionen auf meinem Testsystem durchgespielt.
Werte kommen jetzt und schalten kann man auch. Allerdings funktionieren jetzt keine PopUp Menüs mehr.
Habe es mit dem Gerätetyp Thermostat und Garagentür getestet und konnte in beiden Fällen das Popup nicht öffnen, um Werte wie z.B. die Temperatur zu regeln.

Iqontrol: 0.2.6
JS-Controller: 2.0.9

**Comment by ihavenonick** [comment]
geht bei mir
![grafik](https://user-images.githubusercontent.com/36501310/65578858-e6a1a900-df76-11e9-87f0-7e1ee7934dd9.png)

**Comment by Apollon77** [comment]
Dann am besten neues Issue anlegen :-))
Link zu Browser Konsole im Forum  https://forum.iobroker.net/post/303429

**Comment by Apollon77** [comment]
BTW: Die Codezeile verweist auf _linkedWindowOpenReportingId ... was ist die beu euch woes Fehler gitb? gesetzt oder nicht?

**Comment by sigi2345** [comment]
> Habe soeben das ganze auch noch einmal mit den aktuellen Versionen auf meinem Testsystem durchgespielt.
> Werte kommen jetzt und schalten kann man auch. Allerdings funktionieren jetzt keine PopUp Menüs mehr.
> Habe es mit dem Gerätetyp Thermostat und Garagentür getestet und konnte in beiden Fällen das Popup nicht öffnen, um Werte wie z.B. die Temperatur zu regeln.
> 
> Iqontrol: 0.2.6
> JS-Controller: 2.0.9

Schließe mich an:

![Screenshot (62)](https://user-images.githubusercontent.com/41079106/65582294-69c5fd80-df7d-11e9-8243-2609527c84d4.png)

**Comment by sigi2345** [comment]
> BTW: Die Codezeile verweist auf _linkedWindowOpenReportingId ... was ist die beu euch woes Fehler gitb? gesetzt oder nicht?

Nein

**Comment by ihavenonick** [comment]
Ja, aber bei mir funktioniert es auch:
![grafik](https://user-images.githubusercontent.com/36501310/65585075-2752ef80-df82-11e9-8932-4dc19fe1d60e.png)

**Comment by simatec** [comment]
WindowOpenReporting ist doch ein Datenpunkt für das thermostat, welches mit einem Fensterkontakt verknüpft ist und hat nichts mit dem PopUp zu tun.

Bei dem Gerät "Garagentor" gibt es z.B. WindowOpenReporting garnicht ...

**Comment by sigi2345** [comment]
> Ja, aber bei mir funktioniert es auch:
Automatisch oder Manuel erstellt?

**Comment by ihavenonick** [comment]
Alles automatisch angelegt und das Popup kommt bei mir auch zum Einstellen der Temperatur am Thermostat.

**Comment by simatec** [comment]
Bei mir passiert in der Console folgendes beim Aufruf und die Werte kommen nicht sofort. Erst nach ändern der Werte werden sie bis zum nächsten Aufruf angezeigt.

`Already waiting for object: javascript.0.Test.WZTemp
index.js:649 Fetch object: javascript.0.Test.WZTemp2
2index.js:645 Already waiting for object: javascript.0.Test.WZTemp2
index.js:655 Fetched Object: javascript.0.Test.Fenster2
index.js:655 Fetched Object: javascript.0.Test.Fenster3
index.js:655 Fetched Object: javascript.0.Test.WZLicht
index.js:655 Fetched Object: javascript.0.Test.WZLicht2
index.js:655 Fetched Object: javascript.0.Test.WZTemp
index.js:3097 Uncaught TypeError: Cannot read property 'val' of undefined
    at Array.updateFunction (index.js:3097)
    at updateState (index.js:1271)
    at index.js:656
    at Object.<anonymous> (conn.js:918)
    at n.onack (socket.io.js:3)
    at n.onpacket (socket.io.js:3)
    at n.<anonymous> (socket.io.js:3)
    at n.emit (socket.io.js:2)
    at n.ondecoded (socket.io.js:1)
    at s.<anonymous> (socket.io.js:3)
updateFunction @ index.js:3097
updateState @ index.js:1271
(anonymous) @ index.js:656
(anonymous) @ conn.js:918
n.onack @ socket.io.js:3
n.onpacket @ socket.io.js:3
(anonymous) @ socket.io.js:3
n.emit @ socket.io.js:2
n.ondecoded @ socket.io.js:1
(anonymous) @ socket.io.js:3
r.emit @ socket.io.js:1
s.add @ socket.io.js:1
n.ondata @ socket.io.js:1
(anonymous) @ socket.io.js:3
n.emit @ socket.io.js:2
n.onPacket @ socket.io.js:2
(anonymous) @ socket.io.js:2
n.emit @ socket.io.js:2
n.onPacket @ socket.io.js:2
n.onData @ socket.io.js:2
ws.onmessage @ socket.io.js:3
index.js:655 Fetched Object: javascript.0.Test.WZTemp2
index.js:3097 Uncaught TypeError: Cannot read property 'val' of undefined
    at Array.updateFunction (index.js:3097)
    at updateState (index.js:1271)
    at index.js:656
    at Object.<anonymous> (conn.js:918)
    at n.onack (socket.io.js:3)
    at n.onpacket (socket.io.js:3)
    at n.<anonymous> (socket.io.js:3)
    at n.emit (socket.io.js:2)
    at n.ondecoded (socket.io.js:1)
    at s.<anonymous> (socket.io.js:3)
updateFunction @ index.js:3097
updateState @ index.js:1271
(anonymous) @ index.js:656
(anonymous) @ conn.js:918
n.onack @ socket.io.js:3
n.onpacket @ socket.io.js:3
(anonymous) @ socket.io.js:3
n.emit @ socket.io.js:2
n.ondecoded @ socket.io.js:1
(anonymous) @ socket.io.js:3
r.emit @ socket.io.js:1
s.add @ socket.io.js:1
n.ondata @ socket.io.js:1
(anonymous) @ socket.io.js:3
n.emit @ socket.io.js:2
n.onPacket @ socket.io.js:2
(anonymous) @ socket.io.js:2
n.emit @ socket.io.js:2
n.onPacket @ socket.io.js:2
n.onData @ socket.io.js:2
ws.onmessage @ socket.io.js:3
index.js:3097 Uncaught TypeError: Cannot read property 'val' of undefined
    at Array.updateFunction (index.js:3097)
    at updateState (index.js:1271)
    at index.js:3480
    at index.js:677
    at n.<anonymous> (conn.js:647)
    at n.onack (socket.io.js:3)
    at n.onpacket (socket.io.js:3)
    at n.<anonymous> (socket.io.js:3)
    at n.emit (socket.io.js:2)
    at n.ondecoded (socket.io.js:1)
updateFunction @ index.js:3097
updateState @ index.js:1271
(anonymous) @ index.js:3480
(anonymous) @ index.js:677
(anonymous) @ conn.js:647
n.onack @ socket.io.js:3
n.onpacket @ socket.io.js:3
(anonymous) @ socket.io.js:3
n.emit @ socket.io.js:2
n.ondecoded @ socket.io.js:1
(anonymous) @ socket.io.js:3
r.emit @ socket.io.js:1
s.add @ socket.io.js:1
n.ondata @ socket.io.js:1
(anonymous) @ socket.io.js:3
n.emit @ socket.io.js:2
n.onPacket @ socket.io.js:2
(anonymous) @ socket.io.js:2
n.emit @ socket.io.js:2
n.onPacket @ socket.io.js:2
n.onData @ socket.io.js:2
ws.onmessage @ socket.io.js:3
2index.js:3097 Uncaught TypeError: Cannot read property 'val' of undefined
    at Array.updateFunction (index.js:3097)
    at updateState (index.js:1271)
    at index.js:491
updateFunction @ index.js:3097
updateState @ index.js:1271
(anonymous) @ index.js:491
setTimeout (async)
onUpdate @ index.js:487
(anonymous) @ conn.js:373
n.emit @ socket.io.js:2
n.onevent @ socket.io.js:3
n.onpacket @ socket.io.js:3
(anonymous) @ socket.io.js:3
n.emit @ socket.io.js:2
n.ondecoded @ socket.io.js:1
(anonymous) @ socket.io.js:3
r.emit @ socket.io.js:1
s.add @ socket.io.js:1
n.ondata @ socket.io.js:1
(anonymous) @ socket.io.js:3
n.emit @ socket.io.js:2
n.onPacket @ socket.io.js:2
(anonymous) @ socket.io.js:2
n.emit @ socket.io.js:2
n.onPacket @ socket.io.js:2
n.onData @ socket.io.js:2
ws.onmessage @ socket.io.js:3
ind`

**Comment by sigi2345** [comment]
> > Frage, gibt es ev. eine Möglichkeit als Option default Werte zu laden? Also Farbe, Schriften usw. zurück zu setzen.
> 
> Mit dem (X) hinter jeder Option wird wieder der Default-Wert gesetzt.

Ja, das weis ich. Ich meine ALLE auf einmal auf Default Wert.

**Comment by sbormann** [comment]
Hi, nein, diese Funktion gibt es nicht, dazu musst Du leider viele (X)e drücken :)

**Comment by sbormann** [comment]
> > Habe soeben das ganze auch noch einmal mit den aktuellen Versionen auf meinem Testsystem durchgespielt.
> > Werte kommen jetzt und schalten kann man auch. Allerdings funktionieren jetzt keine PopUp Menüs mehr.
> > Habe es mit dem Gerätetyp Thermostat und Garagentür getestet und konnte in beiden Fällen das Popup nicht öffnen, um Werte wie z.B. die Temperatur zu regeln.
> > Iqontrol: 0.2.6
> > JS-Controller: 2.0.9
> 
> Schließe mich an:
> 
> ![Screenshot (62)](https://user-images.githubusercontent.com/41079106/65582294-69c5fd80-df7d-11e9-8243-2609527c84d4.png)


Hi Sigi (und die Anderen mit dem Problem): Bitte noch mal bei der Fehlermeldung ganz rechts auf das index.js:3105 klicken und mit den Screenshot schicken, wo genau in der Zeile die rote Markierung ist (also an welcher Stelle in der Zeile es hakt). 

Ergänzend wäre noch ganz gut, den Inhalt der Variablen _linkedWindowOpenReportingId und states[_linkedWindowOpenReportingId] zu kennen: Dazu diesen Text in der Zeile markieren und mit der Maus drüber fahren, dann wird der Inhalt der Variable in einem Popup angezeigt. Das ebenfalls schicken bitte.

VG

**Comment by sigi2345** [comment]
> Hi Sigi (und die Anderen mit dem Problem): Bitte noch mal bei der Fehlermeldung ganz rechts auf das index.js:3105 klicken und mit den Screenshot schicken, wo genau in der Zeile die rote Markierung ist (also an welcher Stelle in der Zeile es hakt).

`if (typeof _linkedWindowOpenReportingId !== udef && typeof states[_linkedWindowOpenReportingId] !== udef && typeof states[_linkedWindowOpenReportingId].val !== udef && states[_linkedWindowOpenReportingId].val) $("[data-iQontrol-Device-ID='" + _deviceId + "'].iQontrolDeviceState").append("&nbsp;<image src='./images/wot.png' style='width:12px; height:12px;' />");`

![Screenshot (73)](https://user-images.githubusercontent.com/41079106/65666104-42366a00-e03d-11e9-8015-f92a5c39862d.png)

**Comment by Apollon77** [comment]
@sbormann umfalls "undef" auch null? :-)

**Comment by simatec** [comment]
Ich habe mir mal den Code angeschaut und den Fehler gefixt.
Jetzt kommen alle Werte sauber und die Popups gehen auch wieder ...

https://github.com/sbormann/ioBroker.iqontrol/pull/83

**Comment by sigi2345** [comment]
> Ich habe mir mal den Code angeschaut und den Fehler gefixt.
> Jetzt kommen alle Werte sauber und die Popups gehen auch wieder ...
> 
> Hier der Link zum PR: #83

Bei mir nicht? Gibt es eine neue Version?

**Comment by simatec** [comment]
> > Ich habe mir mal den Code angeschaut und den Fehler gefixt.
> > Jetzt kommen alle Werte sauber und die Popups gehen auch wieder ...
> > Hier der Link zum PR: #83
> 
> Bei mir nicht? Gibt es eine neue Version?

Hi Sigi, mein PR ist noch offen und nicht in der aktuellen Version.
Hier die Änderungen, falls du es händisch testen willst:
https://github.com/sbormann/ioBroker.iqontrol/pull/83/files

**Comment by sbormann** [comment]
Hi
parallel zu @simatec hatte ich auch ein Bugfix entwickelt :)
Habe es mit Deinem PR noch mal abgeglichen. Hoffe es läuft?! Bitte um Rückmeldung!
0.2.8 ist ab sofort online.
LG

**Comment by sigi2345** [comment]
> Hi
> parallel zu @simatec hatte ich auch ein Bugfix entwickelt :)
> Habe es mit Deinem PR noch mal abgeglichen. Hoffe es läuft?! Bitte um Rückmeldung!
> 0.2.8 ist ab sofort online.
> LG

PERFEKT! Funktioniert wieder und ist viel schneller.

**Comment by Apollon77** [comment]
@sbormann blöde Frage ... hatte der zweite Fehler irgendwas mit Controller 2.0 zu tun oder nicht? Wenn ja: Windverhältnisse er sich anders als 1.5?

**Comment by sbormann** [comment]
Tja, das ist eine gute Frage. Ich weiß es selbst nicht genau.
Jedenfalls war die Abfrage auf nicht vorhandene Objekte nicht korrekt formuliert, so dass es vorkommen konnte, dass ein NULL-Objekt abgefragt wurde, was dann natürlich keinen .val-Key hatte. Warum das im alten Controller funktioniert hat - da habe ich leider keinen Plan...

**Comment by Apollon77** [comment]
Ich denke ich weiss es.
* controller 1.5 beim zugriff auf ein state was nich nie einen Wert hatte -> undefined
* controller 2.0 beim zugriff auf ein state was nich nie einen Wert hatte -> null

Gleiches an sich bei States mit einem Expire-Wert:
* controller 1.5 nach expire ist es ein objects mit lc, ts und so und .val=null
* controller 2.0 nach expire -> null (auch kein Objekt)

Kann es das sein?

**Comment by sbormann** [comment]
Ja, das würde passen!

**Comment by simatec** [comment]
Gut zu wissen, dann muss ich bei meinen Adaptern auch etwas ändern

**Comment by sbormann** [comment]
Macht das neue Verhalten Sinn? Wäre es nicht besser, das ursprüngliche Verhalten beizubehalten?

**Comment by Apollon77** [comment]
Das diskutieren wir gerade. Es würde redis technisch ein paar Dinge komplizierter machen.  

Die Unterschiede sind mir am Ende erst gestern bewusst geworden. Gibt ein js-Controller issue für die Diskussion ... macht gern mit.

**Comment by Apollon77** [comment]
ABER: beide Dinge waren übrigens auch in 1.5.x anders sobald man States in redis genutzt hat....
