### ISSUE TITLE
Battery icon

### ISSUE THREAD

**Issue by huk13** [sbormann/ioBroker.iqontrol#82]
display voltage state in addition to percentage in icon. Similar to temperature and humidity in thermometer icon

**Comment by sbormann** [comment]
You can attach it as additional info to every device. It is not displayed as you suggeseted in the tile, but if you open the dialog you can see it. Hope that helps! Greetings

**Comment by huk13** [comment]
I have thought that for the battery device it would be useful to see the voltage level in addition to the charge percentage in the tile rather than to have to open the dialog. Charge and voltage are both characteristic quantities of a battery.
Thanks and regard
HUK

**Comment by sbormann** [comment]
Ah, yes, i misunderstood. That is indead a good idea. Will implement that. Thanks.

**Comment by huk13** [comment]
Hi,

sorry to pick this enhancement up again.

The voltage still does not show up within the battery tile. I have the following situation: I select battery operated device (such as Xiaomi contact) and declare it as battery (Akku). Then I connect the data point voltage to the corresponding state of this device. The voltage value does not show up in the tile. Do I do something wrong or incomplete?

Thanks for your help and regards,

HUK

**Comment by sbormann** [comment]
Hi,

your config schould look similar to:
![image](https://user-images.githubusercontent.com/49171332/66345721-e16a3400-e950-11e9-84d4-97cd7690b5e8.png)

Have you installed the last version of iqontrol (0.2.11)?

If not, update via the github-icon in ioBroker and then follow:
https://github.com/sbormann/ioBroker.iqontrol#troubleshooting

Best luck. Please report, if it works now!

**Comment by huk13** [comment]
Hi,
I use 0.2.11. A screenshot is attached. I want to display a Xiaomi Temp/Humidity sensor as battery to monitor the voltage and charge level. The charge level (%) is shown on the bottom of the battery tile. Charging is indicated, but no voltage.
Thanks for your time and help.
Regards,
HUK

**Comment by sbormann** [comment]
Hi, sorry, screenshot is missing.

**Comment by huk13** [comment]
[cid:image001.png@01D57E75.68F94E20]Hi,
I use 0.2.11. A screenshot is attached. I want to display a Xiaomi Temp/Humidity sensor as battery to monitor the voltage and charge level. The charge level (%) is shown on the bottom of the battery tile. Charging is indicated, but no voltage.
Thanks for your time and help.
Regards,
HUK

**Comment by sbormann** [comment]
Sorry, there is still no screenshot. Please dont reply by mail, upload picture directly on github.

**Comment by huk13** [comment]
![battery](https://user-images.githubusercontent.com/53121010/66547026-9f064a00-eb3e-11e9-96e8-27f837bc8a5a.png)
![Picture1](https://user-images.githubusercontent.com/53121010/66547862-71220500-eb40-11e9-822f-3da9538316bc.png)
Here are the screenshots.
Thanks
HUK

**Comment by sbormann** [comment]
Please send the raw of your temperature and voltage datapoint - maybe they are nit compatible. You can try to override for example the role and type iqontrol uses via the wrench icon. Maybe that helps?

**Comment by huk13** [comment]
Here are the object data points for what is called Test battery state, the right Battery tile (battery % now 97%). Nothing done with the wrenches.
![Picture1](https://user-images.githubusercontent.com/53121010/66633629-8ca61200-ec0b-11e9-99e9-16c223e533af.png)
Thanks,
HUK

**Comment by huk13** [comment]
After the last 4 updates of the adapters (incl. web) it works!
![Picture1](https://user-images.githubusercontent.com/53121010/66644183-96864000-ec20-11e9-807c-eae2b3de83a7.png)
How can I display more digits for Voltage?
Thanks,
HUK

**Comment by huk13** [comment]
`{
  "from": "system.adapter.zigbee.0",
  "user": "system.user.admin",
  "ts": 1570378914144,
  "common": {
    "name": "Battery voltage",
    "type": "number",
    "unit": "V",
    "role": "battery.voltage",
    "read": true,
    "write": false,
    "icon": "img/battery_v.png"
  },
  "native": {},
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "zigbee.0.00158d0002ca02cd.voltage",
  "type": "state"
}`

**Comment by huk13** [comment]
Sorry, I misinterpreted your mail. Here is the raw of the voltage data point:
{
  "from": "system.adapter.zigbee.0",
  "user": "system.user.admin",
  "ts": 1570378914144,
  "common": {
    "name": "Battery voltage",
    "type": "number",
    "unit": "V",
    "role": "battery.voltage",
    "read": true,
    "write": false,
    "icon": "img/battery_v.png"
  },
  "native": {},
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "zigbee.0.00158d0002ca02cd.voltage",
  "type": "state"
}
and here the temperature:
{
  "type": "state",
  "common": {
    "name": "Temperature",
    "type": "number",
    "unit": "°C",
    "read": true,
    "write": false,
    "role": "value.temperature"
  },
  "from": "system.adapter.zigbee.0",
  "user": "system.user.admin",
  "ts": 1570378914141,
  "_id": "zigbee.0.00158d0002ca02cd.temperature",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "native": {}
}
Regards,
HUK

**Comment by sbormann** [comment]
Hi, it is automatically rounded to 1 digit after comma. 
You can use the ADDITIONAL_INFO-Datapoint to display more digits in the dialog.
In the tile this is not possible.
