### ISSUE TITLE
automatische Rückkehr zur Startseite

### ISSUE THREAD

**Issue by simatec** [sbormann/ioBroker.iqontrol#85]
Hallo,

erstmal danke für den Klasse Adapter.
Was ich mir als Feature noch wünschen würde, wäre die Einstellung in den Optionen, dass nach einer Zeit x zur Startseite automatisch zurückgekehrt wird.
Da ich es als VIS auf meinem Wandtablet nutz, wäre das in meinen Augen Sinnvoll, um beim nächsten vorbeigehen am Tablet wieder die Startseite sehen zu können.

**Comment by sbormann** [comment]
Hi, gute Idee! Muss mal überlegen, wie man das am besten implementiert.

**Comment by simatec** [comment]
Super ... danke schonmal vorab.

**Comment by sbormann** [comment]
Hi, habe das ganze in der 0.2.9 implementiert. Unter Optionen/Sonstiges kann das ganze aktiviert werden. Sowohl die Zeit, also auch die View, die nach dieser Inaktivitäts-Dauer aufgerufen wird, sind dort einstellbar. 

Bei mir klappts, bin gespannt auf die Rückmeldungen! 

VG!

**Comment by simatec** [comment]
Funktioniert perfekt bei mir 👌

**Comment by IQontrol-Nutzer** [comment]
Hallo, danke für die super IQontrol Visualisierung!
Nur durch diese Visu konnte ich als Neueinsteiger alles so visualisieren, wie ich es mir vorgestellte habe!

Jedoch stehe ich vor einem Problem mit dem automatischen Seitenwechsel....

Da ich nicht möchte, dass sich bei meinen neuen Geräten die Hauptseite "einbrennt" habe ich mir gedacht ich nutze die automatische Seitenwechsel-Funktion, als Schutz.
Meine Idee war daher, dass ich die Seiten im Minutentakt durchlaufen lasse...
nur bekomme ich das irgendwie nicht ganz hin mit dieser Funktion?

hat irgendwer eine Idee wie ich das umsetzen kann?
