### ISSUE TITLE
Pin Abfrage um Wert zu setzen

### ISSUE THREAD

**Issue by kwittwer** [sbormann/ioBroker.iqontrol#86]
Hallo, 
zunächst mal, das ist ein super Projekt! Tolle Arbeit danke dafür! 
ich würde mir noch eine Pin-Abfrage wünschen damit die beispielsweise die Alarmanlage nur von bestimmten Bedienern ein/ausgeschaltet werden kann. 
VG

**Comment by sbormann** [comment]
Gute Idee. Werde das in der nächsten Version (erstmal quick and dirty mit einem einfachen Browser-Eingabefeld) einbauen, das sollte sich recht leicht erledigen lassen.
LG!

**Comment by sbormann** [comment]
Das ganze ist jetzt in der 0.2.9 implementiert (lädt gerade hoch). Ist aber "Low-Security"-Level, da die PIN im Frontend gecheckt wird. Man kann die PIN also in der Browser-Entwicklerkonsole mit einfachsten JS-Kenntnissen auslesen. Alles andere wäre aber nur mit hohem Aufwand zu schaffen - ich denke so, sollte es für einfache Anwendungen aber ausreichen. Viel Spaß beim Testen!

**Comment by simatec** [comment]
Funktioniert auch super ... cool wäre hier so ein eigenes PIN-Eingabefeld, was sich beim schalten automatisch öffnet. So hatte ich es in der VIS gebaut

**Comment by kwittwer** [comment]
Super! Danke für die schnelle Umsetzung! Das der Pin im Frontend gecheckt wird finde ich nicht schlimm, da es ja nur davor schützen soll das jemand am Wandtablet rumspielt ... 
Ist es möglich, das nach erfolgreicher Pin Eingabe der Dialog automatisch geschlossen wird? 

Ich fände auch ein HTML Pin Pad sehr gut, dann muss nicht die Tastatur verwendet werden um den Pin einzugeben (gerade bei Verwendung von Raspbian mit Touchscreen ist das blöd, da es hier keine native Bildschirmtastatur gibt) 
In meiner alten vis habe ich mal hiermit https://codepen.io/totalnerd_es/pen/AwKLk rumgespielt. 
<img width="369" alt="Bildschirmfoto 2019-10-03 um 00 09 59" src="https://user-images.githubusercontent.com/7408857/66085685-35040880-e572-11e9-8e51-3fe05069c38a.png">

Ich habe die View mit dem Pinpad mal eingefügt, das ist aber keine Alternative da es sehr sehr langsam ist. Anbei ein Bild wie es aussehen könnte... 
<img width="818" alt="Bildschirmfoto 2019-10-03 um 00 12 28" src="https://user-images.githubusercontent.com/7408857/66085870-b8255e80-e572-11e9-9823-1277f8e89316.png">

**Comment by simatec** [comment]
In der Version 0.2.10 funktioniert die PIN Eingabe auf einem Android Tablet mit FullyBrowser nicht. Das Fenster öffnet sich dort nicht.
Im Chrome am MacBook allerdings schon.

**Comment by sbormann** [comment]
Hast Du den Cache geleert?

--
Von meinem iPhone aus gesendet

Am 06.10.2019 um 15:09 schrieb simatec <notifications@github.com>:

﻿

In der Version 0.2.10 funktioniert die PIN Eingabe auf einem Android Tablet mit FullyBrowser nicht. Das Fenster öffnet sich dort nicht.
Im Chrome am MacBook allerdings schon.

**Comment by kwittwer** [comment]
Hi, 
sieht super aus und funktioniert unter Chrome auch bestens. Leider habe ich aber folgendes Problem festgestellt: Ich habe die Seite als „app“ auf dem homescreen von meinem iPhone abgelegt. Wenn ich über diesen Link iQontrol öffne und versuche einen Pin geschützten State zu ändern, dann passiert nix. Bei gleichem Vorgehen über Safari direkt oder über Chrome funktioniert es. Hat jemand einen Tip woran das liegen könnte? VG

**Comment by sbormann** [comment]
Die Homescreen-„Apps“ werden leider ziemlich hard gecached. Lösch die App auf dem Homescreen, öffne die Seite in Safari im Private-Modus uns speicher das ganze neu auf dem Homescreen. Wenn das nicht hilft, dann nach dem Löschen noch die Webseiten-Einstellungen in den Safari-Einstellungen (= Browsercache) löschen.

VG

Von: kwittwer <notifications@github.com>
Gesendet: Sonntag, 6. Oktober 2019 22:58
An: sbormann/ioBroker.iqontrol <ioBroker.iqontrol@noreply.github.com>
Cc: Sebastian Bormann <sebastian@bormann.net>; State change <state_change@noreply.github.com>
Betreff: Re: [sbormann/ioBroker.iqontrol] Pin Abfrage um Wert zu setzen (#86)


Hi,
sieht super aus und funktioniert unter Chrome auch bestens. Leider habe ich aber folgendes Problem festgestellt: Ich habe die Seite als „app“ auf dem homescreen von meinem iPhone abgelegt. Wenn ich über diesen Link iQontrol öffne und versuche einen Pin geschützten State zu ändern, dann passiert nix. Bei gleichem Vorgehen über Safari direkt oder über Chrome funktioniert es. Hat jemand einen Tip woran das liegen könnte? VG

**Comment by kwittwer** [comment]
Hi, 
ich habe es genau so getestet, leider ohne Erfolg. Was könnte ich noch tun?

**Comment by sbormann** [comment]
Das Caching scheint mit ios 13 noch fieser zu sein. Bei mir hat folgendes funktioniert:
* ioBroker neu starten (nur notwendig, falls der Cache im ioBroker nicht deaktiviert wurde)
* App beenden 
* App löschen
* Safari beenden
* Einstellungen/ Safari / Erweitert / Webseitendaten / entsprechenden Server löschen
* iPhone neu booten
* iQontrol in Safari neu laden
* iQontrol neu auf dem Homescreen speichern 
* App vom Homescreen öffnen
* Auf der ersten Seite nach unten wischen, um einen Reload zu erzielen

**Comment by kwittwer** [comment]
Hi, jetzt hat es funktioniert. Ich habe gelesen, das der reload auch durch das einfügen einer Versionsdatei erwungen werde  kann. Ist das eventuell eine Variante um solche Probleme in Zukunft zu verhindern? 
VG

**Comment by sbormann** [comment]
Hi, die Version steckt bei mir in der cache.manifest Datei mit drin. So hatte ich gelesen, sollte es funktionieren - tut es aber zumindest seit iOS 12.2 nicht mehr.  Ist ein schwieriges Thema und es existieren 1000 Tips und Anleitungen, die nach meiner Erfahrung alle nicht zuverlässig funktionieren. Wenn Du mehr weißt, bitte immer mir weiterleiten! Bin sehr daran interessiert! LG!
