### ISSUE TITLE
Can you add a climate device?

### ISSUE THREAD

**Issue by gujiys** [sbormann/ioBroker.iqontrol#87]
Can you add a climate equipment? It has refrigeration, heating, blowing, and other modes. Buttons can switch devices.

**Comment by gujiys** [comment]
My device mode is different from the switch. I can't control the switch status of the device now.
![121](https://user-images.githubusercontent.com/50275040/66269576-7a7b4b00-e87c-11e9-9b8c-8576137003b8.png)

**Comment by sbormann** [comment]
Hi, can you explain in more detail what you mean with "device mode is different from the switch"?

I suppose that /cmnd/mode should be CONTROL_MODE?
Or ist that only the datapoint where you SET the wanted mode and /stat/mode is the ACTUAL mode?
Then you would have to set /stat/mode as CONTROL_MODE, then edit this datapoint via the wrench-icon and set /cmnd/mode as target-value-id.

Does this help?

**Comment by gujiys** [comment]
Forgive me for not expressing myself clearly. I have set / STAT / mode correctly according to your prompt and edited this data point through the wrench icon, setting / cmnd / mode as the target value ID.
![122](https://user-images.githubusercontent.com/50275040/66274443-69006600-e8b1-11e9-90a3-25156c739944.png)
Now I have a problem. My device startup and stop theme is separate. I don't know where to set this theme. The following is marked as startup and stop theme.

![123](https://user-images.githubusercontent.com/50275040/66274562-97cb0c00-e8b2-11e9-8892-697a544f5825.png)
If this data is not set correctly, my device will not be able to start and stop.

**Comment by sbormann** [comment]
Hi, is "ir_gree" really the right root-path? Normally all objects start with
<adapter-name>.<instance-number>/...

**Comment by gujiys** [comment]
yes is it

**Comment by sbormann** [comment]
So, do i understand correctly:
You can set the mode via /cmnd/mode for example to cool, but that does not turn your device on. You have to seperately toggle the /cmnd/power datapoint?

Maybe the scene-adapter can help out:
You could define a scene, that is set to "true", everytime the /cmnd/mode-datapoint is changed to anything else than "off". The scene itsself contains the /cmnd/power-datapoint and turns this automatically to on/off, when the scene state changes to true/false.

**Comment by gujiys** [comment]
tanks
