### ISSUE TITLE
Verschwommene Ansicht 

### ISSUE THREAD

**Issue by papagei1996** [sbormann/ioBroker.iqontrol#88]
Hey 
Erst mal echt Mega adapter der mit mein Leben erleichtert hat sodass ich meine vis fürs Handy nicht noch einmal komplett umgestalten muss.
Allerdings habe ich das Problem dass eine Seite zum Beispiel verschwommen geladen wird.
Beispiel:
Ich bin in der Home Ansicht drücke nun auf die Räume Ansicht. Diese wird nun geladen allerdings ist diese unscharf/verschwommen. Drücke ich nun nochmal drauf lädt es meist nochmals und dann ist es "scharf".
Woran könnte das liegen?
![9F0DC15D-1A6D-4926-BE60-568AF1EBE536](https://user-images.githubusercontent.com/56414714/67151203-9a6e2e00-f2c2-11e9-9ac3-006f370e1bc2.png)

**Comment by sbormann** [comment]
Hi, welche Version nutzt Du? Es gab mal einen Fehler dazu, der behoben wurde. VG!

**Comment by papagei1996** [comment]
Ja habe ich dann auch gefunden und installiert jetzt ist es behoben. Danke für die Rückmeldung hatte eig extra das issue gelöscht gehabt 😄

Gruß Jannik 
Von meinem iPhone gesendet
