### ISSUE TITLE
fertige Konfiguration läd nicht mehr

### ISSUE THREAD

**Issue by MikeyRZW** [sbormann/ioBroker.iqontrol#91]
Hi,
die fertige Konfiguration läd nicht mehr.
Es kommt nur noch die Meldung "Einstellungen laden..."
![grafik](https://user-images.githubusercontent.com/45110596/67635849-212a9880-f8cb-11e9-9c2f-19a000df272f.png)

die Seite läuft aber noch
![grafik](https://user-images.githubusercontent.com/45110596/67635861-369fc280-f8cb-11e9-98d0-cdff063175e9.png)

**Comment by sbormann** [comment]
Hi, bitte mehr infos posten: iqontrol-version, js-controller-version, Fehler im log, Fehler in der Entwicklerkonsole des Browsers (Anleitung dazu steht unter troubleshooting in der readme). VG

**Comment by MikeyRZW** [comment]
Hi,
sorry das ich mich jetzt erst melde. Ich habe das System komplett neu installiert.

![grafik](https://user-images.githubusercontent.com/45110596/67786728-ab136680-fa6f-11e9-8a4e-5d9fb1083e3f.png)

der Fehler scheint temporär zu sein. mal geht es, mal nicht

**Comment by sbormann** [comment]
Hi, welche js-controller-version?

**Comment by MikeyRZW** [comment]
![grafik](https://user-images.githubusercontent.com/45110596/67805868-1a9a4d80-fa92-11e9-842f-d41685b9ec0f.png)

**Comment by MikeyRZW** [comment]
![grafik](https://user-images.githubusercontent.com/45110596/67805910-2f76e100-fa92-11e9-91c6-51c61ab58fb4.png)

**Comment by MikeyRZW** [comment]
gerade aktuallisiert

![grafik](https://user-images.githubusercontent.com/45110596/67806302-df4c4e80-fa92-11e9-8cb5-f59517cbb441.png)

**Comment by Chrisblueeyes83** [comment]
Bei mir ladet die Seite im Browser ewig und es wird nichts angezeigt, nur der Kreis mit der Ladeanzeige. Woran kann das liegen?

**Comment by MikeyRZW** [comment]
Hi,
bei mir trat das auf wenn die aufgerufene Adresse im Browser nicht die lokale Adresse war (ich hatte nach draußen aufrufbar verbogen).

**Comment by sbormann** [comment]
Geht es damit?


https://forum.iobroker.net/post/450689



--
Von meinem iPhone aus gesendet

Am 16.06.2020 um 14:26 schrieb MikeyRZW <notifications@github.com>:

﻿

Hi,
bei mir trat das auf wenn die aufgerufene Adresse im Browser nicht die lokale Adresse war (ich hatte nach draußen aufrufbar verbogen).
