### ISSUE TITLE
Gerätetyp "Externer Link"

### ISSUE THREAD

**Issue by MikeyRZW** [sbormann/ioBroker.iqontrol#92]
Hi,
nachdem ich mein System neu aufgesetzt habe verhalten sich externe Links plötzlich anders,

![grafik](https://user-images.githubusercontent.com/45110596/67863565-6e557700-fb24-11e9-87ef-eeda3d221d9e.png)

![grafik](https://user-images.githubusercontent.com/45110596/67863602-80371a00-fb24-11e9-918e-67c4092b1694.png)

beim click auf die Kachel werden plötzlich die Links aneinander gehangen. Das vorher nicht so.

![grafik](https://user-images.githubusercontent.com/45110596/67863666-9c3abb80-fb24-11e9-976c-0ce4eb27c5aa.png)

System:
![grafik](https://user-images.githubusercontent.com/45110596/67863743-c2f8f200-fb24-11e9-8665-45bc8818716a.png)

![grafik](https://user-images.githubusercontent.com/45110596/67863789-d6a45880-fb24-11e9-8f93-5c695fb2d2d4.png)

**Comment by sbormann** [comment]
Guck mal, du hast Dich bei der URL glaube ich vertippt:
Da steht http:/irgendwas statt http://irgendwas 
Liegt es vielleicht daran? Bitte um kurze Rückmeldung, so lange schließe ich den Issue aber schon mal.
VG!

**Comment by MikeyRZW** [comment]
Hi,
Danke...

Du hast natürlich recht, das war es
