### ISSUE TITLE
toggle doesn't work with js-controller 2.0

### ISSUE THREAD

**Issue by cburghardt** [sbormann/ioBroker.iqontrol#93]
I am using iqontrol to toggle a simple boolean state within the javascript.0 namespace. Since upgrading to js-controller 2.0 the toggle doesn't work anymore. Error from the browser console is attached.
iqontrol 0.2.13
js-controller 2.0.39

![Bildschirmfoto 2019-11-03 um 10 09 10](https://user-images.githubusercontent.com/839480/68082894-677b7c80-fe22-11e9-939d-10dbe4aed723.png)

**Comment by sbormann** [comment]
Hi,
i tried to reproduce, but it works for me. Could you please send the RAW of the object you try to toggle? Wich iQontrol-Device do you use (i tried with Switch)?

**Comment by cburghardt** [comment]
I am also using switch.
I tried it with several objects, one example:

```
{
  "common": {
    "type": "boolean",
    "name": "home.presence.Auto",
    "role": "state"
  },
  "native": {
    "type": "boolean",
    "name": "home.presence.Auto",
    "role": "state"
  },
  "type": "state",
  "from": "system.adapter.javascript.0",
  "user": "system.user.admin",
  "ts": 1571935159852,
  "_id": "javascript.0.home.presence.Auto",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

**Comment by sbormann** [comment]
Das liegt an role: "state". 
Siehe https://forum.iobroker.net/topic/22039/neuer-adapter-visualisierung-iqontrol/1989
VG
