### ISSUE TITLE
Update stable at least to iqontrol 0.2.12 or higher for controller 2.0 stable release please

### ISSUE THREAD

**Issue by Apollon77** [sbormann/ioBroker.iqontrol#94]
on this weekend would be awesome, please create repo PR. Thank you very much

**Comment by sbormann** [comment]
Hi, sorry, bin jetzt erst aus dem Urlaub zurück und wieder am Rechner :)
Würde gerne noch eine Version mit einem Bugfix hochladen und diese dann morgen ins stable übernehmen.

**Comment by Apollon77** [comment]
passt, danke!

**Comment by sbormann** [comment]
Done
