### ISSUE TITLE
Battery symbol allways red HMIP

### ISSUE THREAD

**Issue by MrMadracer** [sbormann/ioBroker.iqontrol#95]
**Describe the bug**  
The battery symbol for Homematic IP thermostat and window sensor shows always red 

**To Reproduce**  
![Screenshot_20191110-102723](https://user-images.githubusercontent.com/43277533/68541840-b6865c00-03a4-11ea-92df-d7170947ab93.png)

The state for all is low battery "false" expect for Kinderzimmer is "true" , but still shows red battery symbol. Inverting shouldn't be the problem then. 
![A+ Gallery_27](https://user-images.githubusercontent.com/43277533/68542016-7d032000-03a7-11ea-9d2b-c59df4c7c77c.jpg)

**Expected behavior**  
Battery symbol should show red or green, if state is false for low battery 

**Screenshots & Logfiles**  

**Versions:**  
 - Adapter version: 0.2.13
 - JS-Controller version: 2.0.39
 - Node version: 12.13.0
 - Operating system: Pi 3+

**Additional context**

**Comment by sbormann** [comment]
Hi,
please show me the RAW of the lowBat-Datapoint.
I will reference this here 
https://forum.iobroker.net/topic/22039/neuer-adapter-visualisierung-iqontrol/1973 
to ask, if anyone else had this problem - as i dont have HMIP-components to test ist.
Thanks!

**Comment by MrMadracer** [comment]
This is for false
`{
  "type": "state",
  "common": {
    "name": "lowBat",
    "type": "string",
    "role": "info",
    "read": true,
    "write": false
  },
  "native": {},
  "from": "system.adapter.hmip.0",
  "ts": xxxxxxxxxxxxxxxx,
  "_id": "hmip.0.devices.3014F711A0000Axxxxxxxxx.channels.0.lowBat",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

And this is for true
`{
  "type": "state",
  "common": {
    "name": "lowBat",
    "type": "string",
    "role": "info",
    "read": true,
    "write": false
  },
  "native": {},
  "from": "system.adapter.hmip.0",
  "ts": xxxxxxxxxxxxxxx,
  "_id": "hmip.0.devices.3014F711A0000Axxxxxxxxxx.channels.0.lowBat",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

**Comment by sbormann** [comment]
Hi, common.type is string - but it schould be boolean. You can modify the type for iqontrol by clicking on the wrench icon. Greetings!

**Comment by MrMadracer** [comment]
Thanks, that did solve it.
