### ISSUE TITLE
Feature-Wunsch "Ganze Ansichten kopieren"

### ISSUE THREAD

**Issue by AlexanderSch90** [sbormann/ioBroker.iqontrol#96]
Hallo, danke für den Adapter. Schön wäre es, wenn man ganze Ansichten unter einem neuen Namen kopieren könnte. So könnte man gleiche Anwendungsfälle z.B. eine Heizungssteuerung auf Einzelraumbasis schneller "zusammenklicken". Aktuell muss man jeden Raum (jede Ansicht) einzelnt zusammen klicken...

Falls du es nicht implementieren magst: Gibt es ggf. eine Möglichkeit die Quelldatei in Notepad+ oder ähnliches aufzurufen und so ganze Sichten zu kopieren?

**Comment by sbormann** [comment]
Hallo,
folgendes sollte funktionieren:
Einstellungen exportieren, die json in notepad++ anpassen und wieder importieren.

![image](https://user-images.githubusercontent.com/49171332/68669585-34846780-054b-11ea-9e43-b38bb022ceb5.png)


Alternativ kann man auch gleich den NATIVE-Teil bzw. den RAW des Objekts
system.adapter.iqontrol.0 
modifizieren und danach die iQontrol-Instanz neu starten.

![image](https://user-images.githubusercontent.com/49171332/68669547-19195c80-054b-11ea-9411-181cc9a7eaa6.png)


Ich hoffe, das hilft?
