### ISSUE TITLE
Feature Wunsch: Kopieren der Geräte innerhalb einer Ansicht

### ISSUE THREAD

**Issue by AlexanderSch90** [sbormann/ioBroker.iqontrol#97]
Hallo,

toll wäre es, wenn man einzelne "Geräte" innerhalb einer Ansicht mit allen Eigenschaften kopieren könnte. Ggf. mit einer Möglichkeit gleich mehrere Objekte auszuwählen und diese dann in einem Zug zu kopieren. In meinem Fall baue ich eine Heizungssteuerung mit Kombinationen aus Zeit und Temperatur je Raum. Zeit und Temperatur ist quasi immer das selbe "Gerät" nur halt eine logische Nummer fortlaufend in meinem Objektbaum. Statt "alles" neu zusammenzuklicken, wäre eine Kopierfunktion deutlich einfacher. 

Auch wäre es toll, wenn man die Reihenfolge statt Pfeilen auch per Zahlen durchführen könnte... Ich musste schonmal ein Objekt von ganz unten nach ganz oben Positionieren. Das dauert mit den Pfeilen bei mir recht lange...

Danke!

**Comment by sbormann** [comment]
Hi, das mit dem Kopieren geht:
![image](https://user-images.githubusercontent.com/49171332/68669721-80371100-054b-11ea-898f-0e62bfb33341.png)

Das mit den Pfeilen ist mir auch ein Dorn im Auge - liegt aber daran, dass ich eine vom ioBroker zur Verfügung gestellte Tabellenfunktion nutze, die leider nur das her gibt.

Das zu ändern hieße quasi von vorne anzufangen - und das schaffe ich zeitlich einfach nicht. Deshalb muss man da leider irgendwie durch - aber zum Glück muss man da ja auch nicht sooo oft dran.

VG!
