### ISSUE TITLE
Light Coloured LEDs - combination of ALTERNATIVE_COLORSPACE and CT missing (

### ISSUE THREAD

**Issue by meia24** [sbormann/ioBroker.iqontrol#98]
Ich habe einen "OSRAM Smart+ LED Streifen" über den Zigbee-Adapter mit einem CC2531-Zigbee-Empfänger angeschlossen. Der Streifen kann dimmen, RGB Farbwechsel und Farbtemperatur WW bis CW.
https://www.amazon.de/gp/product/B07482ZJLY

Als States sind im Zigbee-Adapter verfügbar:
* switch = iqontrol state
* level.dimmer = iqontrol level
* level.color.rgb = iqontrol ALTERNATIVE_COLORSPACE_VALUE mit "#RGB" (Hue etc funktioniert nicht)
* level.color.temperature = iqontrol CT mit Mired-Werten 100-600

Der State "color.rgb" erwartet #RGB-Werte ohne den Zusatz für die Farbtemperatur. Der zusätzliche State "color.temperature" erwartet scheinbar mired-Werte zwischen 100-600. 
Leider ist es in iqontrol derzeit nicht möglich, beide getrennten States zu nutzen. Es wäre nur möglich mit einem "#RGBW" etc als ALTERNATIVE_COLORSPACE_VALUE. 
Wenn ich in iqontrol ALTERNATIVE_COLORSPACE_VALUE und CT zusammen verwende, dann wird der CT-Wert (Farbtemp) vom  ALTERNATIVE_COLORSPACE_VALUE (Farbton & Sättigung) übersteuert. 

Mache ich etwas falsch bzw. welche Möglichkeiten gibt es? Enhancement?

Danke, Meia

**Comment by sbormann** [comment]
Hi, habe es gerade noch mal nachgestellt, bei mir funktioniert es problemlos.
So ist meine Konfig:
![image](https://user-images.githubusercontent.com/49171332/69075062-f696b000-0a30-11ea-9a03-9e1c9879dd31.png)

Und so sieht es aus:
![image](https://user-images.githubusercontent.com/49171332/69075098-06ae8f80-0a31-11ea-9cc8-4efc37fe0ecc.png)

Wenn ich den Farbe oder Sättigungs-Slider bewege, wird lediglich der ALTERNATIVE_COLORSPACE_VALUE geändert.
Wenn ich den Farbtemperatur-Slider bewege, wird der CT Datenpunkt geändert. 
Die beiden Datenpunkte beeinflussen sich gegenseitig nicht.

Macht das vielleicht der Osram-Adpater selbst?

**Comment by meia24** [comment]
Hi,
ich habe jetzt alle Varianten durchgetestet mit folgendem Ergebnis:
* Wenn ich keine Schalter in iqontrol einrichte und über iobroker-Admin in den Objekten level.color.temperature verändere, dann bleibt das auch so und wird nicht sofort durch den RBG-Wert überschrieben > es kann also nicht am zigbee-adapter liegen
* wenn ich einen Schalter in iqontrol einrichte mit CT und ALTERNATIVE_COLORSPACE_VALUE und im Handy-Browser (Chrome) den CT-Wert ändere, wird er sofort durch den RGB-Wert überschrieben
* wenn ich dann im iobroker-Admin den level.color.temperature (CT) ändere, wird er auch mit dem RGB-Wert überschrieben (Browser-Fenster läuft auf dem Handy im Hintergrund)
* wenn ich auf dem Handy das Browser-Fenster komplett schließe und dann im iobroker-Admin den level.color.temperature (CT) ändere, wird er NICHT direkt durch den RGB-Wert überschrieben.
* wenn ich dann wieder ein Browser-Fenster mit iqontrol öffne, wird ohne etwas aktiv zu klicken der RGB-Wert wieder gesendet und die Farbe ändert sich

D.h. das iqontrol-Fenster schickt den RGB-Wert immer nach.

VG, Meia

**Comment by sbormann** [comment]
Hmm, klingt sehr gut untersucht, ich kann es mir im Moment aber noch nicht ganz erklären. Kannst Du mal bitte bei laufender Entwicklerkonsole (F12 im Browser) schauen, welche Meldungen iQontrol abgibt, wenn sich der CT-Wert (fälschlicherweise) ändert?

**Comment by meia24** [comment]
Hier das Schalter-Menü:
![image](https://user-images.githubusercontent.com/48688110/69372641-619aed80-0ca2-11ea-9576-4383beb8f781.png)

Wenn ich nur die Temperatur von 185 auf 490 schiebe, kommen folgende Meldungen:

index.js:692 >>>>>> setState zigbee.0.7cb03eaa0a005f8d.colortemp: 185 --> 490
index.js:720        converted state to number. New value is: 490
index.js:1238 >> ack: false val: 490 newVal: 490
index.js:1238 >> ack: true val: 490 newVal: 490
index.js:1241 << ack-val reached new val: preventUpdate regular ended.
index.js:1476 Converting #RGB from #ff0004 to H|S|B/CT|B...
index.js:1578 ...result is 359|100|100/null|null
index.js:1425 Converting H|S|B/CT|B from 359|100|100/97.14285714285714|null to #RGB...
index.js:1467 ...result is #ff0004
index.js:692 >>>>>> setState zigbee.0.7cb03eaa0a005f8d.color: #ff0004 --> #ff0004
index.js:1476 Converting #RGB from #ff0004 to H|S|B/CT|B...
index.js:1578 ...result is 359|100|100/null|null
index.js:1425 Converting H|S|B/CT|B from 359|100|100/97.14285714285714|null to #RGB...
index.js:1467 ...result is #ff0004
index.js:692 >>>>>> setState zigbee.0.7cb03eaa0a005f8d.color: #ff0004 --> #ff0004
2index.js:1238 >> ack: false val: #ff0004 newVal: #ff0004
index.js:1238 >> ack: false val: #ff0004 newVal: #ff0004
index.js:1476 Converting #RGB from #ff0004 to H|S|B/CT|B...
index.js:1578 ...result is 359|100|100/null|null
index.js:1238 >> ack: false val: #ff0004 newVal: #ff0004
index.js:1476 Converting #RGB from #ff0004 to H|S|B/CT|B...
index.js:1578 ...result is 359|100|100/null|null
index.js:1238 >> ack: true val: #ff0004 newVal: #ff0004
index.js:1241 << ack-val reached new val: preventUpdate regular ended.
index.js:1476 Converting #RGB from #ff0004 to H|S|B/CT|B...
index.js:1578 ...result is 359|100|100/null|null
index.js:1476 Converting #RGB from #ff0004 to H|S|B/CT|B...
index.js:1578 ...result is 359|100|100/null|null
index.js:5246 Page visible-event - socket is connected

**Comment by sbormann** [comment]
Hi, und was passiert dann mit dem CT-Wert? Geht er zurück auf 185?

**Comment by meia24** [comment]
Hi, der CT-Wert im iobroker bleibt auf 490. Dadurch, dass beim Gerät aber zuletzt der RGB-Wert ankommt, wird nicht warmweiß, sondern bunt gezeigt.

**Comment by meia24** [comment]
Das gleiche Problem habe ich mit dieser Osram:
OSRAM Smart+ LED, ZigBee Lampe mit E27 Sockel, warmweiß bis tageslicht, Farbwechsel RGB, dimmbar.
https://www.amazon.de/gp/product/B074PZSW1Y

Gibt's da schon eine Lösung?

**Comment by sbormann** [comment]
Sorry, dass sich hier lange nichts getan hat.
Ich habe jetzt das Problem noch mal anschaut. Das ganze ist ziemlich komplex und ich hab meine eigene Programmierung auch nur noch schwer nachvollziehen können - was updatet da wen in welcher Konstellation u.s.w....

Ich habe in der nächsten Version (kommt heute Abend denke ich) noch mal eine Abfrage eingebaut, die das Verhalten verhindern soll. Ich hoffe, dadurch entstehen jetzt keine neuen Probleme...! 

Falls doch, bitte um Rückmeldung!

LG

**Comment by bishopbkp** [comment]
Hi sbormann, 

leider habe ich das selbe Verhalten wie meia24 beschrieben hat. 
Der CT Wert wird beim öffnen auf dem Handy Browser (Chrome) vom RGB Wert überschrieben.
Ich habe den Adapter in der Version 0.2.16 installiert.
Admin: 4.0.10
Node.js:  12.16.2
js-controller: 2.2.9

Hast du ggf. eine Idee, wie ich diesem Verhalten entgegensteuern kann?

Beste Grüße
bishop

**Comment by frodo777** [comment]
ich habe das gleiche verhalten bei all meinen Osram Farblichtern. 2x Gartenpole mini und LED Stripe

**Comment by sbormann** [comment]
Welche iQontrol-Version?

**Comment by sbormann** [comment]
Bitte noch mal ein Log vom Browser (nicht iobroker) schicken, siehe troubleshooting in der readmy. VG

**Comment by frodo777** [comment]
1.1.5

**Comment by frodo777** [comment]
Wenn ich eine Kachel automatisch erstellen lasse kommt nur ein Dimmer und Farbtemperatur. Die Werte ändern sich auch nur bis 100 und ich glaube da muss was anders stehen (bis 350). Ich kann auch nur an und ausstellen.
![image](https://user-images.githubusercontent.com/37746335/89119726-dde00480-d4b0-11ea-8618-56ee962783c8.png)

![image](https://user-images.githubusercontent.com/37746335/89119756-0667fe80-d4b1-11ea-8138-4b4e2a049d9d.png)

**Comment by frodo777** [comment]
![image](https://user-images.githubusercontent.com/37746335/89120229-ee927980-d4b4-11ea-8252-666a09ffa765.png)

**Comment by sbormann** [comment]
Leider kann ich auf dem Screenshot die Datenpunkte nicht erkennen (zigbee.0.xxxx), hier bitte noch mal schreiben, was Du wo angegeben hast (insbesondere bei ALTERNATIVE_COLORSPACE_VALUE). 

Welche Einstellung hast Du für den ALTERNATIVE_COLORSPACE weiter unten gewählt?

Den Wertebereich (min und max), falls vom Zigbee-Adapter nicht richtig zur Verfügung gestellt, kann man mit dem Schraubenschlüssel bearbeiten (z.B. min = 0, max = 350). Was man da braucht, muss man ausprobieren (bei meinen Milights z.B. ist es 2700 bis 6500)

**Comment by frodo777** [comment]
Als die Daten von Phoscon und deconz kamen hat iqontrol alles erkannt und richtig eingestellt. So wie es aussieht betrifft es alle farbigen Lampen egal welcher Hersteller. Da sitze ich ja Tage wenn ich alles selbst einstellen muss . Ich habe im Garten 10 farbige Lampen von verschiedenen Herstellern .
![image](https://user-images.githubusercontent.com/37746335/89120466-d6bbf500-d4b6-11ea-89ca-2dead1d5870a.png)
![image](https://user-images.githubusercontent.com/37746335/89120517-2ef2f700-d4b7-11ea-8926-ff6fa886307a.png)
und was noch dazukommt ist das ich gar nicht weiß was man da einstellen muss. Da gibt es so viele Kombinationen. Und desto mehr ich einstelle desto langsamer wird iqontrol.

**Comment by sbormann** [comment]
Das kriegen wir schon hin.
Wenn Du einen ALTERNATIVE_COLORSPACE_VALUE verwendest, dann musst Du unten auch angeben, welches Format (Farbraum) dieser haben soll, zum Beispiel #RGB. Aktuell steht der auf "none", d.h. der Datenpunkt ALTERNATIVE_COLORSPACE_VALUE wird gar nicht benutzt. Du musst schauen, was Deine Lampe da erwartet und das entsprechend unten eingeben:
* Wenn die Lampe HUE und SATURATION zur Verfügung stellt, nutze die entsprechenden Datenpunkte und lass ALTERNATIVE_COLORSPACE_VALUE leer (und den Farbraum unten auf "none").
* Wenn die Lampe kein HUE und SATURATION, sondern einen anderen Farbraum erwartet (z.B. #RGB), dann nutze ALTERNATIVE_COLORSPACE_VALUE und stelle den Farbraum unten entsprechend ein. Die Datenpunkte HUE und SATURATION sollen dann leer bleiben.

**Comment by frodo777** [comment]
![image](https://user-images.githubusercontent.com/37746335/89120790-4fbc4c00-d4b9-11ea-880b-c93939c7b67a.png)

**Comment by frodo777** [comment]
ich habe einen hex Wert eingestellt und die Farbe hat sich geändert. Bei welcher Einstellung wird den der Hex Wert eingestellt 
![image](https://user-images.githubusercontent.com/37746335/89121013-73809180-d4bb-11ea-8b09-e83b92699081.png)

**Comment by sbormann** [comment]
Dann stell mal "#RGB" als Farbraum ein.

Für die Farbtemperatur hilft dann nur ausprobieren. Einfach mal (nicht im iQontrol, sondern direkt im ioBroker) ein paar Werte eintippen und schauen, was passiert. Dann muss man die Grenzen nach oben und unten testen und das als min und max eingeben. Dann sollte es laufen.

**Comment by frodo777** [comment]
![image](https://user-images.githubusercontent.com/37746335/89121127-69ab5e00-d4bc-11ea-951c-0e0f1002ec7a.png)
 habe auf #RGB gestellt aber keine Farbscala in iqontrol
![image](https://user-images.githubusercontent.com/37746335/89121153-b4c57100-d4bc-11ea-83d8-c55afcf1ff28.png)

**Comment by sbormann** [comment]
Dumme Frage: Gespeichert und alles neu geladen hast Du?

**Comment by frodo777** [comment]
ja habe ich allerdings kommt immer diese Fehlermeldung 
![image](https://user-images.githubusercontent.com/37746335/89121208-3fa66b80-d4bd-11ea-8575-432355f1941f.png)

**Comment by sbormann** [comment]
Die kann man ignorieren, es wird trotzdem gespeichert (liegt am Admin-Adapter und soll demnächst behoben werden).
iQontrol neu geladen? Dann bitte noch mal Log posten, falls der Fehler weiter besteht.

**Comment by frodo777** [comment]
![image](https://user-images.githubusercontent.com/37746335/89121557-205d0d80-d4c0-11ea-8b49-d2ba94908145.png)

**Comment by frodo777** [comment]
es scheint am Browser zu liegen. Wenn ich im Browser auf aktualisieren drücke ist die Farbscala verschwunden. Schalte ich zwischen den Ansichten hin und her erscheint die Farbscala wieder.

**Comment by frodo777** [comment]
Dieses verhalten ist bei Chrome und Edge gleich einen anderen Browser habe ich nicht installiert

**Comment by sbormann** [comment]
Hi, habe das ganze noch mal mit Deinen Hinweisen nachgestellt und konnte den Fehler reproduzieren und hoffentlich auch beheben. Kannst Du es mal mit der aktuellen Version von Github ausprobieren?

Das geht so:
![image](https://user-images.githubusercontent.com/49171332/89126702-1d761300-d4e8-11ea-8d57-750e2415c443.png)

Anschließend unbedingt manuell ein Upload machen (siehe https://github.com/sbormann/ioBroker.iqontrol#troubleshooting) und iQonrol neu laden.

Hoffe es geht damit???

**Comment by frodo777** [comment]
Danke für die schnelle Hilfe jetzt geht es wunderbar . Ich hoffe ich hab Dir nicht den Sonntag vermiest. Iqontrol ist die beste Visualisierung , einfach zu bedienen und man kommt schnell zum Erfolg .

**Comment by sbormann** [comment]
👍  freu mich, dass es geht.

**Comment by MarkusMG3** [comment]
Hallo zusammen, habe die selbe Problematik.
Blicke allerdings nicht dahinter, was ihr nach dem Update genau gemacht habt. Sorry für die Fragestellung, bin in der lern Phase und froh, dass ich schon Geräte am kaufen habe. 
Danke
Gruß Markus
